import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type AppLanguage = "en" | "fr" | "es" | "ar" | "zh" | "ja" | "sw" | "de";

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGES: { code: AppLanguage; name: string; flag: string; native: string }[] = [
  { code: "en", name: "English", flag: "🇺🇸", native: "English" },
  { code: "fr", name: "French", flag: "🇫🇷", native: "Français" },
  { code: "es", name: "Spanish", flag: "🇪🇸", native: "Español" },
  { code: "ar", name: "Arabic", flag: "🇸🇦", native: "العربية" },
  { code: "zh", name: "Chinese", flag: "🇨🇳", native: "中文" },
  { code: "ja", name: "Japanese", flag: "🇯🇵", native: "日本語" },
  { code: "sw", name: "Swahili", flag: "🇰🇪", native: "Kiswahili" },
  { code: "de", name: "German", flag: "🇩🇪", native: "Deutsch" },
];

// Translation dictionaries
const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.calendar": "Calendar",
    "nav.add": "Add",
    "nav.library": "Library",
    "nav.profile": "Profile",
    // Home
    "home.morning": "Morning",
    "home.afternoon": "Afternoon",
    "home.evening": "Evening",
    "home.quickCapture": "Quick Capture",
    "home.recentEntries": "Recent Entries",
    "home.viewAll": "View All",
    "home.noEntries": "No entries yet",
    "home.createFirst": "Create Your First Entry",
    // Record
    "record.title": "New Entry",
    "record.tapToRecord": "Tap to record your thoughts",
    "record.write": "Write",
    "record.howFeeling": "How are you feeling?",
    "record.selectMood": "Select your mood",
    "record.enhance": "Enhance",
    "record.save": "Save Entry",
    "record.saving": "Saving...",
    "record.recording": "Recording...",
    "record.processing": "Processing...",
    "record.limitReached": "Limit Reached",
    "record.textLimit": "Text entries",
    "record.audioLimit": "Audio entries",
    "record.today": "today",
    "record.thisWeek": "this week",
    "record.upgradePremium": "Upgrade to Premium",
    "record.newEntry": "NEW ENTRY",
    "record.howAreYou": "How are you, ",
    "record.tapToRecordAssessment": "Tap to Record Assessment",
    "record.recordingTime": "Recording {time}... Tap to stop",
    "record.audioLimitReached": "Audio limit reached",
    "record.writeLimit": "Write",
    "record.mood": "Mood",
    "record.aiCoachReflection": "AI COACH REFLECTION",
    "record.recentEntries": "RECENT ENTRIES",
    "record.viewAll": "View All",
    "record.whatsOnMind": "What's on your mind today?",
    "record.continue": "Continue",
    "record.originalTranscription": "Original Transcription",
    "record.enhanceWithAI": "Enhance with AI",
    "record.enhancing": "Enhancing...",
    "record.aiEnhanced": "AI Enhanced",
    "record.addTitle": "Add a title (optional)",
    "record.voicePlaybackLanguage": "Voice Playback Language",
    "record.chooseLanguage": "Choose which language to hear your story in",
    "record.generatingVoice": "Generating Voice...",
    "record.previewVoice": "Preview Voice (Optional)",
    "record.pause": "Pause",
    "record.playPreview": "Play Preview",
    "record.saveEntry": "Save Entry",
    "record.entrySaved": "Entry Saved!",
    "record.entrySavedDesc": "Your journal entry has been saved.",
    "record.textEntriesCount": "Text entries: {count}/2 today",
    "record.audioEntriesCount": "Audio entries: {count}/1 this week",
    "record.upgradeUnlimited": "Upgrade for unlimited",
    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.profile": "Profile",
    "settings.security": "Security & PIN",
    "settings.appearance": "Appearance",
    "settings.themes": "Themes",
    "settings.fonts": "Fonts",
    "settings.darkMode": "Dark Mode",
    "settings.features": "Features",
    "settings.voice": "Voice Settings",
    "settings.goals": "Goals & Interests",
    "settings.reminders": "Reminders",
    "settings.export": "Export Journal",
    "settings.coaching": "AI Coaching",
    "settings.signOut": "Sign Out",
    "settings.admin": "Admin Dashboard",
    "settings.manageSubscription": "Manage Subscription",
    // Coaching
    "coaching.title": "AI Coach",
    "coaching.subtitle": "Your personal soul coach",
    "coaching.analyze": "Analyze My Week",
    "coaching.analyzing": "Analyzing...",
    "coaching.usageCounter": "coaching calls used this month",
    "coaching.limitReached": "Monthly coaching limit reached",
    // Calendar
    "calendar.title": "Journal Calendar",
    "calendar.noEntries": "No entries for this date",
    // Insights
    "insights.title": "Insights",
    "insights.moodTrend": "Mood Trend",
    "insights.weeklyActivity": "Weekly Activity",
    // Export
    "export.title": "Export Journal",
    "export.download": "Download all your entries",
    "export.soulBook": "Soul Book Builder (PDF)",
    "export.quickMarkdown": "Quick JSON / Markdown",
    "export.quickPDF": "Quick PDF",
    // Common
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.success": "Success",
    "common.upgrade": "Upgrade",
    "common.premium": "Premium",
    "common.language": "Language",
    // Pricing
    "pricing.title": "Choose Your Plan",
    "pricing.subtitle": "Unlock the full Echo Diary experience",
    "pricing.free": "Free",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/month",
    "pricing.forever": "/forever",
    "pricing.perYear": "/year",
    "pricing.premiumActive": "Premium Active",
    "pricing.granted": "Granted",
    "pricing.yearly": "Yearly",
    "pricing.monthly": "Monthly",
    "pricing.renewsOn": "Renews",
    "pricing.manageSubscription": "Manage Subscription",
    "pricing.currentPlan": "Current Plan",
    "pricing.yourPlan": "Your Plan",
    "pricing.premiumMonthly": "Premium Monthly",
    "pricing.premiumYearly": "Premium Yearly",
    "pricing.save30": "SAVE 30%",
    "pricing.justPerMonth": "Just",
    "pricing.savePerYear": "save",
    "pricing.subscribeMonthly": "Subscribe Monthly",
    "pricing.subscribeYearly": "Subscribe Yearly — Best Value",
    "pricing.refreshStatus": "Refresh subscription status",
    "pricing.loading": "Loading...",
    // Calendar
    "calendar.visualHistory": "VISUAL HISTORY",
    "calendar.thisMonth": "This month",
    "calendar.entries": "entries",
    "calendar.entry": "Entry",
    "calendar.allEntries": "All entries",
    "calendar.viewEntry": "View Entry",
    "calendar.noEntriesDay": "No entries for this day",
    "calendar.createEntry": "Create Entry",
    "calendar.happy": "HAPPY",
    "calendar.fine": "FINE",
    "calendar.sad": "SAD",
    // Insights
    "insights.yourPatterns": "Your journaling patterns",
    "insights.noEntries": "No entries yet",
    "insights.createFirst": "Create Your First Entry",
    "insights.totalEntries": "Total Entries",
    "insights.bestStreak": "Best Streak",
    "insights.days": "days",
    "insights.mostFelt": "Most Felt",
    "insights.avgLength": "Avg. Length",
    "insights.min": "min",
    "insights.thisWeek": "This Week",
    "insights.languagesUsed": "Languages Used",
    "insights.detailedInsights": "Detailed Insights",
    // Export
    "export.exportYourEntries": "Export Your Entries",
    "export.exportDescription": "Download all your journal entries as a file to keep a backup or share with others.",
    "export.soulBookDesc": "Customizable cover, fonts & layout for printing",
    "export.markdownDesc": "Plain text backup of all entries",
    "export.quickPDFDesc": "Simple formatted export, no customization",
    "export.exportInfo": "Your exported file will include all journal entries with their dates, moods, and content.",
    "export.noEntries": "No entries to export",
    "export.createFirst": "Create some journal entries first!",
    "export.successMarkdown": "Export successful! 📝",
    "export.entriesExported": "entries exported to Markdown.",
    "export.successPDF": "PDF ready! 📄",
    "export.pdfDescription": "entries prepared. Use print dialog to save as PDF.",
    "export.failed": "Export failed",
    "export.failedDesc": "Something went wrong. Please try again.",
    "export.journalExport": "Journal Export",
    "export.journalExportDesc": "Export your journal as PDF or Markdown and build beautiful soul books. Upgrade to Premium to unlock.",
    // Onboarding
    "onboarding.welcome": "Welcome to",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "Your private space for self-reflection. Speak your thoughts, let AI refine them, and discover insights from your Soul Mirror.",
    "onboarding.feature1": "Record voice entries effortlessly",
    "onboarding.feature2": "AI-powered reflections & coaching",
    "onboarding.feature3": "Export your journey as a book",
    "onboarding.yourGoals": "Your Goals",
    "onboarding.goalsDesc": "What are you working toward? Pick a few.",
    "onboarding.worldview": "Worldview",
    "onboarding.worldviewDesc": "Helps personalize your Soul Mirror reflections.",
    "onboarding.yourStrengths": "Your Strengths",
    "onboarding.strengthsDesc": "What do you bring to the table?",
    "onboarding.yourFears": "Your Fears",
    "onboarding.fearsDesc": "Being honest helps your reflections go deeper.",
    "onboarding.cloneVoice": "Clone Your Voice",
    "onboarding.cloneVoiceDesc": "Record 30 seconds of speech and your Soul Mirror will read reflections back in your own voice.",
    "onboarding.setupVoiceClone": "Set Up Voice Clone",
    "onboarding.doLater": "You can always do this later in Settings.",
    "onboarding.allSet": "You're All Set!",
    "onboarding.allSetDesc": "Start by recording your first journal entry. Speak freely — AI will handle the rest.",
    "onboarding.startJournaling": "Start Journaling",
    "onboarding.saving": "Saving...",
    "onboarding.skipForNow": "Skip for now",
    "onboarding.getStarted": "Get Started",
    "onboarding.continue": "Continue",
    "onboarding.back": "Back",
    "onboarding.welcomeToast": "Welcome aboard! 🎉",
    "onboarding.profileReady": "Your Soul Profile is ready.",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.calendar": "Calendrier",
    "nav.add": "Ajouter",
    "nav.library": "Bibliothèque",
    "nav.profile": "Profil",
    "home.morning": "Bonjour",
    "home.afternoon": "Bon après-midi",
    "home.evening": "Bonsoir",
    "home.quickCapture": "Capture rapide",
    "home.recentEntries": "Entrées récentes",
    "home.viewAll": "Voir tout",
    "home.noEntries": "Aucune entrée",
    "home.createFirst": "Créer votre première entrée",
    "record.title": "Nouvelle entrée",
    "record.tapToRecord": "Appuyez pour enregistrer vos pensées",
    "record.write": "Écrire",
    "record.howFeeling": "Comment vous sentez-vous ?",
    "record.selectMood": "Sélectionnez votre humeur",
    "record.enhance": "Améliorer",
    "record.save": "Sauvegarder",
    "record.saving": "Sauvegarde...",
    "record.recording": "Enregistrement...",
    "record.processing": "Traitement...",
    "record.limitReached": "Limite atteinte",
    "record.textLimit": "Entrées texte",
    "record.audioLimit": "Entrées audio",
    "record.today": "aujourd'hui",
    "record.thisWeek": "cette semaine",
    "record.upgradePremium": "Passer à Premium",
    "record.newEntry": "NOUVELLE ENTRÉE",
    "record.howAreYou": "Comment allez-vous, ",
    "record.tapToRecordAssessment": "Appuyez pour enregistrer",
    "record.recordingTime": "Enregistrement {time}... Appuyez pour arrêter",
    "record.audioLimitReached": "Limite audio atteinte",
    "record.writeLimit": "Écrire",
    "record.mood": "Humeur",
    "record.aiCoachReflection": "RÉFLEXION DU COACH IA",
    "record.recentEntries": "ENTRÉES RÉCENTES",
    "record.viewAll": "Voir tout",
    "record.whatsOnMind": "Qu'avez-vous en tête aujourd'hui ?",
    "record.continue": "Continuer",
    "record.originalTranscription": "Transcription originale",
    "record.enhanceWithAI": "Améliorer avec l'IA",
    "record.enhancing": "Amélioration...",
    "record.aiEnhanced": "Amélioré par l'IA",
    "record.addTitle": "Ajouter un titre (optionnel)",
    "record.voicePlaybackLanguage": "Langue de lecture vocale",
    "record.chooseLanguage": "Choisissez la langue pour écouter votre histoire",
    "record.generatingVoice": "Génération de la voix...",
    "record.previewVoice": "Aperçu vocal (Optionnel)",
    "record.pause": "Pause",
    "record.playPreview": "Écouter l'aperçu",
    "record.saveEntry": "Sauvegarder l'entrée",
    "record.entrySaved": "Entrée sauvegardée !",
    "record.entrySavedDesc": "Votre entrée de journal a été sauvegardée.",
    "record.textEntriesCount": "Entrées texte : {count}/2 aujourd'hui",
    "record.audioEntriesCount": "Entrées audio : {count}/1 cette semaine",
    "record.upgradeUnlimited": "Passer en illimité",
    "settings.title": "Paramètres",
    "settings.account": "Compte",
    "settings.profile": "Profil",
    "settings.security": "Sécurité & PIN",
    "settings.appearance": "Apparence",
    "settings.themes": "Thèmes",
    "settings.fonts": "Polices",
    "settings.darkMode": "Mode sombre",
    "settings.features": "Fonctionnalités",
    "settings.voice": "Paramètres vocaux",
    "settings.goals": "Objectifs & Intérêts",
    "settings.reminders": "Rappels",
    "settings.export": "Exporter le journal",
    "settings.coaching": "Coach IA",
    "settings.signOut": "Déconnexion",
    "settings.admin": "Tableau de bord admin",
    "settings.manageSubscription": "Gérer l'abonnement",
    "coaching.title": "Coach IA",
    "coaching.subtitle": "Votre coach personnel",
    "coaching.analyze": "Analyser ma semaine",
    "coaching.analyzing": "Analyse en cours...",
    "coaching.usageCounter": "appels coaching utilisés ce mois",
    "coaching.limitReached": "Limite mensuelle de coaching atteinte",
    "calendar.title": "Calendrier du journal",
    "calendar.noEntries": "Aucune entrée pour cette date",
    "insights.title": "Aperçus",
    "insights.moodTrend": "Tendance d'humeur",
    "insights.weeklyActivity": "Activité hebdomadaire",
    "export.title": "Exporter le journal",
    "export.download": "Téléchargez toutes vos entrées",
    "export.soulBook": "Constructeur de livre d'âme (PDF)",
    "export.quickMarkdown": "JSON / Markdown rapide",
    "export.quickPDF": "PDF rapide",
    "common.back": "Retour",
    "common.cancel": "Annuler",
    "common.save": "Sauvegarder",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.loading": "Chargement...",
    "common.error": "Une erreur est survenue",
    "common.success": "Succès",
    "common.upgrade": "Passer en Premium",
    "common.premium": "Premium",
    "common.language": "Langue",
    "pricing.title": "Choisissez votre plan",
    "pricing.free": "Gratuit",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mois",
    "pricing.subtitle": "Débloquez l'expérience complète Echo Diary",
    "pricing.forever": "/pour toujours",
    "pricing.perYear": "/an",
    "pricing.premiumActive": "Premium actif",
    "pricing.granted": "Offert",
    "pricing.yearly": "Annuel",
    "pricing.monthly": "Mensuel",
    "pricing.renewsOn": "Renouvellement",
    "pricing.manageSubscription": "Gérer l'abonnement",
    "pricing.currentPlan": "Plan actuel",
    "pricing.yourPlan": "Votre plan",
    "pricing.premiumMonthly": "Premium mensuel",
    "pricing.premiumYearly": "Premium annuel",
    "pricing.save30": "ÉCONOMISEZ 30%",
    "pricing.justPerMonth": "Seulement",
    "pricing.savePerYear": "économisez",
    "pricing.subscribeMonthly": "S'abonner mensuellement",
    "pricing.subscribeYearly": "S'abonner annuellement — Meilleur prix",
    "pricing.refreshStatus": "Actualiser le statut d'abonnement",
    "pricing.loading": "Chargement...",
    "calendar.visualHistory": "HISTORIQUE VISUEL",
    "calendar.thisMonth": "Ce mois-ci",
    "calendar.entries": "entrées",
    "calendar.entry": "Entrée",
    "calendar.allEntries": "Toutes les entrées",
    "calendar.viewEntry": "Voir l'entrée",
    "calendar.noEntriesDay": "Aucune entrée pour ce jour",
    "calendar.createEntry": "Créer une entrée",
    "calendar.happy": "CONTENT",
    "calendar.fine": "BIEN",
    "calendar.sad": "TRISTE",
    "insights.yourPatterns": "Vos habitudes de journal",
    "insights.noEntries": "Aucune entrée",
    "insights.createFirst": "Créez votre première entrée",
    "insights.totalEntries": "Total des entrées",
    "insights.bestStreak": "Meilleure série",
    "insights.days": "jours",
    "insights.mostFelt": "Plus ressenti",
    "insights.avgLength": "Durée moy.",
    "insights.min": "min",
    "insights.thisWeek": "Cette semaine",
    "insights.languagesUsed": "Langues utilisées",
    "insights.detailedInsights": "Aperçus détaillés",
    "export.exportYourEntries": "Exporter vos entrées",
    "export.exportDescription": "Téléchargez toutes vos entrées pour une sauvegarde ou un partage.",
    "export.soulBookDesc": "Couverture, polices et mise en page personnalisables",
    "export.markdownDesc": "Sauvegarde texte de toutes les entrées",
    "export.quickPDFDesc": "Export simple sans personnalisation",
    "export.exportInfo": "Votre fichier exporté comprendra toutes les entrées avec dates, humeurs et contenu.",
    "export.noEntries": "Aucune entrée à exporter",
    "export.createFirst": "Créez d'abord des entrées !",
    "export.successMarkdown": "Export réussi ! 📝",
    "export.entriesExported": "entrées exportées en Markdown.",
    "export.successPDF": "PDF prêt ! 📄",
    "export.pdfDescription": "entrées préparées. Utilisez la boîte d'impression pour sauvegarder en PDF.",
    "export.failed": "Échec de l'export",
    "export.failedDesc": "Une erreur est survenue. Veuillez réessayer.",
    "export.journalExport": "Export du journal",
    "export.journalExportDesc": "Exportez votre journal en PDF ou Markdown. Passez en Premium pour débloquer.",
    "onboarding.welcome": "Bienvenue sur",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "Votre espace privé de réflexion. Parlez, l'IA affine vos pensées et découvrez des aperçus.",
    "onboarding.feature1": "Enregistrez des entrées vocales facilement",
    "onboarding.feature2": "Réflexions et coaching propulsés par l'IA",
    "onboarding.feature3": "Exportez votre parcours en livre",
    "onboarding.yourGoals": "Vos objectifs",
    "onboarding.goalsDesc": "Vers quoi travaillez-vous ? Choisissez quelques-uns.",
    "onboarding.worldview": "Vision du monde",
    "onboarding.worldviewDesc": "Personnalise vos réflexions Soul Mirror.",
    "onboarding.yourStrengths": "Vos forces",
    "onboarding.strengthsDesc": "Qu'apportez-vous ?",
    "onboarding.yourFears": "Vos peurs",
    "onboarding.fearsDesc": "L'honnêteté approfondit vos réflexions.",
    "onboarding.cloneVoice": "Clonez votre voix",
    "onboarding.cloneVoiceDesc": "Enregistrez 30 secondes et votre Soul Mirror vous lira avec votre propre voix.",
    "onboarding.setupVoiceClone": "Configurer le clone vocal",
    "onboarding.doLater": "Vous pouvez toujours le faire plus tard dans les paramètres.",
    "onboarding.allSet": "Vous êtes prêt !",
    "onboarding.allSetDesc": "Commencez par enregistrer votre première entrée. Parlez librement — l'IA s'occupe du reste.",
    "onboarding.startJournaling": "Commencer le journal",
    "onboarding.saving": "Sauvegarde...",
    "onboarding.skipForNow": "Passer pour l'instant",
    "onboarding.getStarted": "Commencer",
    "onboarding.continue": "Continuer",
    "onboarding.back": "Retour",
    "onboarding.welcomeToast": "Bienvenue ! 🎉",
    "onboarding.profileReady": "Votre profil est prêt.",
  },
  es: {
    "nav.home": "Inicio",
    "nav.calendar": "Calendario",
    "nav.add": "Añadir",
    "nav.library": "Biblioteca",
    "nav.profile": "Perfil",
    "home.morning": "Buenos días",
    "home.afternoon": "Buenas tardes",
    "home.evening": "Buenas noches",
    "home.quickCapture": "Captura rápida",
    "home.recentEntries": "Entradas recientes",
    "home.viewAll": "Ver todo",
    "home.noEntries": "Sin entradas aún",
    "home.createFirst": "Crea tu primera entrada",
    "record.title": "Nueva entrada",
    "record.tapToRecord": "Toca para grabar tus pensamientos",
    "record.write": "Escribir",
    "record.howFeeling": "¿Cómo te sientes?",
    "record.selectMood": "Selecciona tu estado de ánimo",
    "record.enhance": "Mejorar",
    "record.save": "Guardar",
    "record.saving": "Guardando...",
    "record.recording": "Grabando...",
    "record.processing": "Procesando...",
    "record.limitReached": "Límite alcanzado",
    "record.textLimit": "Entradas de texto",
    "record.audioLimit": "Entradas de audio",
    "record.today": "hoy",
    "record.thisWeek": "esta semana",
    "record.upgradePremium": "Actualizar a Premium",
    "record.newEntry": "NUEVA ENTRADA",
    "record.howAreYou": "¿Cómo estás, ",
    "record.tapToRecordAssessment": "Toca para grabar",
    "record.recordingTime": "Grabando {time}... Toca para detener",
    "record.audioLimitReached": "Límite de audio alcanzado",
    "record.writeLimit": "Escribir",
    "record.mood": "Ánimo",
    "record.aiCoachReflection": "REFLEXIÓN DEL COACH IA",
    "record.recentEntries": "ENTRADAS RECIENTES",
    "record.viewAll": "Ver todo",
    "record.whatsOnMind": "¿Qué tienes en mente hoy?",
    "record.continue": "Continuar",
    "record.originalTranscription": "Transcripción original",
    "record.enhanceWithAI": "Mejorar con IA",
    "record.enhancing": "Mejorando...",
    "record.aiEnhanced": "Mejorado por IA",
    "record.addTitle": "Añadir un título (opcional)",
    "record.voicePlaybackLanguage": "Idioma de reproducción de voz",
    "record.chooseLanguage": "Elige en qué idioma escuchar tu historia",
    "record.generatingVoice": "Generando voz...",
    "record.previewVoice": "Vista previa de voz (Opcional)",
    "record.pause": "Pausa",
    "record.playPreview": "Reproducir vista previa",
    "record.saveEntry": "Guardar entrada",
    "record.entrySaved": "¡Entrada guardada!",
    "record.entrySavedDesc": "Tu entrada de diario ha sido guardada.",
    "record.textEntriesCount": "Entradas de texto: {count}/2 hoy",
    "record.audioEntriesCount": "Entradas de audio: {count}/1 esta semana",
    "record.upgradeUnlimited": "Actualizar a ilimitado",
    "settings.title": "Configuración",
    "settings.account": "Cuenta",
    "settings.profile": "Perfil",
    "settings.security": "Seguridad y PIN",
    "settings.appearance": "Apariencia",
    "settings.themes": "Temas",
    "settings.fonts": "Fuentes",
    "settings.darkMode": "Modo oscuro",
    "settings.features": "Funciones",
    "settings.voice": "Configuración de voz",
    "settings.goals": "Objetivos e intereses",
    "settings.reminders": "Recordatorios",
    "settings.export": "Exportar diario",
    "settings.coaching": "Coach IA",
    "settings.signOut": "Cerrar sesión",
    "settings.admin": "Panel de administración",
    "settings.manageSubscription": "Gestionar suscripción",
    "coaching.title": "Coach IA",
    "coaching.subtitle": "Tu coach personal",
    "coaching.analyze": "Analizar mi semana",
    "coaching.analyzing": "Analizando...",
    "coaching.usageCounter": "llamadas de coaching usadas este mes",
    "coaching.limitReached": "Límite mensual de coaching alcanzado",
    "calendar.title": "Calendario del diario",
    "calendar.noEntries": "Sin entradas para esta fecha",
    "insights.title": "Perspectivas",
    "insights.moodTrend": "Tendencia de ánimo",
    "insights.weeklyActivity": "Actividad semanal",
    "export.title": "Exportar diario",
    "export.download": "Descarga todas tus entradas",
    "export.soulBook": "Constructor de libro del alma (PDF)",
    "export.quickMarkdown": "JSON / Markdown rápido",
    "export.quickPDF": "PDF rápido",
    "common.back": "Volver",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.loading": "Cargando...",
    "common.error": "Algo salió mal",
    "common.success": "Éxito",
    "common.upgrade": "Actualizar",
    "common.premium": "Premium",
    "common.language": "Idioma",
    "pricing.title": "Elige tu plan",
    "pricing.free": "Gratis",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mes",
    "pricing.subtitle": "Desbloquea la experiencia completa de Echo Diary",
    "pricing.forever": "/siempre",
    "pricing.perYear": "/año",
    "pricing.premiumActive": "Premium activo",
    "pricing.granted": "Otorgado",
    "pricing.yearly": "Anual",
    "pricing.monthly": "Mensual",
    "pricing.renewsOn": "Se renueva",
    "pricing.manageSubscription": "Gestionar suscripción",
    "pricing.currentPlan": "Plan actual",
    "pricing.yourPlan": "Tu plan",
    "pricing.premiumMonthly": "Premium mensual",
    "pricing.premiumYearly": "Premium anual",
    "pricing.save30": "AHORRA 30%",
    "pricing.justPerMonth": "Solo",
    "pricing.savePerYear": "ahorra",
    "pricing.subscribeMonthly": "Suscribirse mensualmente",
    "pricing.subscribeYearly": "Suscribirse anualmente — Mejor precio",
    "pricing.refreshStatus": "Actualizar estado de suscripción",
    "pricing.loading": "Cargando...",
    "calendar.visualHistory": "HISTORIAL VISUAL",
    "calendar.thisMonth": "Este mes",
    "calendar.entries": "entradas",
    "calendar.entry": "Entrada",
    "calendar.allEntries": "Todas las entradas",
    "calendar.viewEntry": "Ver entrada",
    "calendar.noEntriesDay": "Sin entradas para este día",
    "calendar.createEntry": "Crear entrada",
    "calendar.happy": "FELIZ",
    "calendar.fine": "BIEN",
    "calendar.sad": "TRISTE",
    "insights.yourPatterns": "Tus patrones de diario",
    "insights.noEntries": "Sin entradas aún",
    "insights.createFirst": "Crea tu primera entrada",
    "insights.totalEntries": "Total de entradas",
    "insights.bestStreak": "Mejor racha",
    "insights.days": "días",
    "insights.mostFelt": "Más sentido",
    "insights.avgLength": "Duración prom.",
    "insights.min": "min",
    "insights.thisWeek": "Esta semana",
    "insights.languagesUsed": "Idiomas usados",
    "insights.detailedInsights": "Perspectivas detalladas",
    "export.exportYourEntries": "Exportar tus entradas",
    "export.exportDescription": "Descarga todas tus entradas como archivo de respaldo o para compartir.",
    "export.soulBookDesc": "Portada, fuentes y diseño personalizables",
    "export.markdownDesc": "Respaldo en texto plano de todas las entradas",
    "export.quickPDFDesc": "Exportación simple sin personalización",
    "export.exportInfo": "Tu archivo exportado incluirá todas las entradas con fechas, ánimos y contenido.",
    "export.noEntries": "Sin entradas para exportar",
    "export.createFirst": "¡Crea algunas entradas primero!",
    "export.successMarkdown": "¡Exportación exitosa! 📝",
    "export.entriesExported": "entradas exportadas a Markdown.",
    "export.successPDF": "¡PDF listo! 📄",
    "export.pdfDescription": "entradas preparadas. Usa el diálogo de impresión para guardar como PDF.",
    "export.failed": "Exportación fallida",
    "export.failedDesc": "Algo salió mal. Inténtalo de nuevo.",
    "export.journalExport": "Exportar diario",
    "export.journalExportDesc": "Exporta tu diario como PDF o Markdown. Actualiza a Premium para desbloquear.",
    "onboarding.welcome": "Bienvenido a",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "Tu espacio privado de reflexión. Habla, la IA refina tus pensamientos y descubre perspectivas.",
    "onboarding.feature1": "Graba entradas de voz fácilmente",
    "onboarding.feature2": "Reflexiones y coaching con IA",
    "onboarding.feature3": "Exporta tu viaje como libro",
    "onboarding.yourGoals": "Tus objetivos",
    "onboarding.goalsDesc": "¿Hacia qué trabajas? Elige algunos.",
    "onboarding.worldview": "Visión del mundo",
    "onboarding.worldviewDesc": "Personaliza tus reflexiones del Soul Mirror.",
    "onboarding.yourStrengths": "Tus fortalezas",
    "onboarding.strengthsDesc": "¿Qué aportas?",
    "onboarding.yourFears": "Tus miedos",
    "onboarding.fearsDesc": "La honestidad profundiza tus reflexiones.",
    "onboarding.cloneVoice": "Clona tu voz",
    "onboarding.cloneVoiceDesc": "Graba 30 segundos y tu Soul Mirror te leerá con tu propia voz.",
    "onboarding.setupVoiceClone": "Configurar clon de voz",
    "onboarding.doLater": "Puedes hacerlo después en Configuración.",
    "onboarding.allSet": "¡Todo listo!",
    "onboarding.allSetDesc": "Comienza grabando tu primera entrada. Habla libremente — la IA se encarga del resto.",
    "onboarding.startJournaling": "Empezar a escribir",
    "onboarding.saving": "Guardando...",
    "onboarding.skipForNow": "Saltar por ahora",
    "onboarding.getStarted": "Empezar",
    "onboarding.continue": "Continuar",
    "onboarding.back": "Atrás",
    "onboarding.welcomeToast": "¡Bienvenido! 🎉",
    "onboarding.profileReady": "Tu perfil está listo.",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.calendar": "التقويم",
    "nav.add": "إضافة",
    "nav.library": "المكتبة",
    "nav.profile": "الملف الشخصي",
    "home.morning": "صباح الخير",
    "home.afternoon": "مساء الخير",
    "home.evening": "مساء الخير",
    "home.quickCapture": "التقاط سريع",
    "home.recentEntries": "الإدخالات الأخيرة",
    "home.viewAll": "عرض الكل",
    "home.noEntries": "لا توجد إدخالات بعد",
    "home.createFirst": "أنشئ إدخالك الأول",
    "record.title": "إدخال جديد",
    "record.tapToRecord": "اضغط لتسجيل أفكارك",
    "record.write": "كتابة",
    "record.howFeeling": "كيف تشعر؟",
    "record.selectMood": "اختر مزاجك",
    "record.enhance": "تحسين",
    "record.save": "حفظ",
    "record.saving": "جارٍ الحفظ...",
    "record.recording": "جارٍ التسجيل...",
    "record.processing": "جارٍ المعالجة...",
    "record.limitReached": "تم الوصول للحد",
    "record.textLimit": "إدخالات نصية",
    "record.audioLimit": "إدخالات صوتية",
    "record.today": "اليوم",
    "record.thisWeek": "هذا الأسبوع",
    "record.upgradePremium": "ترقية إلى Premium",
    "record.newEntry": "إدخال جديد",
    "record.howAreYou": "كيف حالك، ",
    "record.tapToRecordAssessment": "اضغط للتسجيل",
    "record.recordingTime": "تسجيل {time}... اضغط للإيقاف",
    "record.audioLimitReached": "تم الوصول لحد الصوت",
    "record.writeLimit": "كتابة",
    "record.mood": "المزاج",
    "record.aiCoachReflection": "تأمل مدرب الذكاء الاصطناعي",
    "record.recentEntries": "الإدخالات الأخيرة",
    "record.viewAll": "عرض الكل",
    "record.whatsOnMind": "ما الذي يشغل بالك اليوم؟",
    "record.continue": "متابعة",
    "record.originalTranscription": "النص الأصلي",
    "record.enhanceWithAI": "تحسين بالذكاء الاصطناعي",
    "record.enhancing": "جارٍ التحسين...",
    "record.aiEnhanced": "محسّن بالذكاء الاصطناعي",
    "record.addTitle": "أضف عنوانًا (اختياري)",
    "record.voicePlaybackLanguage": "لغة تشغيل الصوت",
    "record.chooseLanguage": "اختر اللغة لسماع قصتك",
    "record.generatingVoice": "جارٍ إنشاء الصوت...",
    "record.previewVoice": "معاينة الصوت (اختياري)",
    "record.pause": "إيقاف مؤقت",
    "record.playPreview": "تشغيل المعاينة",
    "record.saveEntry": "حفظ الإدخال",
    "record.entrySaved": "تم حفظ الإدخال!",
    "record.entrySavedDesc": "تم حفظ إدخال يومياتك.",
    "record.textEntriesCount": "إدخالات نصية: {count}/2 اليوم",
    "record.audioEntriesCount": "إدخالات صوتية: {count}/1 هذا الأسبوع",
    "record.upgradeUnlimited": "ترقية للامحدود",
    "settings.title": "الإعدادات",
    "settings.account": "الحساب",
    "settings.profile": "الملف الشخصي",
    "settings.security": "الأمان و PIN",
    "settings.appearance": "المظهر",
    "settings.themes": "السمات",
    "settings.fonts": "الخطوط",
    "settings.darkMode": "الوضع الداكن",
    "settings.features": "الميزات",
    "settings.voice": "إعدادات الصوت",
    "settings.goals": "الأهداف والاهتمامات",
    "settings.reminders": "التذكيرات",
    "settings.export": "تصدير اليوميات",
    "settings.coaching": "مدرب الذكاء الاصطناعي",
    "settings.signOut": "تسجيل الخروج",
    "settings.admin": "لوحة الإدارة",
    "settings.manageSubscription": "إدارة الاشتراك",
    "coaching.title": "مدرب الذكاء الاصطناعي",
    "coaching.subtitle": "مدربك الشخصي",
    "coaching.analyze": "تحليل أسبوعي",
    "coaching.analyzing": "جارٍ التحليل...",
    "coaching.usageCounter": "مكالمات تدريب مستخدمة هذا الشهر",
    "coaching.limitReached": "تم الوصول لحد التدريب الشهري",
    "calendar.title": "تقويم اليوميات",
    "calendar.noEntries": "لا توجد إدخالات لهذا التاريخ",
    "insights.title": "رؤى",
    "insights.moodTrend": "اتجاه المزاج",
    "insights.weeklyActivity": "النشاط الأسبوعي",
    "export.title": "تصدير اليوميات",
    "export.download": "تنزيل جميع إدخالاتك",
    "export.soulBook": "منشئ كتاب الروح (PDF)",
    "export.quickMarkdown": "JSON / Markdown سريع",
    "export.quickPDF": "PDF سريع",
    "common.back": "رجوع",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.loading": "جارٍ التحميل...",
    "common.error": "حدث خطأ ما",
    "common.success": "نجاح",
    "common.upgrade": "ترقية",
    "common.premium": "Premium",
    "common.language": "اللغة",
    "pricing.title": "اختر خطتك",
    "pricing.free": "مجاني",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/شهر",
  },
  zh: {
    "nav.home": "首页",
    "nav.calendar": "日历",
    "nav.add": "添加",
    "nav.library": "图书馆",
    "nav.profile": "个人资料",
    "home.morning": "早上好",
    "home.afternoon": "下午好",
    "home.evening": "晚上好",
    "home.quickCapture": "快速记录",
    "home.recentEntries": "最近的条目",
    "home.viewAll": "查看全部",
    "home.noEntries": "还没有条目",
    "home.createFirst": "创建您的第一个条目",
    "record.title": "新条目",
    "record.tapToRecord": "点击录制您的想法",
    "record.write": "写作",
    "record.howFeeling": "您感觉如何？",
    "record.selectMood": "选择您的心情",
    "record.enhance": "优化",
    "record.save": "保存",
    "record.saving": "保存中...",
    "record.recording": "录制中...",
    "record.processing": "处理中...",
    "record.limitReached": "已达上限",
    "record.textLimit": "文字条目",
    "record.audioLimit": "音频条目",
    "record.today": "今天",
    "record.thisWeek": "本周",
    "record.upgradePremium": "升级至 Premium",
    "record.newEntry": "新条目",
    "record.howAreYou": "你好吗，",
    "record.tapToRecordAssessment": "点击录制",
    "record.recordingTime": "录制中 {time}... 点击停止",
    "record.audioLimitReached": "音频上限已达",
    "record.writeLimit": "写作",
    "record.mood": "心情",
    "record.aiCoachReflection": "AI 教练反思",
    "record.recentEntries": "最近条目",
    "record.viewAll": "查看全部",
    "record.whatsOnMind": "今天在想什么？",
    "record.continue": "继续",
    "record.originalTranscription": "原始转录",
    "record.enhanceWithAI": "AI 优化",
    "record.enhancing": "优化中...",
    "record.aiEnhanced": "AI 已优化",
    "record.addTitle": "添加标题（可选）",
    "record.voicePlaybackLanguage": "语音播放语言",
    "record.chooseLanguage": "选择收听故事的语言",
    "record.generatingVoice": "生成语音中...",
    "record.previewVoice": "预览语音（可选）",
    "record.pause": "暂停",
    "record.playPreview": "播放预览",
    "record.saveEntry": "保存条目",
    "record.entrySaved": "条目已保存！",
    "record.entrySavedDesc": "您的日记条目已保存。",
    "record.textEntriesCount": "文字条目：{count}/2 今天",
    "record.audioEntriesCount": "音频条目：{count}/1 本周",
    "record.upgradeUnlimited": "升级至无限",
    "settings.title": "设置",
    "settings.account": "账户",
    "settings.profile": "个人资料",
    "settings.security": "安全与 PIN",
    "settings.appearance": "外观",
    "settings.themes": "主题",
    "settings.fonts": "字体",
    "settings.darkMode": "深色模式",
    "settings.features": "功能",
    "settings.voice": "语音设置",
    "settings.goals": "目标与兴趣",
    "settings.reminders": "提醒",
    "settings.export": "导出日记",
    "settings.coaching": "AI 教练",
    "settings.signOut": "退出登录",
    "settings.admin": "管理后台",
    "settings.manageSubscription": "管理订阅",
    "coaching.title": "AI 教练",
    "coaching.subtitle": "您的个人教练",
    "coaching.analyze": "分析我的一周",
    "coaching.analyzing": "分析中...",
    "coaching.usageCounter": "本月已使用教练次数",
    "coaching.limitReached": "已达月度教练上限",
    "calendar.title": "日记日历",
    "calendar.noEntries": "此日期无条目",
    "insights.title": "洞察",
    "insights.moodTrend": "情绪趋势",
    "insights.weeklyActivity": "每周活动",
    "export.title": "导出日记",
    "export.download": "下载所有条目",
    "export.soulBook": "灵魂之书构建器 (PDF)",
    "export.quickMarkdown": "快速 JSON / Markdown",
    "export.quickPDF": "快速 PDF",
    "common.back": "返回",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.loading": "加载中...",
    "common.error": "出了点问题",
    "common.success": "成功",
    "common.upgrade": "升级",
    "common.premium": "Premium",
    "common.language": "语言",
    "pricing.title": "选择您的计划",
    "pricing.free": "免费",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/月",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.calendar": "カレンダー",
    "nav.add": "追加",
    "nav.library": "ライブラリ",
    "nav.profile": "プロフィール",
    "home.morning": "おはようございます",
    "home.afternoon": "こんにちは",
    "home.evening": "こんばんは",
    "home.quickCapture": "クイック記録",
    "home.recentEntries": "最近のエントリー",
    "home.viewAll": "すべて表示",
    "home.noEntries": "エントリーがありません",
    "home.createFirst": "最初のエントリーを作成",
    "record.title": "新しいエントリー",
    "record.tapToRecord": "タップして思考を記録",
    "record.write": "書く",
    "record.howFeeling": "気分はどうですか？",
    "record.selectMood": "気分を選択",
    "record.enhance": "改善",
    "record.save": "保存",
    "record.saving": "保存中...",
    "record.recording": "録音中...",
    "record.processing": "処理中...",
    "record.limitReached": "上限に達しました",
    "record.textLimit": "テキストエントリー",
    "record.audioLimit": "音声エントリー",
    "record.today": "今日",
    "record.thisWeek": "今週",
    "record.upgradePremium": "Premiumにアップグレード",
    "record.newEntry": "新しいエントリー",
    "record.howAreYou": "お元気ですか、",
    "record.tapToRecordAssessment": "タップして録音",
    "record.recordingTime": "録音中 {time}... タップで停止",
    "record.audioLimitReached": "音声上限に達しました",
    "record.writeLimit": "書く",
    "record.mood": "気分",
    "record.aiCoachReflection": "AIコーチの振り返り",
    "record.recentEntries": "最近のエントリー",
    "record.viewAll": "すべて表示",
    "record.whatsOnMind": "今日は何を考えていますか？",
    "record.continue": "続ける",
    "record.originalTranscription": "元の文字起こし",
    "record.enhanceWithAI": "AIで改善",
    "record.enhancing": "改善中...",
    "record.aiEnhanced": "AI改善済み",
    "record.addTitle": "タイトルを追加（任意）",
    "record.voicePlaybackLanguage": "音声再生言語",
    "record.chooseLanguage": "ストーリーを聞く言語を選択",
    "record.generatingVoice": "音声生成中...",
    "record.previewVoice": "音声プレビュー（任意）",
    "record.pause": "一時停止",
    "record.playPreview": "プレビュー再生",
    "record.saveEntry": "エントリーを保存",
    "record.entrySaved": "エントリーが保存されました！",
    "record.entrySavedDesc": "日記エントリーが保存されました。",
    "record.textEntriesCount": "テキスト：{count}/2 今日",
    "record.audioEntriesCount": "音声：{count}/1 今週",
    "record.upgradeUnlimited": "無制限にアップグレード",
    "settings.title": "設定",
    "settings.account": "アカウント",
    "settings.profile": "プロフィール",
    "settings.security": "セキュリティ & PIN",
    "settings.appearance": "外観",
    "settings.themes": "テーマ",
    "settings.fonts": "フォント",
    "settings.darkMode": "ダークモード",
    "settings.features": "機能",
    "settings.voice": "音声設定",
    "settings.goals": "目標と興味",
    "settings.reminders": "リマインダー",
    "settings.export": "日記をエクスポート",
    "settings.coaching": "AIコーチ",
    "settings.signOut": "サインアウト",
    "settings.admin": "管理ダッシュボード",
    "settings.manageSubscription": "サブスクリプション管理",
    "coaching.title": "AIコーチ",
    "coaching.subtitle": "あなたの個人コーチ",
    "coaching.analyze": "今週を分析",
    "coaching.analyzing": "分析中...",
    "coaching.usageCounter": "今月のコーチング利用回数",
    "coaching.limitReached": "月間コーチング上限に達しました",
    "calendar.title": "日記カレンダー",
    "calendar.noEntries": "この日付のエントリーはありません",
    "insights.title": "インサイト",
    "insights.moodTrend": "気分の傾向",
    "insights.weeklyActivity": "週間アクティビティ",
    "export.title": "日記をエクスポート",
    "export.download": "すべてのエントリーをダウンロード",
    "export.soulBook": "ソウルブックビルダー (PDF)",
    "export.quickMarkdown": "クイック JSON / Markdown",
    "export.quickPDF": "クイック PDF",
    "common.back": "戻る",
    "common.cancel": "キャンセル",
    "common.save": "保存",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.loading": "読み込み中...",
    "common.error": "エラーが発生しました",
    "common.success": "成功",
    "common.upgrade": "アップグレード",
    "common.premium": "Premium",
    "common.language": "言語",
    "pricing.title": "プランを選択",
    "pricing.free": "無料",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/月",
  },
  sw: {
    "nav.home": "Nyumbani",
    "nav.calendar": "Kalenda",
    "nav.add": "Ongeza",
    "nav.library": "Maktaba",
    "nav.profile": "Wasifu",
    "home.morning": "Habari za asubuhi",
    "home.afternoon": "Habari za mchana",
    "home.evening": "Habari za jioni",
    "home.quickCapture": "Chukua haraka",
    "home.recentEntries": "Maingizo ya hivi karibuni",
    "home.viewAll": "Tazama yote",
    "home.noEntries": "Hakuna maingizo bado",
    "home.createFirst": "Unda ingizo lako la kwanza",
    "record.title": "Ingizo jipya",
    "record.tapToRecord": "Gusa ili kurekodi mawazo yako",
    "record.write": "Andika",
    "record.howFeeling": "Unajisikiaje?",
    "record.selectMood": "Chagua hali yako",
    "record.enhance": "Boresha",
    "record.save": "Hifadhi",
    "record.saving": "Inahifadhi...",
    "record.recording": "Inarekodi...",
    "record.processing": "Inachakata...",
    "record.limitReached": "Kikomo kimefikiwa",
    "record.textLimit": "Maingizo ya maandishi",
    "record.audioLimit": "Maingizo ya sauti",
    "record.today": "leo",
    "record.thisWeek": "wiki hii",
    "record.upgradePremium": "Panda hadi Premium",
    "record.newEntry": "INGIZO JIPYA",
    "record.howAreYou": "Habari yako, ",
    "record.tapToRecordAssessment": "Gusa ili kurekodi",
    "record.recordingTime": "Inarekodi {time}... Gusa kusimamisha",
    "record.audioLimitReached": "Kikomo cha sauti kimefikiwa",
    "record.writeLimit": "Andika",
    "record.mood": "Hali",
    "record.aiCoachReflection": "TAFAKURI YA KOCHA WA AI",
    "record.recentEntries": "MAINGIZO YA HIVI KARIBUNI",
    "record.viewAll": "Tazama yote",
    "record.whatsOnMind": "Una nini akilini leo?",
    "record.continue": "Endelea",
    "record.originalTranscription": "Maandishi ya awali",
    "record.enhanceWithAI": "Boresha na AI",
    "record.enhancing": "Inaboresha...",
    "record.aiEnhanced": "Imeboreshwa na AI",
    "record.addTitle": "Ongeza kichwa (hiari)",
    "record.voicePlaybackLanguage": "Lugha ya kucheza sauti",
    "record.chooseLanguage": "Chagua lugha ya kusikiliza hadithi yako",
    "record.generatingVoice": "Inaunda sauti...",
    "record.previewVoice": "Hakiki sauti (Hiari)",
    "record.pause": "Simamisha",
    "record.playPreview": "Cheza hakiki",
    "record.saveEntry": "Hifadhi ingizo",
    "record.entrySaved": "Ingizo limehifadhiwa!",
    "record.entrySavedDesc": "Ingizo lako la jarida limehifadhiwa.",
    "record.textEntriesCount": "Maingizo ya maandishi: {count}/2 leo",
    "record.audioEntriesCount": "Maingizo ya sauti: {count}/1 wiki hii",
    "record.upgradeUnlimited": "Panda kwa bila kikomo",
    "settings.title": "Mipangilio",
    "settings.account": "Akaunti",
    "settings.profile": "Wasifu",
    "settings.security": "Usalama & PIN",
    "settings.appearance": "Muonekano",
    "settings.themes": "Mandhari",
    "settings.fonts": "Fonti",
    "settings.darkMode": "Hali ya giza",
    "settings.features": "Vipengele",
    "settings.voice": "Mipangilio ya sauti",
    "settings.goals": "Malengo na Maslahi",
    "settings.reminders": "Vikumbusho",
    "settings.export": "Hamisha jarida",
    "settings.coaching": "Kocha wa AI",
    "settings.signOut": "Ondoka",
    "settings.admin": "Dashibodi ya msimamizi",
    "settings.manageSubscription": "Dhibiti usajili",
    "coaching.title": "Kocha wa AI",
    "coaching.subtitle": "Kocha wako binafsi",
    "coaching.analyze": "Changanua wiki yangu",
    "coaching.analyzing": "Inachambua...",
    "coaching.usageCounter": "simu za kocha zilizotumika mwezi huu",
    "coaching.limitReached": "Kikomo cha kocha cha mwezi kimefikiwa",
    "calendar.title": "Kalenda ya jarida",
    "calendar.noEntries": "Hakuna maingizo kwa tarehe hii",
    "insights.title": "Maarifa",
    "insights.moodTrend": "Mwenendo wa hali",
    "insights.weeklyActivity": "Shughuli za wiki",
    "export.title": "Hamisha jarida",
    "export.download": "Pakua maingizo yako yote",
    "export.soulBook": "Mjenzi wa Kitabu cha Roho (PDF)",
    "export.quickMarkdown": "JSON / Markdown haraka",
    "export.quickPDF": "PDF haraka",
    "common.back": "Rudi",
    "common.cancel": "Ghairi",
    "common.save": "Hifadhi",
    "common.delete": "Futa",
    "common.edit": "Hariri",
    "common.loading": "Inapakia...",
    "common.error": "Kuna kosa limetokea",
    "common.success": "Imefanikiwa",
    "common.upgrade": "Panda daraja",
    "common.premium": "Premium",
    "common.language": "Lugha",
    "pricing.title": "Chagua mpango wako",
    "pricing.free": "Bure",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mwezi",
  },
  de: {
    "nav.home": "Startseite",
    "nav.calendar": "Kalender",
    "nav.add": "Hinzufügen",
    "nav.library": "Bibliothek",
    "nav.profile": "Profil",
    "home.morning": "Guten Morgen",
    "home.afternoon": "Guten Tag",
    "home.evening": "Guten Abend",
    "home.quickCapture": "Schnellaufnahme",
    "home.recentEntries": "Letzte Einträge",
    "home.viewAll": "Alle anzeigen",
    "home.noEntries": "Noch keine Einträge",
    "home.createFirst": "Erstelle deinen ersten Eintrag",
    "record.title": "Neuer Eintrag",
    "record.tapToRecord": "Tippe, um deine Gedanken aufzunehmen",
    "record.write": "Schreiben",
    "record.howFeeling": "Wie fühlst du dich?",
    "record.selectMood": "Wähle deine Stimmung",
    "record.enhance": "Verbessern",
    "record.save": "Speichern",
    "record.saving": "Speichern...",
    "record.recording": "Aufnahme...",
    "record.processing": "Verarbeitung...",
    "record.limitReached": "Limit erreicht",
    "record.textLimit": "Texteinträge",
    "record.audioLimit": "Audioeinträge",
    "record.today": "heute",
    "record.thisWeek": "diese Woche",
    "record.upgradePremium": "Auf Premium upgraden",
    "record.newEntry": "NEUER EINTRAG",
    "record.howAreYou": "Wie geht es dir, ",
    "record.tapToRecordAssessment": "Tippe zum Aufnehmen",
    "record.recordingTime": "Aufnahme {time}... Tippe zum Stoppen",
    "record.audioLimitReached": "Audio-Limit erreicht",
    "record.writeLimit": "Schreiben",
    "record.mood": "Stimmung",
    "record.aiCoachReflection": "KI-COACH REFLEXION",
    "record.recentEntries": "LETZTE EINTRÄGE",
    "record.viewAll": "Alle anzeigen",
    "record.whatsOnMind": "Was beschäftigt dich heute?",
    "record.continue": "Weiter",
    "record.originalTranscription": "Originaltranskription",
    "record.enhanceWithAI": "Mit KI verbessern",
    "record.enhancing": "Verbessern...",
    "record.aiEnhanced": "KI-verbessert",
    "record.addTitle": "Titel hinzufügen (optional)",
    "record.voicePlaybackLanguage": "Sprachwiedergabe",
    "record.chooseLanguage": "Wähle die Sprache für deine Geschichte",
    "record.generatingVoice": "Stimme wird erzeugt...",
    "record.previewVoice": "Stimmvorschau (Optional)",
    "record.pause": "Pause",
    "record.playPreview": "Vorschau abspielen",
    "record.saveEntry": "Eintrag speichern",
    "record.entrySaved": "Eintrag gespeichert!",
    "record.entrySavedDesc": "Dein Tagebucheintrag wurde gespeichert.",
    "record.textEntriesCount": "Texteinträge: {count}/2 heute",
    "record.audioEntriesCount": "Audioeinträge: {count}/1 diese Woche",
    "record.upgradeUnlimited": "Auf unbegrenzt upgraden",
    "settings.title": "Einstellungen",
    "settings.account": "Konto",
    "settings.profile": "Profil",
    "settings.security": "Sicherheit & PIN",
    "settings.appearance": "Erscheinungsbild",
    "settings.themes": "Themen",
    "settings.fonts": "Schriftarten",
    "settings.darkMode": "Dunkelmodus",
    "settings.features": "Funktionen",
    "settings.voice": "Spracheinstellungen",
    "settings.goals": "Ziele & Interessen",
    "settings.reminders": "Erinnerungen",
    "settings.export": "Tagebuch exportieren",
    "settings.coaching": "KI-Coach",
    "settings.signOut": "Abmelden",
    "settings.admin": "Admin-Dashboard",
    "settings.manageSubscription": "Abo verwalten",
    "coaching.title": "KI-Coach",
    "coaching.subtitle": "Dein persönlicher Coach",
    "coaching.analyze": "Meine Woche analysieren",
    "coaching.analyzing": "Analyse läuft...",
    "coaching.usageCounter": "Coaching-Anrufe diesen Monat genutzt",
    "coaching.limitReached": "Monatliches Coaching-Limit erreicht",
    "calendar.title": "Tagebuch-Kalender",
    "calendar.noEntries": "Keine Einträge für dieses Datum",
    "insights.title": "Einblicke",
    "insights.moodTrend": "Stimmungstrend",
    "insights.weeklyActivity": "Wöchentliche Aktivität",
    "export.title": "Tagebuch exportieren",
    "export.download": "Alle Einträge herunterladen",
    "export.soulBook": "Seelenbuch-Builder (PDF)",
    "export.quickMarkdown": "Schnell JSON / Markdown",
    "export.quickPDF": "Schnell PDF",
    "common.back": "Zurück",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.loading": "Laden...",
    "common.error": "Etwas ist schiefgelaufen",
    "common.success": "Erfolg",
    "common.upgrade": "Upgraden",
    "common.premium": "Premium",
    "common.language": "Sprache",
    "pricing.title": "Wähle deinen Plan",
    "pricing.free": "Kostenlos",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/Monat",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    return (localStorage.getItem("app-language") as AppLanguage) || "en";
  });

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};

// Helper to get full language name for AI prompts
export const getLanguageName = (code: AppLanguage): string => {
  return LANGUAGES.find((l) => l.code === code)?.name || "English";
};
