import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { EXTRA_TRANSLATIONS } from "@/contexts/extraTranslations";
import { UI_TRANSLATIONS } from "@/contexts/uiTranslations";

export type AppLanguage = "en" | "fr" | "es" | "ar" | "zh" | "ja" | "sw" | "de";

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGES: { code: AppLanguage; name: string; flag: string; native: string }[] = [
  { code: "en", name: "English", flag: "🇺🇸", native: "English" },
  { code: "fr", name: "French", flag: "🇫🇷", native: "Français" },
  { code: "es", name: "Spanish", flag: "🇪🇸", native: "Español" },
  { code: "ar", name: "Arabic", flag: "🇸🇦", native: "العربية" },
  { code: "zh", name: "Chinese", flag: "🇨🇳", native: "中文" },
  { code: "ja", name: "Japanese", flag: "🇯🇵", native: "日本語" },
  { code: "sw", name: "Swahili", flag: "🇰🇪", native: "Kiswahili" },
  { code: "de", name: "German", flag: "🇩🇪", native: "Deutsch" },
];

// Translation dictionaries for all supported languages
const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.calendar": "Calendar",
    "nav.add": "Add",
    "nav.library": "Library",
    "nav.profile": "Profile",
    // Home
    "home.morning": "Morning",
    "home.afternoon": "Afternoon",
    "home.evening": "Evening",
    "home.friend": "Friend",
    "home.quickCapture": "Quick Capture",
    "home.recentEntries": "Recent Entries",
    "home.viewAll": "View All",
    "home.noEntries": "No entries yet",
    "home.createFirst": "Create Your First Entry",
    // Record
    "record.title": "New Entry",
    "record.tapToRecord": "Tap to record your thoughts",
    "record.write": "Write",
    "record.howFeeling": "How are you feeling?",
    "record.selectMood": "Select your mood",
    "record.enhance": "Enhance",
    "record.save": "Save Entry",
    "record.saving": "Saving...",
    "record.recording": "Recording...",
    "record.processing": "Processing...",
    "record.limitReached": "Limit Reached",
    "record.textLimit": "Text entries",
    "record.audioLimit": "Audio entries",
    "record.today": "today",
    "record.thisWeek": "this week",
    "record.upgradePremium": "Upgrade to Premium",
    "record.newEntry": "NEW ENTRY",
    "record.howAreYou": "How are you, ",
    "record.tapToRecordAssessment": "Tap to Record Assessment",
    "record.recordingTime": "Recording {time}... Tap to stop",
    "record.audioLimitReached": "Audio limit reached",
    "record.writeLimit": "Write",
    "record.mood": "Mood",
    "record.aiCoachReflection": "AI COACH REFLECTION",
    "record.recentEntries": "RECENT ENTRIES",
    "record.viewAll": "View All",
    "record.whatsOnMind": "What's on your mind today?",
    "record.continue": "Continue",
    "record.originalTranscription": "Original Transcription",
    "record.enhanceWithAI": "Enhance with AI",
    "record.enhancing": "Enhancing...",
    "record.aiEnhanced": "AI Enhanced",
    "record.addTitle": "Add a title (optional)",
    "record.voicePlaybackLanguage": "Voice Playback Language",
    "record.chooseLanguage": "Choose which language to hear your story in",
    "record.generatingVoice": "Generating Voice...",
    "record.previewVoice": "Preview Voice (Optional)",
    "record.pause": "Pause",
    "record.playPreview": "Play Preview",
    "record.saveEntry": "Save Entry",
    "record.entrySaved": "Entry Saved!",
    "record.entrySavedDesc": "Your journal entry has been saved.",
    "record.textEntriesCount": "Text entries: {count}/2 today",
    "record.audioEntriesCount": "Audio entries: {count}/1 this week",
    "record.upgradeUnlimited": "Upgrade for unlimited",
    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.profile": "Profile",
    "settings.security": "Security & PIN",
    "settings.appearance": "Appearance",
    "settings.themes": "Themes",
    "settings.fonts": "Fonts",
    "settings.darkMode": "Dark Mode",
    "settings.features": "Features",
    "settings.voice": "Voice Settings",
    "settings.goals": "Goals & Interests",
    "settings.reminders": "Reminders",
    "settings.export": "Export Journal",
    "settings.coaching": "AI Coaching",
    "settings.signOut": "Sign Out",
    "settings.admin": "Admin Dashboard",
    "settings.manageSubscription": "Manage Subscription",
    // Coaching
    "coaching.title": "AI Coach",
    "coaching.subtitle": "Your personal soul coach",
    "coaching.analyze": "Analyze My Week",
    "coaching.analyzing": "Analyzing...",
    "coaching.usageCounter": "coaching calls used this month",
    "coaching.limitReached": "Monthly coaching limit reached",
    // Calendar
    "calendar.title": "Journal Calendar",
    "calendar.noEntries": "No entries for this date",
    // Insights
    "insights.title": "Insights",
    "insights.moodTrend": "Mood Trend",
    "insights.weeklyActivity": "Weekly Activity",
    // Export
    "export.title": "Export Journal",
    "export.download": "Download all your entries",
    "export.soulBook": "Soul Book Builder (PDF)",
    "export.quickMarkdown": "Quick JSON / Markdown",
    "export.quickPDF": "Quick PDF",
    // Common
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.success": "Success",
    "common.upgrade": "Upgrade",
    "common.premium": "Premium",
    "common.language": "Language",
    "auth.welcomeBack": "Welcome back! Sign in to continue",
    "auth.createAccount": "Create your account",
    "auth.signIn": "Sign In",
    "auth.signUp": "Create Account",
    "auth.yourName": "Your name",
    "auth.email": "Email address",
    "auth.password": "Password",
    "auth.or": "or",
    "auth.continueGoogle": "Continue with Google",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.signUpLink": "Sign up",
    "auth.signInLink": "Sign in",
    // Pricing
    "pricing.title": "Choose Your Plan",
    "pricing.subtitle": "Unlock the full Echo Diary experience",
    "pricing.free": "Free",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/month",
    "pricing.forever": "/forever",
    "pricing.perYear": "/year",
    "pricing.premiumActive": "Premium Active",
    "pricing.granted": "Granted",
    "pricing.yearly": "Yearly",
    "pricing.monthly": "Monthly",
    "pricing.renewsOn": "Renews",
    "pricing.manageSubscription": "Manage Subscription",
    "pricing.currentPlan": "Current Plan",
    "pricing.yourPlan": "Your Plan",
    "pricing.premiumMonthly": "Premium Monthly",
    "pricing.premiumYearly": "Premium Yearly",
    "pricing.save30": "SAVE 30%",
    "pricing.justPerMonth": "Just",
    "pricing.savePerYear": "save",
    "pricing.subscribeMonthly": "Subscribe Monthly",
    "pricing.subscribeYearly": "Subscribe Yearly — Best Value",
    "pricing.refreshStatus": "Refresh subscription status",
    "pricing.loading": "Loading...",
    // Calendar
    "calendar.visualHistory": "VISUAL HISTORY",
    "calendar.thisMonth": "This month",
    "calendar.entries": "entries",
    "calendar.entry": "Entry",
    "calendar.allEntries": "All entries",
    "calendar.viewEntry": "View Entry",
    "calendar.noEntriesDay": "No entries for this day",
    "calendar.createEntry": "Create Entry",
    "calendar.happy": "HAPPY",
    "calendar.fine": "FINE",
    "calendar.sad": "SAD",
    // Insights
    "insights.yourPatterns": "Your journaling patterns",
    "insights.noEntries": "No entries yet",
    "insights.createFirst": "Create Your First Entry",
    "insights.totalEntries": "Total Entries",
    "insights.bestStreak": "Best Streak",
    "insights.days": "days",
    "insights.mostFelt": "Most Felt",
    "insights.avgLength": "Avg. Length",
    "insights.min": "min",
    "insights.thisWeek": "This Week",
    "insights.languagesUsed": "Languages Used",
    "insights.detailedInsights": "Detailed Insights",
    // Export
    "export.exportYourEntries": "Export Your Entries",
    "export.exportDescription": "Download all your journal entries as a file to keep a backup or share with others.",
    "export.soulBookDesc": "Customizable cover, fonts & layout for printing",
    "export.markdownDesc": "Plain text backup of all entries",
    "export.quickPDFDesc": "Simple formatted export, no customization",
    "export.exportInfo": "Your exported file will include all journal entries with their dates, moods, and content.",
    "export.noEntries": "No entries to export",
    "export.createFirst": "Create some journal entries first!",
    "export.successMarkdown": "Export successful! 📝",
    "export.entriesExported": "entries exported to Markdown.",
    "export.successPDF": "PDF ready! 📄",
    "export.pdfDescription": "entries prepared. Use print dialog to save as PDF.",
    "export.failed": "Export failed",
    "export.failedDesc": "Something went wrong. Please try again.",
    "export.journalExport": "Journal Export",
    "export.journalExportDesc": "Export your journal as PDF or Markdown and build beautiful soul books. Upgrade to Premium to unlock.",
    // Onboarding
    "onboarding.welcome": "Welcome to",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "Your private space for self-reflection. Speak your thoughts, let AI refine them, and discover insights from your Soul Mirror.",
    "onboarding.feature1": "Record voice entries effortlessly",
    "onboarding.feature2": "AI-powered reflections & coaching",
    "onboarding.feature3": "Export your journey as a book",
    "onboarding.yourGoals": "Your Goals",
    "onboarding.goalsDesc": "What are you working toward? Pick a few.",
    "onboarding.worldview": "Worldview",
    "onboarding.worldviewDesc": "Helps personalize your Soul Mirror reflections.",
    "onboarding.yourStrengths": "Your Strengths",
    "onboarding.strengthsDesc": "What do you bring to the table?",
    "onboarding.yourFears": "Your Fears",
    "onboarding.fearsDesc": "Being honest helps your reflections go deeper.",
    "onboarding.cloneVoice": "Clone Your Voice",
    "onboarding.cloneVoiceDesc": "Record 30 seconds of speech and your Soul Mirror will read reflections back in your own voice.",
    "onboarding.setupVoiceClone": "Set Up Voice Clone",
    "onboarding.doLater": "You can always do this later in Settings.",
    "onboarding.allSet": "You're All Set!",
    "onboarding.allSetDesc": "Start by recording your first journal entry. Speak freely — AI will handle the rest.",
    "onboarding.startJournaling": "Start Journaling",
    "onboarding.saving": "Saving...",
    "onboarding.skipForNow": "Skip for now",
    "onboarding.getStarted": "Get Started",
    "onboarding.continue": "Continue",
    "onboarding.back": "Back",
    "onboarding.welcomeToast": "Welcome aboard! 🎉",
    "onboarding.profileReady": "Your Soul Profile is ready.",
    "onboarding.q1.title": "Tell me about yourself",
    "onboarding.q1.subtitle": "What brought you here? Share a bit about who you are.",
    "onboarding.q2.title": "What are you trying to improve?",
    "onboarding.q2.subtitle": "What changes or growth are you seeking in your life?",
    "onboarding.q3.title": "What are you proud of?",
    "onboarding.q3.subtitle": "Tell me about something that makes you proud of yourself.",
    "onboarding.q4.title": "What holds you back?",
    "onboarding.q4.subtitle": "What patterns or obstacles get in your way sometimes?",
    "onboarding.q5.title": "What are you afraid of?",
    "onboarding.q5.subtitle": "What do you fear losing, failing at, or becoming?",
    "onboarding.q6.title": "When do you feel most alive?",
    "onboarding.q6.subtitle": "What moments or activities make you feel truly motivated?",
    "onboarding.beliefSystem": "Your Belief System",
    "onboarding.beliefDesc": "This helps personalize your reflections and coaching with cultural sensitivity.",
    "onboarding.analyzingTitle": "Analyzing Your Soul Profile...",
    "onboarding.analyzingDesc": "AI is reading your answers and building your personalized psychological profile.",
    "onboarding.soulProfileTitle": "Your Soul Profile",
    "onboarding.discovered": "Here's what we discovered about you",
    "onboarding.yourStrengthsLabel": "Your Strengths",
    "onboarding.growthOpportunities": "Growth Opportunities",
    "onboarding.deepFears": "Deep Fears",
    "onboarding.personalityLabel": "Personality",
    "onboarding.enterApp": "Enter the App",
    "onboarding.analyzeProfile": "Analyze My Profile",
    "onboarding.next": "Next",
    "onboarding.chooseLanguage": "Choose Your Language",
    "onboarding.chooseLanguageDesc": "Select your preferred language for the app",
    "onboarding.tapReRecord": "Tap to re-record",
    "onboarding.tapRecord": "Tap to record your answer",
    "onboarding.orType": "Or type your answer here...",
    "onboarding.answerCaptured": "Answer captured",
    "onboarding.transcribing": "Transcribing...",
    "onboarding.question": "Question",
    "onboarding.belief": "Belief",
    "onboarding.analyzing": "Analyzing",
    "onboarding.profile": "Profile",
    "onboarding.language": "Language",
    "onboarding.worldviewIslam": "Islam",
    "onboarding.worldviewChristianity": "Christianity",
    "onboarding.worldviewJudaism": "Judaism",
    "onboarding.worldviewBuddhism": "Buddhism",
    "onboarding.worldviewHinduism": "Hinduism",
    "onboarding.worldviewSpiritual": "Spiritual",
    "onboarding.worldviewNoPref": "No preference",
    // Upgrade touchpoints
    "upgrade.badge": "Upgrade",
    "upgrade.winStreak": "See deeper patterns in your journey with Premium",
    "upgrade.winEntries": "Unlock AI insights & mood trends with Premium",
    "upgrade.lockedTitle": "Your Deeper Soul Map",
    "upgrade.lockedDesc": "Unlock this deeper analysis of your personality, strengths and hidden patterns",
    "upgrade.lockedLine1": "Your emotional patterns reveal a quiet strength",
    "upgrade.lockedLine2": "Hidden theme: you think clearest after rest",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.calendar": "Calendrier",
    "nav.add": "Ajouter",
    "nav.library": "Bibliothèque",
    "nav.profile": "Profil",
    "home.morning": "Bonjour",
    "home.afternoon": "Bon après-midi",
    "home.evening": "Bonsoir",
    "home.friend": "Ami",
    "home.quickCapture": "Capture rapide",
    "home.recentEntries": "Entrées récentes",
    "home.viewAll": "Voir tout",
    "home.noEntries": "Aucune entrée",
    "home.createFirst": "Créer votre première entrée",
    "record.title": "Nouvelle entrée",
    "record.tapToRecord": "Appuyez pour enregistrer vos pensées",
    "record.write": "Écrire",
    "record.howFeeling": "Comment vous sentez-vous ?",
    "record.selectMood": "Sélectionnez votre humeur",
    "record.enhance": "Améliorer",
    "record.save": "Sauvegarder",
    "record.saving": "Sauvegarde...",
    "record.recording": "Enregistrement...",
    "record.processing": "Traitement...",
    "record.limitReached": "Limite atteinte",
    "record.textLimit": "Entrées texte",
    "record.audioLimit": "Entrées audio",
    "record.today": "aujourd'hui",
    "record.thisWeek": "cette semaine",
    "record.upgradePremium": "Passer à Premium",
    "record.newEntry": "NOUVELLE ENTRÉE",
    "record.howAreYou": "Comment allez-vous, ",
    "record.tapToRecordAssessment": "Appuyez pour enregistrer",
    "record.recordingTime": "Enregistrement {time}... Appuyez pour arrêter",
    "record.audioLimitReached": "Limite audio atteinte",
    "record.writeLimit": "Écrire",
    "record.mood": "Humeur",
    "record.aiCoachReflection": "RÉFLEXION DU COACH IA",
    "record.recentEntries": "ENTRÉES RÉCENTES",
    "record.viewAll": "Voir tout",
    "record.whatsOnMind": "Qu'avez-vous en tête aujourd'hui ?",
    "record.continue": "Continuer",
    "record.originalTranscription": "Transcription originale",
    "record.enhanceWithAI": "Améliorer avec l'IA",
    "record.enhancing": "Amélioration...",
    "record.aiEnhanced": "Amélioré par l'IA",
    "record.addTitle": "Ajouter un titre (optionnel)",
    "record.voicePlaybackLanguage": "Langue de lecture vocale",
    "record.chooseLanguage": "Choisissez la langue pour écouter votre histoire",
    "record.generatingVoice": "Génération de la voix...",
    "record.previewVoice": "Aperçu vocal (Optionnel)",
    "record.pause": "Pause",
    "record.playPreview": "Écouter l'aperçu",
    "record.saveEntry": "Sauvegarder l'entrée",
    "record.entrySaved": "Entrée sauvegardée !",
    "record.entrySavedDesc": "Votre entrée de journal a été sauvegardée.",
    "record.textEntriesCount": "Entrées texte : {count}/2 aujourd'hui",
    "record.audioEntriesCount": "Entrées audio : {count}/1 cette semaine",
    "record.upgradeUnlimited": "Passer en illimité",
    "settings.title": "Paramètres",
    "settings.account": "Compte",
    "settings.profile": "Profil",
    "settings.security": "Sécurité & PIN",
    "settings.appearance": "Apparence",
    "settings.themes": "Thèmes",
    "settings.fonts": "Polices",
    "settings.darkMode": "Mode sombre",
    "settings.features": "Fonctionnalités",
    "settings.voice": "Paramètres vocaux",
    "settings.goals": "Objectifs & Intérêts",
    "settings.reminders": "Rappels",
    "settings.export": "Exporter le journal",
    "settings.coaching": "Coach IA",
    "settings.signOut": "Déconnexion",
    "settings.admin": "Tableau de bord admin",
    "settings.manageSubscription": "Gérer l'abonnement",
    "coaching.title": "Coach IA",
    "coaching.subtitle": "Votre coach personnel",
    "coaching.analyze": "Analyser ma semaine",
    "coaching.analyzing": "Analyse en cours...",
    "coaching.usageCounter": "appels coaching utilisés ce mois",
    "coaching.limitReached": "Limite mensuelle de coaching atteinte",
    "calendar.title": "Calendrier du journal",
    "calendar.noEntries": "Aucune entrée pour cette date",
    "insights.title": "Aperçus",
    "insights.moodTrend": "Tendance d'humeur",
    "insights.weeklyActivity": "Activité hebdomadaire",
    "export.title": "Exporter le journal",
    "export.download": "Téléchargez toutes vos entrées",
    "export.soulBook": "Constructeur de livre d'âme (PDF)",
    "export.quickMarkdown": "JSON / Markdown rapide",
    "export.quickPDF": "PDF rapide",
    "common.back": "Retour",
    "common.cancel": "Annuler",
    "common.save": "Sauvegarder",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.loading": "Chargement...",
    "common.error": "Une erreur est survenue",
    "common.success": "Succès",
    "common.upgrade": "Passer en Premium",
    "common.premium": "Premium",
    "common.language": "Langue",
    "auth.welcomeBack": "Bon retour ! Connectez-vous pour continuer",
    "auth.createAccount": "Créez votre compte",
    "auth.signIn": "Se connecter",
    "auth.signUp": "Créer un compte",
    "auth.yourName": "Votre nom",
    "auth.email": "Adresse e-mail",
    "auth.password": "Mot de passe",
    "auth.or": "ou",
    "auth.continueGoogle": "Continuer avec Google",
    "auth.noAccount": "Vous n'avez pas de compte ?",
    "auth.hasAccount": "Vous avez déjà un compte ?",
    "auth.signUpLink": "S'inscrire",
    "auth.signInLink": "Se connecter",
    "pricing.title": "Choisissez votre plan",
    "pricing.free": "Gratuit",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mois",
    "pricing.subtitle": "Débloquez l'expérience complète Echo Diary",
    "pricing.forever": "/pour toujours",
    "pricing.perYear": "/an",
    "pricing.premiumActive": "Premium actif",
    "pricing.granted": "Offert",
    "pricing.yearly": "Annuel",
    "pricing.monthly": "Mensuel",
    "pricing.renewsOn": "Renouvellement",
    "pricing.manageSubscription": "Gérer l'abonnement",
    "pricing.currentPlan": "Plan actuel",
    "pricing.yourPlan": "Votre plan",
    "pricing.premiumMonthly": "Premium mensuel",
    "pricing.premiumYearly": "Premium annuel",
    "pricing.save30": "ÉCONOMISEZ 30%",
    "pricing.justPerMonth": "Seulement",
    "pricing.savePerYear": "économisez",
    "pricing.subscribeMonthly": "S'abonner mensuellement",
    "pricing.subscribeYearly": "S'abonner annuellement — Meilleur prix",
    "pricing.refreshStatus": "Actualiser le statut d'abonnement",
    "pricing.loading": "Chargement...",
    "calendar.visualHistory": "HISTORIQUE VISUEL",
    "calendar.thisMonth": "Ce mois-ci",
    "calendar.entries": "entrées",
    "calendar.entry": "Entrée",
    "calendar.allEntries": "Toutes les entrées",
    "calendar.viewEntry": "Voir l'entrée",
    "calendar.noEntriesDay": "Aucune entrée pour ce jour",
    "calendar.createEntry": "Créer une entrée",
    "calendar.happy": "CONTENT",
    "calendar.fine": "BIEN",
    "calendar.sad": "TRISTE",
    "insights.yourPatterns": "Vos habitudes de journal",
    "insights.noEntries": "Aucune entrée",
    "insights.createFirst": "Créez votre première entrée",
    "insights.totalEntries": "Total des entrées",
    "insights.bestStreak": "Meilleure série",
    "insights.days": "jours",
    "insights.mostFelt": "Plus ressenti",
    "insights.avgLength": "Durée moy.",
    "insights.min": "min",
    "insights.thisWeek": "Cette semaine",
    "insights.languagesUsed": "Langues utilisées",
    "insights.detailedInsights": "Aperçus détaillés",
    "export.exportYourEntries": "Exporter vos entrées",
    "export.exportDescription": "Téléchargez toutes vos entrées pour une sauvegarde ou un partage.",
    "export.soulBookDesc": "Couverture, polices et mise en page personnalisables",
    "export.markdownDesc": "Sauvegarde texte de toutes les entrées",
    "export.quickPDFDesc": "Export simple sans personnalisation",
    "export.exportInfo": "Votre fichier exporté comprendra toutes les entrées avec dates, humeurs et contenu.",
    "export.noEntries": "Aucune entrée à exporter",
    "export.createFirst": "Créez d'abord des entrées !",
    "export.successMarkdown": "Export réussi ! 📝",
    "export.entriesExported": "entrées exportées en Markdown.",
    "export.successPDF": "PDF prêt ! 📄",
    "export.pdfDescription": "entrées préparées. Utilisez la boîte d'impression pour sauvegarder en PDF.",
    "export.failed": "Échec de l'export",
    "export.failedDesc": "Une erreur est survenue. Veuillez réessayer.",
    "export.journalExport": "Export du journal",
    "export.journalExportDesc": "Exportez votre journal en PDF ou Markdown. Passez en Premium pour débloquer.",
    "onboarding.welcome": "Bienvenue sur",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "Votre espace privé de réflexion. Parlez, l'IA affine vos pensées et découvrez des aperçus.",
    "onboarding.feature1": "Enregistrez des entrées vocales facilement",
    "onboarding.feature2": "Réflexions et coaching propulsés par l'IA",
    "onboarding.feature3": "Exportez votre parcours en livre",
    "onboarding.yourGoals": "Vos objectifs",
    "onboarding.goalsDesc": "Vers quoi travaillez-vous ? Choisissez quelques-uns.",
    "onboarding.worldview": "Vision du monde",
    "onboarding.worldviewDesc": "Personnalise vos réflexions Soul Mirror.",
    "onboarding.yourStrengths": "Vos forces",
    "onboarding.strengthsDesc": "Qu'apportez-vous ?",
    "onboarding.yourFears": "Vos peurs",
    "onboarding.fearsDesc": "L'honnêteté approfondit vos réflexions.",
    "onboarding.cloneVoice": "Clonez votre voix",
    "onboarding.cloneVoiceDesc": "Enregistrez 30 secondes et votre Soul Mirror vous lira avec votre propre voix.",
    "onboarding.setupVoiceClone": "Configurer le clone vocal",
    "onboarding.doLater": "Vous pouvez toujours le faire plus tard dans les paramètres.",
    "onboarding.allSet": "Vous êtes prêt !",
    "onboarding.allSetDesc": "Commencez par enregistrer votre première entrée. Parlez librement — l'IA s'occupe du reste.",
    "onboarding.startJournaling": "Commencer le journal",
    "onboarding.saving": "Sauvegarde...",
    "onboarding.skipForNow": "Passer pour l'instant",
    "onboarding.getStarted": "Commencer",
    "onboarding.continue": "Continuer",
    "onboarding.back": "Retour",
    "onboarding.welcomeToast": "Bienvenue ! 🎉",
    "onboarding.profileReady": "Votre profil est prêt.",
    "onboarding.q1.title": "Parlez-moi de vous",
    "onboarding.q1.subtitle": "Qu'est-ce qui vous amène ici ? Partagez un peu de qui vous êtes.",
    "onboarding.q2.title": "Que cherchez-vous à améliorer ?",
    "onboarding.q2.subtitle": "Quels changements ou quelle croissance recherchez-vous ?",
    "onboarding.q3.title": "De quoi êtes-vous fier(e) ?",
    "onboarding.q3.subtitle": "Parlez-moi de quelque chose qui vous rend fier(e).",
    "onboarding.q4.title": "Qu'est-ce qui vous retient ?",
    "onboarding.q4.subtitle": "Quels schémas ou obstacles se mettent en travers de votre chemin ?",
    "onboarding.q5.title": "De quoi avez-vous peur ?",
    "onboarding.q5.subtitle": "Que craignez-vous de perdre, d'échouer ou de devenir ?",
    "onboarding.q6.title": "Quand vous sentez-vous le plus vivant(e) ?",
    "onboarding.q6.subtitle": "Quels moments ou activités vous motivent vraiment ?",
    "onboarding.beliefSystem": "Votre système de croyances",
    "onboarding.beliefDesc": "Cela aide à personnaliser vos réflexions avec sensibilité culturelle.",
    "onboarding.analyzingTitle": "Analyse de votre profil...",
    "onboarding.analyzingDesc": "L'IA lit vos réponses et construit votre profil psychologique personnalisé.",
    "onboarding.soulProfileTitle": "Votre profil d'âme",
    "onboarding.discovered": "Voici ce que nous avons découvert sur vous",
    "onboarding.yourStrengthsLabel": "Vos forces",
    "onboarding.growthOpportunities": "Opportunités de croissance",
    "onboarding.deepFears": "Peurs profondes",
    "onboarding.personalityLabel": "Personnalité",
    "onboarding.enterApp": "Entrer dans l'application",
    "onboarding.analyzeProfile": "Analyser mon profil",
    "onboarding.next": "Suivant",
    "onboarding.chooseLanguage": "Choisissez votre langue",
    "onboarding.chooseLanguageDesc": "Sélectionnez votre langue préférée",
    "onboarding.tapReRecord": "Appuyez pour réenregistrer",
    "onboarding.tapRecord": "Appuyez pour enregistrer votre réponse",
    "onboarding.orType": "Ou tapez votre réponse ici...",
    "onboarding.answerCaptured": "Réponse enregistrée",
    "onboarding.transcribing": "Transcription...",
    "onboarding.question": "Question",
    "onboarding.belief": "Croyance",
    "onboarding.analyzing": "Analyse",
    "onboarding.profile": "Profil",
    "onboarding.language": "Langue",
    "onboarding.worldviewIslam": "Islam",
    "onboarding.worldviewChristianity": "Christianisme",
    "onboarding.worldviewJudaism": "Judaïsme",
    "onboarding.worldviewBuddhism": "Bouddhisme",
    "onboarding.worldviewHinduism": "Hindouisme",
    "onboarding.worldviewSpiritual": "Spirituel",
    "onboarding.worldviewNoPref": "Pas de préférence",
    // Upgrade touchpoints
    "upgrade.badge": "Premium",
    "upgrade.winStreak": "Voyez des tendances plus profondes dans votre parcours avec Premium",
    "upgrade.winEntries": "Débloquez les insights IA et les tendances d'humeur avec Premium",
    "upgrade.lockedTitle": "Votre carte d'âme profonde",
    "upgrade.lockedDesc": "Débloquez cette analyse plus profonde de votre personnalité, de vos forces et de vos schémas cachés",
    "upgrade.lockedLine1": "Vos émotions révèlent une force tranquille",
    "upgrade.lockedLine2": "Thème caché : vous pensez le plus clairement après le repos",
  },
  es: {
    "nav.home": "Inicio",
    "nav.calendar": "Calendario",
    "nav.add": "Añadir",
    "nav.library": "Biblioteca",
    "nav.profile": "Perfil",
    "home.morning": "Buenos días",
    "home.afternoon": "Buenas tardes",
    "home.evening": "Buenas noches",
    "home.friend": "Amigo",
    "home.quickCapture": "Captura rápida",
    "home.recentEntries": "Entradas recientes",
    "home.viewAll": "Ver todo",
    "home.noEntries": "Sin entradas aún",
    "home.createFirst": "Crea tu primera entrada",
    "record.title": "Nueva entrada",
    "record.tapToRecord": "Toca para grabar tus pensamientos",
    "record.write": "Escribir",
    "record.howFeeling": "¿Cómo te sientes?",
    "record.selectMood": "Selecciona tu estado de ánimo",
    "record.enhance": "Mejorar",
    "record.save": "Guardar",
    "record.saving": "Guardando...",
    "record.recording": "Grabando...",
    "record.processing": "Procesando...",
    "record.limitReached": "Límite alcanzado",
    "record.textLimit": "Entradas de texto",
    "record.audioLimit": "Entradas de audio",
    "record.today": "hoy",
    "record.thisWeek": "esta semana",
    "record.upgradePremium": "Actualizar a Premium",
    "record.newEntry": "NUEVA ENTRADA",
    "record.howAreYou": "¿Cómo estás, ",
    "record.tapToRecordAssessment": "Toca para grabar",
    "record.recordingTime": "Grabando {time}... Toca para detener",
    "record.audioLimitReached": "Límite de audio alcanzado",
    "record.writeLimit": "Escribir",
    "record.mood": "Ánimo",
    "record.aiCoachReflection": "REFLEXIÓN DEL COACH IA",
    "record.recentEntries": "ENTRADAS RECIENTES",
    "record.viewAll": "Ver todo",
    "record.whatsOnMind": "¿Qué tienes en mente hoy?",
    "record.continue": "Continuar",
    "record.originalTranscription": "Transcripción original",
    "record.enhanceWithAI": "Mejorar con IA",
    "record.enhancing": "Mejorando...",
    "record.aiEnhanced": "Mejorado por IA",
    "record.addTitle": "Añadir un título (opcional)",
    "record.voicePlaybackLanguage": "Idioma de reproducción de voz",
    "record.chooseLanguage": "Elige en qué idioma escuchar tu historia",
    "record.generatingVoice": "Generando voz...",
    "record.previewVoice": "Vista previa de voz (Opcional)",
    "record.pause": "Pausa",
    "record.playPreview": "Reproducir vista previa",
    "record.saveEntry": "Guardar entrada",
    "record.entrySaved": "¡Entrada guardada!",
    "record.entrySavedDesc": "Tu entrada de diario ha sido guardada.",
    "record.textEntriesCount": "Entradas de texto: {count}/2 hoy",
    "record.audioEntriesCount": "Entradas de audio: {count}/1 esta semana",
    "record.upgradeUnlimited": "Actualizar a ilimitado",
    "settings.title": "Configuración",
    "settings.account": "Cuenta",
    "settings.profile": "Perfil",
    "settings.security": "Seguridad y PIN",
    "settings.appearance": "Apariencia",
    "settings.themes": "Temas",
    "settings.fonts": "Fuentes",
    "settings.darkMode": "Modo oscuro",
    "settings.features": "Funciones",
    "settings.voice": "Configuración de voz",
    "settings.goals": "Objetivos e intereses",
    "settings.reminders": "Recordatorios",
    "settings.export": "Exportar diario",
    "settings.coaching": "Coach IA",
    "settings.signOut": "Cerrar sesión",
    "settings.admin": "Panel de administración",
    "settings.manageSubscription": "Gestionar suscripción",
    "coaching.title": "Coach IA",
    "coaching.subtitle": "Tu coach personal",
    "coaching.analyze": "Analizar mi semana",
    "coaching.analyzing": "Analizando...",
    "coaching.usageCounter": "llamadas de coaching usadas este mes",
    "coaching.limitReached": "Límite mensual de coaching alcanzado",
    "calendar.title": "Calendario del diario",
    "calendar.noEntries": "Sin entradas para esta fecha",
    "insights.title": "Perspectivas",
    "insights.moodTrend": "Tendencia de ánimo",
    "insights.weeklyActivity": "Actividad semanal",
    "export.title": "Exportar diario",
    "export.download": "Descarga todas tus entradas",
    "export.soulBook": "Constructor de libro del alma (PDF)",
    "export.quickMarkdown": "JSON / Markdown rápido",
    "export.quickPDF": "PDF rápido",
    "common.back": "Volver",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.loading": "Cargando...",
    "common.error": "Algo salió mal",
    "common.success": "Éxito",
    "common.upgrade": "Actualizar",
    "common.premium": "Premium",
    "common.language": "Idioma",
    "auth.welcomeBack": "¡Bienvenido de nuevo! Inicia sesión para continuar",
    "auth.createAccount": "Crea tu cuenta",
    "auth.signIn": "Iniciar sesión",
    "auth.signUp": "Crear cuenta",
    "auth.yourName": "Tu nombre",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.or": "o",
    "auth.continueGoogle": "Continuar con Google",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.hasAccount": "¿Ya tienes cuenta?",
    "auth.signUpLink": "Regístrate",
    "auth.signInLink": "Inicia sesión",
    "pricing.title": "Elige tu plan",
    "pricing.free": "Gratis",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mes",
    "pricing.subtitle": "Desbloquea la experiencia completa de Echo Diary",
    "pricing.forever": "/siempre",
    "pricing.perYear": "/año",
    "pricing.premiumActive": "Premium activo",
    "pricing.granted": "Otorgado",
    "pricing.yearly": "Anual",
    "pricing.monthly": "Mensual",
    "pricing.renewsOn": "Se renueva",
    "pricing.manageSubscription": "Gestionar suscripción",
    "pricing.currentPlan": "Plan actual",
    "pricing.yourPlan": "Tu plan",
    "pricing.premiumMonthly": "Premium mensual",
    "pricing.premiumYearly": "Premium anual",
    "pricing.save30": "AHORRA 30%",
    "pricing.justPerMonth": "Solo",
    "pricing.savePerYear": "ahorra",
    "pricing.subscribeMonthly": "Suscribirse mensualmente",
    "pricing.subscribeYearly": "Suscribirse anualmente — Mejor precio",
    "pricing.refreshStatus": "Actualizar estado de suscripción",
    "pricing.loading": "Cargando...",
    "calendar.visualHistory": "HISTORIAL VISUAL",
    "calendar.thisMonth": "Este mes",
    "calendar.entries": "entradas",
    "calendar.entry": "Entrada",
    "calendar.allEntries": "Todas las entradas",
    "calendar.viewEntry": "Ver entrada",
    "calendar.noEntriesDay": "Sin entradas para este día",
    "calendar.createEntry": "Crear entrada",
    "calendar.happy": "FELIZ",
    "calendar.fine": "BIEN",
    "calendar.sad": "TRISTE",
    "insights.yourPatterns": "Tus patrones de diario",
    "insights.noEntries": "Sin entradas aún",
    "insights.createFirst": "Crea tu primera entrada",
    "insights.totalEntries": "Total de entradas",
    "insights.bestStreak": "Mejor racha",
    "insights.days": "días",
    "insights.mostFelt": "Más sentido",
    "insights.avgLength": "Duración prom.",
    "insights.min": "min",
    "insights.thisWeek": "Esta semana",
    "insights.languagesUsed": "Idiomas usados",
    "insights.detailedInsights": "Perspectivas detalladas",
    "export.exportYourEntries": "Exportar tus entradas",
    "export.exportDescription": "Descarga todas tus entradas como archivo de respaldo o para compartir.",
    "export.soulBookDesc": "Portada, fuentes y diseño personalizables",
    "export.markdownDesc": "Respaldo en texto plano de todas las entradas",
    "export.quickPDFDesc": "Exportación simple sin personalización",
    "export.exportInfo": "Tu archivo exportado incluirá todas las entradas con fechas, ánimos y contenido.",
    "export.noEntries": "Sin entradas para exportar",
    "export.createFirst": "¡Crea algunas entradas primero!",
    "export.successMarkdown": "¡Exportación exitosa! 📝",
    "export.entriesExported": "entradas exportadas a Markdown.",
    "export.successPDF": "¡PDF listo! 📄",
    "export.pdfDescription": "entradas preparadas. Usa el diálogo de impresión para guardar como PDF.",
    "export.failed": "Exportación fallida",
    "export.failedDesc": "Algo salió mal. Inténtalo de nuevo.",
    "export.journalExport": "Exportar diario",
    "export.journalExportDesc": "Exporta tu diario como PDF o Markdown. Actualiza a Premium para desbloquear.",
    "onboarding.welcome": "Bienvenido a",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "Tu espacio privado de reflexión. Habla, la IA refina tus pensamientos y descubre perspectivas.",
    "onboarding.feature1": "Graba entradas de voz fácilmente",
    "onboarding.feature2": "Reflexiones y coaching con IA",
    "onboarding.feature3": "Exporta tu viaje como libro",
    "onboarding.yourGoals": "Tus objetivos",
    "onboarding.goalsDesc": "¿Hacia qué trabajas? Elige algunos.",
    "onboarding.worldview": "Visión del mundo",
    "onboarding.worldviewDesc": "Personaliza tus reflexiones del Soul Mirror.",
    "onboarding.yourStrengths": "Tus fortalezas",
    "onboarding.strengthsDesc": "¿Qué aportas?",
    "onboarding.yourFears": "Tus miedos",
    "onboarding.fearsDesc": "La honestidad profundiza tus reflexiones.",
    "onboarding.cloneVoice": "Clona tu voz",
    "onboarding.cloneVoiceDesc": "Graba 30 segundos y tu Soul Mirror te leerá con tu propia voz.",
    "onboarding.setupVoiceClone": "Configurar clon de voz",
    "onboarding.doLater": "Puedes hacerlo después en Configuración.",
    "onboarding.allSet": "¡Todo listo!",
    "onboarding.allSetDesc": "Comienza grabando tu primera entrada. Habla libremente — la IA se encarga del resto.",
    "onboarding.startJournaling": "Empezar a escribir",
    "onboarding.saving": "Guardando...",
    "onboarding.skipForNow": "Saltar por ahora",
    "onboarding.getStarted": "Empezar",
    "onboarding.continue": "Continuar",
    "onboarding.back": "Atrás",
    "onboarding.welcomeToast": "¡Bienvenido! 🎉",
    "onboarding.profileReady": "Tu perfil está listo.",
    "onboarding.q1.title": "Cuéntame sobre ti",
    "onboarding.q1.subtitle": "¿Qué te trajo aquí? Comparte un poco sobre quién eres.",
    "onboarding.q2.title": "¿Qué estás tratando de mejorar?",
    "onboarding.q2.subtitle": "¿Qué cambios o crecimiento buscas en tu vida?",
    "onboarding.q3.title": "¿De qué estás orgulloso/a?",
    "onboarding.q3.subtitle": "Cuéntame algo que te haga sentir orgulloso/a de ti mismo/a.",
    "onboarding.q4.title": "¿Qué te detiene?",
    "onboarding.q4.subtitle": "¿Qué patrones u obstáculos se interponen en tu camino?",
    "onboarding.q5.title": "¿A qué le tienes miedo?",
    "onboarding.q5.subtitle": "¿Qué temes perder, fallar o convertirte?",
    "onboarding.q6.title": "¿Cuándo te sientes más vivo/a?",
    "onboarding.q6.subtitle": "¿Qué momentos o actividades te motivan de verdad?",
    "onboarding.beliefSystem": "Tu sistema de creencias",
    "onboarding.beliefDesc": "Esto ayuda a personalizar tus reflexiones con sensibilidad cultural.",
    "onboarding.analyzingTitle": "Analizando tu perfil...",
    "onboarding.analyzingDesc": "La IA está leyendo tus respuestas y creando tu perfil psicológico personalizado.",
    "onboarding.soulProfileTitle": "Tu perfil del alma",
    "onboarding.discovered": "Esto es lo que descubrimos sobre ti",
    "onboarding.yourStrengthsLabel": "Tus fortalezas",
    "onboarding.growthOpportunities": "Oportunidades de crecimiento",
    "onboarding.deepFears": "Miedos profundos",
    "onboarding.personalityLabel": "Personalidad",
    "onboarding.enterApp": "Entrar a la app",
    "onboarding.analyzeProfile": "Analizar mi perfil",
    "onboarding.next": "Siguiente",
    "onboarding.chooseLanguage": "Elige tu idioma",
    "onboarding.chooseLanguageDesc": "Selecciona tu idioma preferido para la app",
    "onboarding.tapReRecord": "Toca para regrabar",
    "onboarding.tapRecord": "Toca para grabar tu respuesta",
    "onboarding.orType": "O escribe tu respuesta aquí...",
    "onboarding.answerCaptured": "Respuesta capturada",
    "onboarding.transcribing": "Transcribiendo...",
    "onboarding.question": "Pregunta",
    "onboarding.belief": "Creencia",
    "onboarding.analyzing": "Analizando",
    "onboarding.profile": "Perfil",
    "onboarding.language": "Idioma",
    "onboarding.worldviewIslam": "Islam",
    "onboarding.worldviewChristianity": "Cristianismo",
    "onboarding.worldviewJudaism": "Judaísmo",
    "onboarding.worldviewBuddhism": "Budismo",
    "onboarding.worldviewHinduism": "Hinduismo",
    "onboarding.worldviewSpiritual": "Espiritual",
    "onboarding.worldviewNoPref": "Sin preferencia",
    // Upgrade touchpoints
    "upgrade.badge": "Premium",
    "upgrade.winStreak": "Descubre patrones más profundos en tu camino con Premium",
    "upgrade.winEntries": "Desbloquea insights de IA y tendencias de humor con Premium",
    "upgrade.lockedTitle": "Tu mapa del alma profundo",
    "upgrade.lockedDesc": "Desbloquea este análisis más profundo de tu personalidad, fortalezas y patrones ocultos",
    "upgrade.lockedLine1": "Tus emociones revelan una fuerza tranquila",
    "upgrade.lockedLine2": "Tema oculto: piensas con claridad tras descansar",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.calendar": "التقويم",
    "nav.add": "إضافة",
    "nav.library": "المكتبة",
    "nav.profile": "الملف الشخصي",
    "home.morning": "صباح الخير",
    "home.afternoon": "مساء الخير",
    "home.evening": "مساء الخير",
    "home.friend": "صديق",
    "home.quickCapture": "التقاط سريع",
    "home.recentEntries": "الإدخالات الأخيرة",
    "home.viewAll": "عرض الكل",
    "home.noEntries": "لا توجد إدخالات بعد",
    "home.createFirst": "أنشئ إدخالك الأول",
    "record.title": "إدخال جديد",
    "record.tapToRecord": "اضغط لتسجيل أفكارك",
    "record.write": "كتابة",
    "record.howFeeling": "كيف تشعر؟",
    "record.selectMood": "اختر مزاجك",
    "record.enhance": "تحسين",
    "record.save": "حفظ",
    "record.saving": "جارٍ الحفظ...",
    "record.recording": "جارٍ التسجيل...",
    "record.processing": "جارٍ المعالجة...",
    "record.limitReached": "تم الوصول للحد",
    "record.textLimit": "إدخالات نصية",
    "record.audioLimit": "إدخالات صوتية",
    "record.today": "اليوم",
    "record.thisWeek": "هذا الأسبوع",
    "record.upgradePremium": "ترقية إلى Premium",
    "record.newEntry": "إدخال جديد",
    "record.howAreYou": "كيف حالك، ",
    "record.tapToRecordAssessment": "اضغط للتسجيل",
    "record.recordingTime": "تسجيل {time}... اضغط للإيقاف",
    "record.audioLimitReached": "تم الوصول لحد الصوت",
    "record.writeLimit": "كتابة",
    "record.mood": "المزاج",
    "record.aiCoachReflection": "تأمل مدرب الذكاء الاصطناعي",
    "record.recentEntries": "الإدخالات الأخيرة",
    "record.viewAll": "عرض الكل",
    "record.whatsOnMind": "ما الذي يشغل بالك اليوم؟",
    "record.continue": "متابعة",
    "record.originalTranscription": "النص الأصلي",
    "record.enhanceWithAI": "تحسين بالذكاء الاصطناعي",
    "record.enhancing": "جارٍ التحسين...",
    "record.aiEnhanced": "محسّن بالذكاء الاصطناعي",
    "record.addTitle": "أضف عنوانًا (اختياري)",
    "record.voicePlaybackLanguage": "لغة تشغيل الصوت",
    "record.chooseLanguage": "اختر اللغة لسماع قصتك",
    "record.generatingVoice": "جارٍ إنشاء الصوت...",
    "record.previewVoice": "معاينة الصوت (اختياري)",
    "record.pause": "إيقاف مؤقت",
    "record.playPreview": "تشغيل المعاينة",
    "record.saveEntry": "حفظ الإدخال",
    "record.entrySaved": "تم حفظ الإدخال!",
    "record.entrySavedDesc": "تم حفظ إدخال يومياتك.",
    "record.textEntriesCount": "إدخالات نصية: {count}/2 اليوم",
    "record.audioEntriesCount": "إدخالات صوتية: {count}/1 هذا الأسبوع",
    "record.upgradeUnlimited": "ترقية للامحدود",
    "settings.title": "الإعدادات",
    "settings.account": "الحساب",
    "settings.profile": "الملف الشخصي",
    "settings.security": "الأمان و PIN",
    "settings.appearance": "المظهر",
    "settings.themes": "السمات",
    "settings.fonts": "الخطوط",
    "settings.darkMode": "الوضع الداكن",
    "settings.features": "الميزات",
    "settings.voice": "إعدادات الصوت",
    "settings.goals": "الأهداف والاهتمامات",
    "settings.reminders": "التذكيرات",
    "settings.export": "تصدير اليوميات",
    "settings.coaching": "مدرب الذكاء الاصطناعي",
    "settings.signOut": "تسجيل الخروج",
    "settings.admin": "لوحة الإدارة",
    "settings.manageSubscription": "إدارة الاشتراك",
    "coaching.title": "مدرب الذكاء الاصطناعي",
    "coaching.subtitle": "مدربك الشخصي",
    "coaching.analyze": "تحليل أسبوعي",
    "coaching.analyzing": "جارٍ التحليل...",
    "coaching.usageCounter": "مكالمات تدريب مستخدمة هذا الشهر",
    "coaching.limitReached": "تم الوصول لحد التدريب الشهري",
    "calendar.title": "تقويم اليوميات",
    "calendar.noEntries": "لا توجد إدخالات لهذا التاريخ",
    "insights.title": "رؤى",
    "insights.moodTrend": "اتجاه المزاج",
    "insights.weeklyActivity": "النشاط الأسبوعي",
    "export.title": "تصدير اليوميات",
    "export.download": "تنزيل جميع إدخالاتك",
    "export.soulBook": "منشئ كتاب الروح (PDF)",
    "export.quickMarkdown": "JSON / Markdown سريع",
    "export.quickPDF": "PDF سريع",
    "common.back": "رجوع",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.loading": "جارٍ التحميل...",
    "common.error": "حدث خطأ ما",
    "common.success": "نجاح",
    "common.upgrade": "ترقية",
    "common.premium": "Premium",
    "common.language": "اللغة",
    "auth.welcomeBack": "مرحبًا بعودتك! سجّل الدخول للمتابعة",
    "auth.createAccount": "أنشئ حسابك",
    "auth.signIn": "تسجيل الدخول",
    "auth.signUp": "إنشاء حساب",
    "auth.yourName": "اسمك",
    "auth.email": "البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.or": "أو",
    "auth.continueGoogle": "المتابعة مع Google",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.hasAccount": "لديك حساب بالفعل؟",
    "auth.signUpLink": "سجّل",
    "auth.signInLink": "سجّل الدخول",
    "pricing.title": "اختر خطتك",
    "pricing.free": "مجاني",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/شهر",
    "pricing.subtitle": "افتح تجربة Echo Diary الكاملة",
    "pricing.forever": "/للأبد",
    "pricing.perYear": "/سنة",
    "pricing.premiumActive": "Premium نشط",
    "pricing.granted": "ممنوح",
    "pricing.yearly": "سنوي",
    "pricing.monthly": "شهري",
    "pricing.renewsOn": "يتجدد",
    "pricing.manageSubscription": "إدارة الاشتراك",
    "pricing.currentPlan": "الخطة الحالية",
    "pricing.yourPlan": "خطتك",
    "pricing.premiumMonthly": "Premium شهري",
    "pricing.premiumYearly": "Premium سنوي",
    "pricing.save30": "وفر 30%",
    "pricing.justPerMonth": "فقط",
    "pricing.savePerYear": "وفر",
    "pricing.subscribeMonthly": "اشترك شهرياً",
    "pricing.subscribeYearly": "اشترك سنوياً — أفضل قيمة",
    "pricing.refreshStatus": "تحديث حالة الاشتراك",
    "pricing.loading": "جارٍ التحميل...",
    "calendar.visualHistory": "السجل المرئي",
    "calendar.thisMonth": "هذا الشهر",
    "calendar.entries": "إدخالات",
    "calendar.entry": "إدخال",
    "calendar.allEntries": "جميع الإدخالات",
    "calendar.viewEntry": "عرض الإدخال",
    "calendar.noEntriesDay": "لا إدخالات لهذا اليوم",
    "calendar.createEntry": "إنشاء إدخال",
    "calendar.happy": "سعيد",
    "calendar.fine": "بخير",
    "calendar.sad": "حزين",
    "insights.yourPatterns": "أنماط يومياتك",
    "insights.noEntries": "لا إدخالات بعد",
    "insights.createFirst": "أنشئ إدخالك الأول",
    "insights.totalEntries": "إجمالي الإدخالات",
    "insights.bestStreak": "أفضل سلسلة",
    "insights.days": "أيام",
    "insights.mostFelt": "الأكثر شعوراً",
    "insights.avgLength": "متوسط الطول",
    "insights.min": "دقيقة",
    "insights.thisWeek": "هذا الأسبوع",
    "insights.languagesUsed": "اللغات المستخدمة",
    "insights.detailedInsights": "رؤى مفصلة",
    "export.exportYourEntries": "تصدير إدخالاتك",
    "export.exportDescription": "حمّل جميع إدخالاتك كنسخة احتياطية أو للمشاركة.",
    "export.soulBookDesc": "غلاف وخطوط وتخطيط قابلة للتخصيص",
    "export.markdownDesc": "نسخة نصية لجميع الإدخالات",
    "export.quickPDFDesc": "تصدير بسيط بدون تخصيص",
    "export.exportInfo": "سيشمل ملفك المصدّر جميع الإدخالات مع التواريخ والمزاج والمحتوى.",
    "export.noEntries": "لا إدخالات للتصدير",
    "export.createFirst": "أنشئ بعض الإدخالات أولاً!",
    "export.successMarkdown": "تم التصدير بنجاح! 📝",
    "export.entriesExported": "إدخالات صُدّرت إلى Markdown.",
    "export.successPDF": "PDF جاهز! 📄",
    "export.pdfDescription": "إدخالات جاهزة. استخدم حوار الطباعة للحفظ كـ PDF.",
    "export.failed": "فشل التصدير",
    "export.failedDesc": "حدث خطأ. يرجى المحاولة مرة أخرى.",
    "export.journalExport": "تصدير اليوميات",
    "export.journalExportDesc": "صدّر يومياتك كـ PDF أو Markdown. قم بالترقية لفتح هذه الميزة.",
    "onboarding.welcome": "مرحباً بك في",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "مساحتك الخاصة للتأمل. تحدث بأفكارك ودع الذكاء الاصطناعي يصقلها.",
    "onboarding.feature1": "سجّل إدخالات صوتية بسهولة",
    "onboarding.feature2": "تأملات وتدريب بالذكاء الاصطناعي",
    "onboarding.feature3": "صدّر رحلتك ككتاب",
    "onboarding.yourGoals": "أهدافك",
    "onboarding.goalsDesc": "ما الذي تعمل عليه؟ اختر بعضها.",
    "onboarding.worldview": "رؤية العالم",
    "onboarding.worldviewDesc": "تخصّص تأملات Soul Mirror.",
    "onboarding.yourStrengths": "نقاط قوتك",
    "onboarding.strengthsDesc": "ماذا تقدم؟",
    "onboarding.yourFears": "مخاوفك",
    "onboarding.fearsDesc": "الصدق يعمّق تأملاتك.",
    "onboarding.cloneVoice": "استنسخ صوتك",
    "onboarding.cloneVoiceDesc": "سجّل 30 ثانية وسيقرأ لك Soul Mirror بصوتك.",
    "onboarding.setupVoiceClone": "إعداد استنساخ الصوت",
    "onboarding.doLater": "يمكنك فعل ذلك لاحقاً في الإعدادات.",
    "onboarding.allSet": "أنت جاهز!",
    "onboarding.allSetDesc": "ابدأ بتسجيل أول إدخال. تحدث بحرية — الذكاء الاصطناعي يتولى الباقي.",
    "onboarding.startJournaling": "ابدأ التدوين",
    "onboarding.saving": "جارٍ الحفظ...",
    "onboarding.skipForNow": "تخطي الآن",
    "onboarding.getStarted": "ابدأ",
    "onboarding.continue": "متابعة",
    "onboarding.back": "رجوع",
    "onboarding.welcomeToast": "مرحباً! 🎉",
    "onboarding.profileReady": "ملفك الشخصي جاهز.",
    "onboarding.q1.title": "أخبرني عن نفسك",
    "onboarding.q1.subtitle": "ما الذي أحضرك إلى هنا؟ شارك قليلاً عن نفسك.",
    "onboarding.q2.title": "ما الذي تحاول تحسينه؟",
    "onboarding.q2.subtitle": "ما التغييرات أو النمو الذي تسعى إليه في حياتك؟",
    "onboarding.q3.title": "بماذا تفخر؟",
    "onboarding.q3.subtitle": "أخبرني عن شيء يجعلك فخوراً بنفسك.",
    "onboarding.q4.title": "ما الذي يعيقك؟",
    "onboarding.q4.subtitle": "ما الأنماط أو العقبات التي تقف في طريقك أحياناً؟",
    "onboarding.q5.title": "مما تخاف؟",
    "onboarding.q5.subtitle": "ما الذي تخشى فقدانه أو الفشل فيه أو أن تصبح عليه؟",
    "onboarding.q6.title": "متى تشعر بأنك أكثر حيوية؟",
    "onboarding.q6.subtitle": "ما اللحظات أو الأنشطة التي تحفزك حقاً؟",
    "onboarding.beliefSystem": "نظام معتقداتك",
    "onboarding.beliefDesc": "يساعد في تخصيص تأملاتك بحساسية ثقافية.",
    "onboarding.analyzingTitle": "جاري تحليل ملفك الشخصي...",
    "onboarding.analyzingDesc": "الذكاء الاصطناعي يقرأ إجاباتك ويبني ملفك النفسي المخصص.",
    "onboarding.soulProfileTitle": "ملف روحك",
    "onboarding.discovered": "هذا ما اكتشفناه عنك",
    "onboarding.yourStrengthsLabel": "نقاط قوتك",
    "onboarding.growthOpportunities": "فرص النمو",
    "onboarding.deepFears": "المخاوف العميقة",
    "onboarding.personalityLabel": "الشخصية",
    "onboarding.enterApp": "دخول التطبيق",
    "onboarding.analyzeProfile": "تحليل ملفي",
    "onboarding.next": "التالي",
    "onboarding.chooseLanguage": "اختر لغتك",
    "onboarding.chooseLanguageDesc": "اختر لغتك المفضلة للتطبيق",
    "onboarding.tapReRecord": "اضغط لإعادة التسجيل",
    "onboarding.tapRecord": "اضغط لتسجيل إجابتك",
    "onboarding.orType": "أو اكتب إجابتك هنا...",
    "onboarding.answerCaptured": "تم التقاط الإجابة",
    "onboarding.transcribing": "جاري النسخ...",
    "onboarding.question": "سؤال",
    "onboarding.belief": "المعتقد",
    "onboarding.analyzing": "تحليل",
    "onboarding.profile": "الملف",
    "onboarding.language": "اللغة",
    "onboarding.worldviewIslam": "الإسلام",
    "onboarding.worldviewChristianity": "المسيحية",
    "onboarding.worldviewJudaism": "اليهودية",
    "onboarding.worldviewBuddhism": "البوذية",
    "onboarding.worldviewHinduism": "الهندوسية",
    "onboarding.worldviewSpiritual": "روحاني",
    "onboarding.worldviewNoPref": "بدون تفضيل",
    // Upgrade touchpoints
    "upgrade.badge": "الترقية",
    "upgrade.winStreak": "اكتشف أنماطًا أعمق في رحلتك مع Premium",
    "upgrade.winEntries": "افتح رؤى الذكاء الاصطناعي واتجاهات المزاج مع Premium",
    "upgrade.lockedTitle": "خريطة روحك العميقة",
    "upgrade.lockedDesc": "افتح هذا التحليل الأعمق لشخصيتك ونقاط قوتك وأنماطك المخفية",
    "upgrade.lockedLine1": "تكشف مشاعرك قوة هادئة",
    "upgrade.lockedLine2": "موضوع خفي: تفكيرك أوضح بعد الراحة",
  },
  zh: {
    "nav.home": "首页",
    "nav.calendar": "日历",
    "nav.add": "添加",
    "nav.library": "图书馆",
    "nav.profile": "个人资料",
    "home.morning": "早上好",
    "home.afternoon": "下午好",
    "home.evening": "晚上好",
    "home.friend": "朋友",
    "home.quickCapture": "快速记录",
    "home.recentEntries": "最近的条目",
    "home.viewAll": "查看全部",
    "home.noEntries": "还没有条目",
    "home.createFirst": "创建您的第一个条目",
    "record.title": "新条目",
    "record.tapToRecord": "点击录制您的想法",
    "record.write": "写作",
    "record.howFeeling": "您感觉如何？",
    "record.selectMood": "选择您的心情",
    "record.enhance": "优化",
    "record.save": "保存",
    "record.saving": "保存中...",
    "record.recording": "录制中...",
    "record.processing": "处理中...",
    "record.limitReached": "已达上限",
    "record.textLimit": "文字条目",
    "record.audioLimit": "音频条目",
    "record.today": "今天",
    "record.thisWeek": "本周",
    "record.upgradePremium": "升级至 Premium",
    "record.newEntry": "新条目",
    "record.howAreYou": "你好吗，",
    "record.tapToRecordAssessment": "点击录制",
    "record.recordingTime": "录制中 {time}... 点击停止",
    "record.audioLimitReached": "音频上限已达",
    "record.writeLimit": "写作",
    "record.mood": "心情",
    "record.aiCoachReflection": "AI 教练反思",
    "record.recentEntries": "最近条目",
    "record.viewAll": "查看全部",
    "record.whatsOnMind": "今天在想什么？",
    "record.continue": "继续",
    "record.originalTranscription": "原始转录",
    "record.enhanceWithAI": "AI 优化",
    "record.enhancing": "优化中...",
    "record.aiEnhanced": "AI 已优化",
    "record.addTitle": "添加标题（可选）",
    "record.voicePlaybackLanguage": "语音播放语言",
    "record.chooseLanguage": "选择收听故事的语言",
    "record.generatingVoice": "生成语音中...",
    "record.previewVoice": "预览语音（可选）",
    "record.pause": "暂停",
    "record.playPreview": "播放预览",
    "record.saveEntry": "保存条目",
    "record.entrySaved": "条目已保存！",
    "record.entrySavedDesc": "您的日记条目已保存。",
    "record.textEntriesCount": "文字条目：{count}/2 今天",
    "record.audioEntriesCount": "音频条目：{count}/1 本周",
    "record.upgradeUnlimited": "升级至无限",
    "settings.title": "设置",
    "settings.account": "账户",
    "settings.profile": "个人资料",
    "settings.security": "安全与 PIN",
    "settings.appearance": "外观",
    "settings.themes": "主题",
    "settings.fonts": "字体",
    "settings.darkMode": "深色模式",
    "settings.features": "功能",
    "settings.voice": "语音设置",
    "settings.goals": "目标与兴趣",
    "settings.reminders": "提醒",
    "settings.export": "导出日记",
    "settings.coaching": "AI 教练",
    "settings.signOut": "退出登录",
    "settings.admin": "管理后台",
    "settings.manageSubscription": "管理订阅",
    "coaching.title": "AI 教练",
    "coaching.subtitle": "您的个人教练",
    "coaching.analyze": "分析我的一周",
    "coaching.analyzing": "分析中...",
    "coaching.usageCounter": "本月已使用教练次数",
    "coaching.limitReached": "已达月度教练上限",
    "calendar.title": "日记日历",
    "calendar.noEntries": "此日期无条目",
    "insights.title": "洞察",
    "insights.moodTrend": "情绪趋势",
    "insights.weeklyActivity": "每周活动",
    "export.title": "导出日记",
    "export.download": "下载所有条目",
    "export.soulBook": "灵魂之书构建器 (PDF)",
    "export.quickMarkdown": "快速 JSON / Markdown",
    "export.quickPDF": "快速 PDF",
    "common.back": "返回",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.loading": "加载中...",
    "common.error": "出了点问题",
    "common.success": "成功",
    "common.upgrade": "升级",
    "common.premium": "Premium",
    "common.language": "语言",
    "auth.welcomeBack": "欢迎回来！请登录继续",
    "auth.createAccount": "创建您的账户",
    "auth.signIn": "登录",
    "auth.signUp": "创建账户",
    "auth.yourName": "您的姓名",
    "auth.email": "电子邮箱",
    "auth.password": "密码",
    "auth.or": "或",
    "auth.continueGoogle": "使用 Google 继续",
    "auth.noAccount": "没有账户？",
    "auth.hasAccount": "已有账户？",
    "auth.signUpLink": "注册",
    "auth.signInLink": "登录",
    "pricing.title": "选择您的计划",
    "pricing.free": "免费",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/月",
    "pricing.subtitle": "解锁完整的 Echo Diary 体验",
    "pricing.forever": "/永久",
    "pricing.perYear": "/年",
    "pricing.premiumActive": "Premium 已激活",
    "pricing.granted": "已授予",
    "pricing.yearly": "年度",
    "pricing.monthly": "月度",
    "pricing.renewsOn": "续期",
    "pricing.manageSubscription": "管理订阅",
    "pricing.currentPlan": "当前计划",
    "pricing.yourPlan": "您的计划",
    "pricing.premiumMonthly": "Premium 月度",
    "pricing.premiumYearly": "Premium 年度",
    "pricing.save30": "节省 30%",
    "pricing.justPerMonth": "仅",
    "pricing.savePerYear": "节省",
    "pricing.subscribeMonthly": "月度订阅",
    "pricing.subscribeYearly": "年度订阅 — 最佳价值",
    "pricing.refreshStatus": "刷新订阅状态",
    "pricing.loading": "加载中...",
    "calendar.visualHistory": "视觉历史",
    "calendar.thisMonth": "本月",
    "calendar.entries": "条目",
    "calendar.entry": "条目",
    "calendar.allEntries": "所有条目",
    "calendar.viewEntry": "查看条目",
    "calendar.noEntriesDay": "今天没有条目",
    "calendar.createEntry": "创建条目",
    "calendar.happy": "开心",
    "calendar.fine": "还好",
    "calendar.sad": "难过",
    "insights.yourPatterns": "您的日记模式",
    "insights.noEntries": "还没有条目",
    "insights.createFirst": "创建第一个条目",
    "insights.totalEntries": "总条目数",
    "insights.bestStreak": "最佳连续",
    "insights.days": "天",
    "insights.mostFelt": "最多感受",
    "insights.avgLength": "平均时长",
    "insights.min": "分钟",
    "insights.thisWeek": "本周",
    "insights.languagesUsed": "使用的语言",
    "insights.detailedInsights": "详细洞察",
    "export.exportYourEntries": "导出您的条目",
    "export.exportDescription": "下载所有日记条目作为备份或分享。",
    "export.soulBookDesc": "可定制封面、字体和布局",
    "export.markdownDesc": "所有条目的纯文本备份",
    "export.quickPDFDesc": "简单格式导出，无定制",
    "export.exportInfo": "您的导出文件将包含所有条目及其日期、情绪和内容。",
    "export.noEntries": "没有条目可导出",
    "export.createFirst": "请先创建一些日记条目！",
    "export.successMarkdown": "导出成功！📝",
    "export.entriesExported": "条目已导出为 Markdown。",
    "export.successPDF": "PDF 已就绪！📄",
    "export.pdfDescription": "条目已准备好。使用打印对话框保存为 PDF。",
    "export.failed": "导出失败",
    "export.failedDesc": "出了点问题。请重试。",
    "export.journalExport": "日记导出",
    "export.journalExportDesc": "将日记导出为 PDF 或 Markdown。升级到 Premium 解锁。",
    "onboarding.welcome": "欢迎来到",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "您的私人反思空间。说出您的想法，让 AI 提炼它们。",
    "onboarding.feature1": "轻松录制语音条目",
    "onboarding.feature2": "AI 驱动的反思与教练",
    "onboarding.feature3": "将您的旅程导出为书籍",
    "onboarding.yourGoals": "您的目标",
    "onboarding.goalsDesc": "您在努力实现什么？选择几个。",
    "onboarding.worldview": "世界观",
    "onboarding.worldviewDesc": "个性化您的 Soul Mirror 反思。",
    "onboarding.yourStrengths": "您的优势",
    "onboarding.strengthsDesc": "您能带来什么？",
    "onboarding.yourFears": "您的恐惧",
    "onboarding.fearsDesc": "诚实让反思更深入。",
    "onboarding.cloneVoice": "克隆您的声音",
    "onboarding.cloneVoiceDesc": "录制30秒，Soul Mirror 将用您自己的声音朗读。",
    "onboarding.setupVoiceClone": "设置声音克隆",
    "onboarding.doLater": "您可以稍后在设置中完成。",
    "onboarding.allSet": "一切就绪！",
    "onboarding.allSetDesc": "开始录制您的第一个日记条目。自由表达 — AI 会处理剩下的。",
    "onboarding.startJournaling": "开始写日记",
    "onboarding.saving": "保存中...",
    "onboarding.skipForNow": "暂时跳过",
    "onboarding.getStarted": "开始",
    "onboarding.continue": "继续",
    "onboarding.back": "返回",
    "onboarding.welcomeToast": "欢迎！🎉",
    "onboarding.profileReady": "您的个人资料已就绪。",
    "onboarding.q1.title": "介绍一下你自己",
    "onboarding.q1.subtitle": "是什么让你来到这里？分享一下你是谁。",
    "onboarding.q2.title": "你正在努力改善什么？",
    "onboarding.q2.subtitle": "你在生活中寻求什么样的改变或成长？",
    "onboarding.q3.title": "你为什么感到自豪？",
    "onboarding.q3.subtitle": "告诉我一些让你为自己感到骄傲的事情。",
    "onboarding.q4.title": "什么在阻碍你？",
    "onboarding.q4.subtitle": "哪些模式或障碍有时会妨碍你？",
    "onboarding.q5.title": "你害怕什么？",
    "onboarding.q5.subtitle": "你害怕失去、失败或变成什么？",
    "onboarding.q6.title": "什么时候你感觉最有活力？",
    "onboarding.q6.subtitle": "哪些时刻或活动让你感到真正的动力？",
    "onboarding.beliefSystem": "你的信仰体系",
    "onboarding.beliefDesc": "这有助于以文化敏感性个性化你的反思。",
    "onboarding.analyzingTitle": "正在分析你的灵魂档案...",
    "onboarding.analyzingDesc": "AI正在阅读你的回答并构建你的个性化心理档案。",
    "onboarding.soulProfileTitle": "你的灵魂档案",
    "onboarding.discovered": "这是我们发现的关于你的信息",
    "onboarding.yourStrengthsLabel": "你的优势",
    "onboarding.growthOpportunities": "成长机会",
    "onboarding.deepFears": "深层恐惧",
    "onboarding.personalityLabel": "性格",
    "onboarding.enterApp": "进入应用",
    "onboarding.analyzeProfile": "分析我的档案",
    "onboarding.next": "下一步",
    "onboarding.chooseLanguage": "选择你的语言",
    "onboarding.chooseLanguageDesc": "选择你喜欢的应用语言",
    "onboarding.tapReRecord": "点击重新录制",
    "onboarding.tapRecord": "点击录制你的回答",
    "onboarding.orType": "或在这里输入你的回答...",
    "onboarding.answerCaptured": "回答已记录",
    "onboarding.transcribing": "正在转录...",
    "onboarding.question": "问题",
    "onboarding.belief": "信仰",
    "onboarding.analyzing": "分析中",
    "onboarding.profile": "档案",
    "onboarding.language": "语言",
    "onboarding.worldviewIslam": "伊斯兰教",
    "onboarding.worldviewChristianity": "基督教",
    "onboarding.worldviewJudaism": "犹太教",
    "onboarding.worldviewBuddhism": "佛教",
    "onboarding.worldviewHinduism": "印度教",
    "onboarding.worldviewSpiritual": "灵性",
    "onboarding.worldviewNoPref": "无偏好",
    // Upgrade touchpoints
    "upgrade.badge": "升级",
    "upgrade.winStreak": "使用 Premium 发现你旅程中更深层的模式",
    "upgrade.winEntries": "使用 Premium 解锁 AI 洞察与情绪趋势",
    "upgrade.lockedTitle": "你的深层灵魂地图",
    "upgrade.lockedDesc": "使用 Premium 解锁对你性格、优势与隐藏模式的更深入分析",
    "upgrade.lockedLine1": "你的情感模式揭示了一种宁静的力量",
    "upgrade.lockedLine2": "隐藏主题：休息后你的思维最清晰",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.calendar": "カレンダー",
    "nav.add": "追加",
    "nav.library": "ライブラリ",
    "nav.profile": "プロフィール",
    "home.morning": "おはようございます",
    "home.afternoon": "こんにちは",
    "home.evening": "こんばんは",
    "home.friend": "フレンド",
    "home.quickCapture": "クイック記録",
    "home.recentEntries": "最近のエントリー",
    "home.viewAll": "すべて表示",
    "home.noEntries": "エントリーがありません",
    "home.createFirst": "最初のエントリーを作成",
    "record.title": "新しいエントリー",
    "record.tapToRecord": "タップして思考を記録",
    "record.write": "書く",
    "record.howFeeling": "気分はどうですか？",
    "record.selectMood": "気分を選択",
    "record.enhance": "改善",
    "record.save": "保存",
    "record.saving": "保存中...",
    "record.recording": "録音中...",
    "record.processing": "処理中...",
    "record.limitReached": "上限に達しました",
    "record.textLimit": "テキストエントリー",
    "record.audioLimit": "音声エントリー",
    "record.today": "今日",
    "record.thisWeek": "今週",
    "record.upgradePremium": "Premiumにアップグレード",
    "record.newEntry": "新しいエントリー",
    "record.howAreYou": "お元気ですか、",
    "record.tapToRecordAssessment": "タップして録音",
    "record.recordingTime": "録音中 {time}... タップで停止",
    "record.audioLimitReached": "音声上限に達しました",
    "record.writeLimit": "書く",
    "record.mood": "気分",
    "record.aiCoachReflection": "AIコーチの振り返り",
    "record.recentEntries": "最近のエントリー",
    "record.viewAll": "すべて表示",
    "record.whatsOnMind": "今日は何を考えていますか？",
    "record.continue": "続ける",
    "record.originalTranscription": "元の文字起こし",
    "record.enhanceWithAI": "AIで改善",
    "record.enhancing": "改善中...",
    "record.aiEnhanced": "AI改善済み",
    "record.addTitle": "タイトルを追加（任意）",
    "record.voicePlaybackLanguage": "音声再生言語",
    "record.chooseLanguage": "ストーリーを聞く言語を選択",
    "record.generatingVoice": "音声生成中...",
    "record.previewVoice": "音声プレビュー（任意）",
    "record.pause": "一時停止",
    "record.playPreview": "プレビュー再生",
    "record.saveEntry": "エントリーを保存",
    "record.entrySaved": "エントリーが保存されました！",
    "record.entrySavedDesc": "日記エントリーが保存されました。",
    "record.textEntriesCount": "テキスト：{count}/2 今日",
    "record.audioEntriesCount": "音声：{count}/1 今週",
    "record.upgradeUnlimited": "無制限にアップグレード",
    "settings.title": "設定",
    "settings.account": "アカウント",
    "settings.profile": "プロフィール",
    "settings.security": "セキュリティ & PIN",
    "settings.appearance": "外観",
    "settings.themes": "テーマ",
    "settings.fonts": "フォント",
    "settings.darkMode": "ダークモード",
    "settings.features": "機能",
    "settings.voice": "音声設定",
    "settings.goals": "目標と興味",
    "settings.reminders": "リマインダー",
    "settings.export": "日記をエクスポート",
    "settings.coaching": "AIコーチ",
    "settings.signOut": "サインアウト",
    "settings.admin": "管理ダッシュボード",
    "settings.manageSubscription": "サブスクリプション管理",
    "coaching.title": "AIコーチ",
    "coaching.subtitle": "あなたの個人コーチ",
    "coaching.analyze": "今週を分析",
    "coaching.analyzing": "分析中...",
    "coaching.usageCounter": "今月のコーチング利用回数",
    "coaching.limitReached": "月間コーチング上限に達しました",
    "calendar.title": "日記カレンダー",
    "calendar.noEntries": "この日付のエントリーはありません",
    "insights.title": "インサイト",
    "insights.moodTrend": "気分の傾向",
    "insights.weeklyActivity": "週間アクティビティ",
    "export.title": "日記をエクスポート",
    "export.download": "すべてのエントリーをダウンロード",
    "export.soulBook": "ソウルブックビルダー (PDF)",
    "export.quickMarkdown": "クイック JSON / Markdown",
    "export.quickPDF": "クイック PDF",
    "common.back": "戻る",
    "common.cancel": "キャンセル",
    "common.save": "保存",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.loading": "読み込み中...",
    "common.error": "エラーが発生しました",
    "common.success": "成功",
    "common.upgrade": "アップグレード",
    "common.premium": "Premium",
    "common.language": "言語",
    "auth.welcomeBack": "おかえりなさい！ログインして続行",
    "auth.createAccount": "アカウントを作成",
    "auth.signIn": "ログイン",
    "auth.signUp": "アカウント作成",
    "auth.yourName": "お名前",
    "auth.email": "メールアドレス",
    "auth.password": "パスワード",
    "auth.or": "または",
    "auth.continueGoogle": "Googleで続行",
    "auth.noAccount": "アカウントをお持ちでない方",
    "auth.hasAccount": "アカウントをお持ちの方",
    "auth.signUpLink": "登録",
    "auth.signInLink": "ログイン",
    "pricing.title": "プランを選択",
    "pricing.free": "無料",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/月",
    "pricing.subtitle": "Echo Diary の完全な体験をアンロック",
    "pricing.forever": "/永久",
    "pricing.perYear": "/年",
    "pricing.premiumActive": "Premium アクティブ",
    "pricing.granted": "付与済み",
    "pricing.yearly": "年間",
    "pricing.monthly": "月間",
    "pricing.renewsOn": "更新日",
    "pricing.manageSubscription": "サブスクリプション管理",
    "pricing.currentPlan": "現在のプラン",
    "pricing.yourPlan": "あなたのプラン",
    "pricing.premiumMonthly": "Premium 月間",
    "pricing.premiumYearly": "Premium 年間",
    "pricing.save30": "30% お得",
    "pricing.justPerMonth": "わずか",
    "pricing.savePerYear": "節約",
    "pricing.subscribeMonthly": "月額で購読",
    "pricing.subscribeYearly": "年額で購読 — 最もお得",
    "pricing.refreshStatus": "サブスクリプション状態を更新",
    "pricing.loading": "読み込み中...",
    "calendar.visualHistory": "ビジュアル履歴",
    "calendar.thisMonth": "今月",
    "calendar.entries": "エントリー",
    "calendar.entry": "エントリー",
    "calendar.allEntries": "すべてのエントリー",
    "calendar.viewEntry": "エントリーを表示",
    "calendar.noEntriesDay": "この日のエントリーはありません",
    "calendar.createEntry": "エントリーを作成",
    "calendar.happy": "幸せ",
    "calendar.fine": "普通",
    "calendar.sad": "悲しい",
    "insights.yourPatterns": "日記のパターン",
    "insights.noEntries": "エントリーがありません",
    "insights.createFirst": "最初のエントリーを作成",
    "insights.totalEntries": "合計エントリー",
    "insights.bestStreak": "最高連続記録",
    "insights.days": "日",
    "insights.mostFelt": "最も感じた",
    "insights.avgLength": "平均時間",
    "insights.min": "分",
    "insights.thisWeek": "今週",
    "insights.languagesUsed": "使用言語",
    "insights.detailedInsights": "詳細なインサイト",
    "export.exportYourEntries": "エントリーをエクスポート",
    "export.exportDescription": "すべての日記エントリーをバックアップまたは共有用にダウンロード。",
    "export.soulBookDesc": "カスタマイズ可能なカバー、フォント、レイアウト",
    "export.markdownDesc": "すべてのエントリーのテキストバックアップ",
    "export.quickPDFDesc": "シンプルなフォーマットエクスポート",
    "export.exportInfo": "エクスポートファイルにはすべてのエントリーの日付、気分、内容が含まれます。",
    "export.noEntries": "エクスポートするエントリーがありません",
    "export.createFirst": "まず日記エントリーを作成してください！",
    "export.successMarkdown": "エクスポート成功！📝",
    "export.entriesExported": "エントリーを Markdown にエクスポートしました。",
    "export.successPDF": "PDF 準備完了！📄",
    "export.pdfDescription": "エントリーが準備されました。印刷ダイアログで PDF として保存してください。",
    "export.failed": "エクスポート失敗",
    "export.failedDesc": "エラーが発生しました。再試行してください。",
    "export.journalExport": "日記エクスポート",
    "export.journalExportDesc": "日記を PDF または Markdown でエクスポート。Premium にアップグレードしてアンロック。",
    "onboarding.welcome": "ようこそ",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "あなただけの内省空間。思いを語り、AI が磨き上げ、洞察を発見。",
    "onboarding.feature1": "簡単に音声エントリーを記録",
    "onboarding.feature2": "AI による振り返りとコーチング",
    "onboarding.feature3": "旅を本としてエクスポート",
    "onboarding.yourGoals": "あなたの目標",
    "onboarding.goalsDesc": "何に向かっていますか？いくつか選んでください。",
    "onboarding.worldview": "世界観",
    "onboarding.worldviewDesc": "Soul Mirror の反映をカスタマイズ。",
    "onboarding.yourStrengths": "あなたの強み",
    "onboarding.strengthsDesc": "何を提供できますか？",
    "onboarding.yourFears": "あなたの恐れ",
    "onboarding.fearsDesc": "正直さが振り返りを深めます。",
    "onboarding.cloneVoice": "声をクローン",
    "onboarding.cloneVoiceDesc": "30秒録音すれば Soul Mirror があなたの声で読み上げます。",
    "onboarding.setupVoiceClone": "ボイスクローン設定",
    "onboarding.doLater": "後で設定から行えます。",
    "onboarding.allSet": "準備完了！",
    "onboarding.allSetDesc": "最初のエントリーを録音して始めましょう。自由に話してください — AI が残りを処理します。",
    "onboarding.startJournaling": "ジャーナルを始める",
    "onboarding.saving": "保存中...",
    "onboarding.skipForNow": "今はスキップ",
    "onboarding.getStarted": "始める",
    "onboarding.continue": "続ける",
    "onboarding.back": "戻る",
    "onboarding.welcomeToast": "ようこそ！🎉",
    "onboarding.profileReady": "プロフィールの準備ができました。",
    "onboarding.q1.title": "あなたについて教えてください",
    "onboarding.q1.subtitle": "ここに来たきっかけは何ですか？あなた自身について少し教えてください。",
    "onboarding.q2.title": "何を改善しようとしていますか？",
    "onboarding.q2.subtitle": "人生でどんな変化や成長を求めていますか？",
    "onboarding.q3.title": "何を誇りに思っていますか？",
    "onboarding.q3.subtitle": "自分を誇りに思えることを教えてください。",
    "onboarding.q4.title": "何があなたを妨げていますか？",
    "onboarding.q4.subtitle": "どんなパターンや障害が時々邪魔をしますか？",
    "onboarding.q5.title": "何を恐れていますか？",
    "onboarding.q5.subtitle": "失うこと、失敗すること、なることを恐れているものは何ですか？",
    "onboarding.q6.title": "最も生き生きと感じるのはいつですか？",
    "onboarding.q6.subtitle": "どんな瞬間や活動が本当にやる気を起こさせますか？",
    "onboarding.beliefSystem": "あなたの信念体系",
    "onboarding.beliefDesc": "文化的感受性を持ってリフレクションをカスタマイズするのに役立ちます。",
    "onboarding.analyzingTitle": "ソウルプロフィールを分析中...",
    "onboarding.analyzingDesc": "AIがあなたの回答を読み、パーソナライズされた心理プロフィールを作成しています。",
    "onboarding.soulProfileTitle": "あなたのソウルプロフィール",
    "onboarding.discovered": "あなたについて発見したことです",
    "onboarding.yourStrengthsLabel": "あなたの強み",
    "onboarding.growthOpportunities": "成長の機会",
    "onboarding.deepFears": "深い恐れ",
    "onboarding.personalityLabel": "性格",
    "onboarding.enterApp": "アプリに入る",
    "onboarding.analyzeProfile": "プロフィールを分析",
    "onboarding.next": "次へ",
    "onboarding.chooseLanguage": "言語を選択",
    "onboarding.chooseLanguageDesc": "アプリの言語を選択してください",
    "onboarding.tapReRecord": "タップして再録音",
    "onboarding.tapRecord": "タップして回答を録音",
    "onboarding.orType": "またはここに回答を入力...",
    "onboarding.answerCaptured": "回答が記録されました",
    "onboarding.transcribing": "文字起こし中...",
    "onboarding.question": "質問",
    "onboarding.belief": "信念",
    "onboarding.analyzing": "分析中",
    "onboarding.profile": "プロフィール",
    "onboarding.language": "言語",
    "onboarding.worldviewIslam": "イスラム教",
    "onboarding.worldviewChristianity": "キリスト教",
    "onboarding.worldviewJudaism": "ユダヤ教",
    "onboarding.worldviewBuddhism": "仏教",
    "onboarding.worldviewHinduism": "ヒンドゥー教",
    "onboarding.worldviewSpiritual": "スピリチュアル",
    "onboarding.worldviewNoPref": "特になし",
    // Upgrade touchpoints
    "upgrade.badge": "アップグレード",
    "upgrade.winStreak": "Premiumで旅のより深いパターンを見つけよう",
    "upgrade.winEntries": "PremiumでAIインサイトと気分の傾向を解放",
    "upgrade.lockedTitle": "あなたの深層ソウルマップ",
    "upgrade.lockedDesc": "Premiumで、性格・強み・隠れたパターンのより深い分析を解放",
    "upgrade.lockedLine1": "感情のパターンが静かな強さを明らかにします",
    "upgrade.lockedLine2": "隠れたテーマ：休息後に思考が最も明晰に",
  },
  sw: {
    "nav.home": "Nyumbani",
    "nav.calendar": "Kalenda",
    "nav.add": "Ongeza",
    "nav.library": "Maktaba",
    "nav.profile": "Wasifu",
    "home.morning": "Habari za asubuhi",
    "home.afternoon": "Habari za mchana",
    "home.evening": "Habari za jioni",
    "home.friend": "Rafiki",
    "home.quickCapture": "Chukua haraka",
    "home.recentEntries": "Maingizo ya hivi karibuni",
    "home.viewAll": "Tazama yote",
    "home.noEntries": "Hakuna maingizo bado",
    "home.createFirst": "Unda ingizo lako la kwanza",
    "record.title": "Ingizo jipya",
    "record.tapToRecord": "Gusa ili kurekodi mawazo yako",
    "record.write": "Andika",
    "record.howFeeling": "Unajisikiaje?",
    "record.selectMood": "Chagua hali yako",
    "record.enhance": "Boresha",
    "record.save": "Hifadhi",
    "record.saving": "Inahifadhi...",
    "record.recording": "Inarekodi...",
    "record.processing": "Inachakata...",
    "record.limitReached": "Kikomo kimefikiwa",
    "record.textLimit": "Maingizo ya maandishi",
    "record.audioLimit": "Maingizo ya sauti",
    "record.today": "leo",
    "record.thisWeek": "wiki hii",
    "record.upgradePremium": "Panda hadi Premium",
    "record.newEntry": "INGIZO JIPYA",
    "record.howAreYou": "Habari yako, ",
    "record.tapToRecordAssessment": "Gusa ili kurekodi",
    "record.recordingTime": "Inarekodi {time}... Gusa kusimamisha",
    "record.audioLimitReached": "Kikomo cha sauti kimefikiwa",
    "record.writeLimit": "Andika",
    "record.mood": "Hali",
    "record.aiCoachReflection": "TAFAKURI YA KOCHA WA AI",
    "record.recentEntries": "MAINGIZO YA HIVI KARIBUNI",
    "record.viewAll": "Tazama yote",
    "record.whatsOnMind": "Una nini akilini leo?",
    "record.continue": "Endelea",
    "record.originalTranscription": "Maandishi ya awali",
    "record.enhanceWithAI": "Boresha na AI",
    "record.enhancing": "Inaboresha...",
    "record.aiEnhanced": "Imeboreshwa na AI",
    "record.addTitle": "Ongeza kichwa (hiari)",
    "record.voicePlaybackLanguage": "Lugha ya kucheza sauti",
    "record.chooseLanguage": "Chagua lugha ya kusikiliza hadithi yako",
    "record.generatingVoice": "Inaunda sauti...",
    "record.previewVoice": "Hakiki sauti (Hiari)",
    "record.pause": "Simamisha",
    "record.playPreview": "Cheza hakiki",
    "record.saveEntry": "Hifadhi ingizo",
    "record.entrySaved": "Ingizo limehifadhiwa!",
    "record.entrySavedDesc": "Ingizo lako la jarida limehifadhiwa.",
    "record.textEntriesCount": "Maingizo ya maandishi: {count}/2 leo",
    "record.audioEntriesCount": "Maingizo ya sauti: {count}/1 wiki hii",
    "record.upgradeUnlimited": "Panda kwa bila kikomo",
    "settings.title": "Mipangilio",
    "settings.account": "Akaunti",
    "settings.profile": "Wasifu",
    "settings.security": "Usalama & PIN",
    "settings.appearance": "Muonekano",
    "settings.themes": "Mandhari",
    "settings.fonts": "Fonti",
    "settings.darkMode": "Hali ya giza",
    "settings.features": "Vipengele",
    "settings.voice": "Mipangilio ya sauti",
    "settings.goals": "Malengo na Maslahi",
    "settings.reminders": "Vikumbusho",
    "settings.export": "Hamisha jarida",
    "settings.coaching": "Kocha wa AI",
    "settings.signOut": "Ondoka",
    "settings.admin": "Dashibodi ya msimamizi",
    "settings.manageSubscription": "Dhibiti usajili",
    "coaching.title": "Kocha wa AI",
    "coaching.subtitle": "Kocha wako binafsi",
    "coaching.analyze": "Changanua wiki yangu",
    "coaching.analyzing": "Inachambua...",
    "coaching.usageCounter": "simu za kocha zilizotumika mwezi huu",
    "coaching.limitReached": "Kikomo cha kocha cha mwezi kimefikiwa",
    "calendar.title": "Kalenda ya jarida",
    "calendar.noEntries": "Hakuna maingizo kwa tarehe hii",
    "insights.title": "Maarifa",
    "insights.moodTrend": "Mwenendo wa hali",
    "insights.weeklyActivity": "Shughuli za wiki",
    "export.title": "Hamisha jarida",
    "export.download": "Pakua maingizo yako yote",
    "export.soulBook": "Mjenzi wa Kitabu cha Roho (PDF)",
    "export.quickMarkdown": "JSON / Markdown haraka",
    "export.quickPDF": "PDF haraka",
    "common.back": "Rudi",
    "common.cancel": "Ghairi",
    "common.save": "Hifadhi",
    "common.delete": "Futa",
    "common.edit": "Hariri",
    "common.loading": "Inapakia...",
    "common.error": "Kuna kosa limetokea",
    "common.success": "Imefanikiwa",
    "common.upgrade": "Panda daraja",
    "common.premium": "Premium",
    "common.language": "Lugha",
    "auth.welcomeBack": "Karibu tena! Ingia kuendelea",
    "auth.createAccount": "Fungua akaunti yako",
    "auth.signIn": "Ingia",
    "auth.signUp": "Fungua akaunti",
    "auth.yourName": "Jina lako",
    "auth.email": "Barua pepe",
    "auth.password": "Nenosiri",
    "auth.or": "au",
    "auth.continueGoogle": "Endelea na Google",
    "auth.noAccount": "Huna akaunti?",
    "auth.hasAccount": "Tayari una akaunti?",
    "auth.signUpLink": "Jisajili",
    "auth.signInLink": "Ingia",
    "pricing.title": "Chagua mpango wako",
    "pricing.free": "Bure",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mwezi",
    "pricing.subtitle": "Fungua uzoefu kamili wa Echo Diary",
    "pricing.forever": "/milele",
    "pricing.perYear": "/mwaka",
    "pricing.premiumActive": "Premium Inatumika",
    "pricing.granted": "Imetolewa",
    "pricing.yearly": "Kwa mwaka",
    "pricing.monthly": "Kwa mwezi",
    "pricing.renewsOn": "Inafanywa upya",
    "pricing.manageSubscription": "Dhibiti usajili",
    "pricing.currentPlan": "Mpango wa sasa",
    "pricing.yourPlan": "Mpango wako",
    "pricing.premiumMonthly": "Premium kwa mwezi",
    "pricing.premiumYearly": "Premium kwa mwaka",
    "pricing.save30": "OKOA 30%",
    "pricing.justPerMonth": "Tu",
    "pricing.savePerYear": "okoa",
    "pricing.subscribeMonthly": "Jiandikishe kwa mwezi",
    "pricing.subscribeYearly": "Jiandikishe kwa mwaka — Thamani bora",
    "pricing.refreshStatus": "Sasisha hali ya usajili",
    "pricing.loading": "Inapakia...",
    "calendar.visualHistory": "HISTORIA YA KUONA",
    "calendar.thisMonth": "Mwezi huu",
    "calendar.entries": "maingizo",
    "calendar.entry": "Ingizo",
    "calendar.allEntries": "Maingizo yote",
    "calendar.viewEntry": "Tazama ingizo",
    "calendar.noEntriesDay": "Hakuna maingizo kwa siku hii",
    "calendar.createEntry": "Unda ingizo",
    "calendar.happy": "FURAHA",
    "calendar.fine": "SAWA",
    "calendar.sad": "HUZUNI",
    "insights.yourPatterns": "Mifumo yako ya jarida",
    "insights.noEntries": "Hakuna maingizo bado",
    "insights.createFirst": "Unda ingizo lako la kwanza",
    "insights.totalEntries": "Jumla ya maingizo",
    "insights.bestStreak": "Mfuatano bora",
    "insights.days": "siku",
    "insights.mostFelt": "Iliyohisiwa zaidi",
    "insights.avgLength": "Urefu wa wastani",
    "insights.min": "dakika",
    "insights.thisWeek": "Wiki hii",
    "insights.languagesUsed": "Lugha zilizotumika",
    "insights.detailedInsights": "Maarifa ya kina",
    "export.exportYourEntries": "Hamisha maingizo yako",
    "export.exportDescription": "Pakua maingizo yako yote kama nakala rudufu au kushiriki.",
    "export.soulBookDesc": "Jalada, fonti na mpangilio unaoweza kubinafsishwa",
    "export.markdownDesc": "Nakala ya maandishi ya maingizo yote",
    "export.quickPDFDesc": "Uhamishaji rahisi bila ubinafsishaji",
    "export.exportInfo": "Faili yako itajumuisha maingizo yote pamoja na tarehe, hali na maudhui.",
    "export.noEntries": "Hakuna maingizo ya kuhamisha",
    "export.createFirst": "Unda maingizo kwanza!",
    "export.successMarkdown": "Uhamishaji umefanikiwa! 📝",
    "export.entriesExported": "maingizo yamehamishwa kwa Markdown.",
    "export.successPDF": "PDF iko tayari! 📄",
    "export.pdfDescription": "maingizo yametayarishwa. Tumia mazungumzo ya kuchapisha kuhifadhi kama PDF.",
    "export.failed": "Uhamishaji umeshindwa",
    "export.failedDesc": "Kuna kosa limetokea. Tafadhali jaribu tena.",
    "export.journalExport": "Hamisha jarida",
    "export.journalExportDesc": "Hamisha jarida lako kama PDF au Markdown. Panda daraja ili kufungua.",
    "onboarding.welcome": "Karibu kwenye",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "Nafasi yako ya faragha ya kutafakari. Sema mawazo yako, AI itayasafisha.",
    "onboarding.feature1": "Rekodi maingizo ya sauti kwa urahisi",
    "onboarding.feature2": "Tafakuri na mafunzo ya AI",
    "onboarding.feature3": "Hamisha safari yako kama kitabu",
    "onboarding.yourGoals": "Malengo yako",
    "onboarding.goalsDesc": "Unafanya kazi kuelekea nini? Chagua machache.",
    "onboarding.worldview": "Mtazamo wa ulimwengu",
    "onboarding.worldviewDesc": "Inabinafsisha tafakuri zako za Soul Mirror.",
    "onboarding.yourStrengths": "Nguvu zako",
    "onboarding.strengthsDesc": "Unaleta nini?",
    "onboarding.yourFears": "Hofu zako",
    "onboarding.fearsDesc": "Uaminifu unasaidia tafakuri kuwa za kina.",
    "onboarding.cloneVoice": "Nakili sauti yako",
    "onboarding.cloneVoiceDesc": "Rekodi sekunde 30 na Soul Mirror itakusomea kwa sauti yako mwenyewe.",
    "onboarding.setupVoiceClone": "Weka nakala ya sauti",
    "onboarding.doLater": "Unaweza kufanya hivi baadaye kwenye Mipangilio.",
    "onboarding.allSet": "Uko tayari!",
    "onboarding.allSetDesc": "Anza kwa kurekodi ingizo lako la kwanza. Sema kwa uhuru — AI itashughulikia mengine.",
    "onboarding.startJournaling": "Anza kuandika jarida",
    "onboarding.saving": "Inahifadhi...",
    "onboarding.skipForNow": "Ruka kwa sasa",
    "onboarding.getStarted": "Anza",
    "onboarding.continue": "Endelea",
    "onboarding.back": "Rudi",
    "onboarding.welcomeToast": "Karibu! 🎉",
    "onboarding.profileReady": "Wasifu wako uko tayari.",
    "onboarding.q1.title": "Niambie kuhusu wewe",
    "onboarding.q1.subtitle": "Ni nini kilichokuleta hapa? Shiriki kidogo kuhusu wewe ni nani.",
    "onboarding.q2.title": "Unajaribu kuboresha nini?",
    "onboarding.q2.subtitle": "Mabadiliko au ukuaji gani unautafuta maishani mwako?",
    "onboarding.q3.title": "Unajivunia nini?",
    "onboarding.q3.subtitle": "Niambie kitu kinachokufanya ujivunie.",
    "onboarding.q4.title": "Nini kinakuzuia?",
    "onboarding.q4.subtitle": "Ni mifumo au vikwazo gani vinavyokuzuia wakati mwingine?",
    "onboarding.q5.title": "Unaogopa nini?",
    "onboarding.q5.subtitle": "Unaogopa kupoteza, kushindwa, au kuwa nini?",
    "onboarding.q6.title": "Lini unahisi hai zaidi?",
    "onboarding.q6.subtitle": "Ni wakati gani au shughuli zipi zinazokupa motisha kweli?",
    "onboarding.beliefSystem": "Mfumo wako wa imani",
    "onboarding.beliefDesc": "Hii inasaidia kubinafsisha tafakari zako kwa unyeti wa kitamaduni.",
    "onboarding.analyzingTitle": "Kuchambua wasifu wako...",
    "onboarding.analyzingDesc": "AI inasoma majibu yako na kujenga wasifu wako wa kisaikolojia.",
    "onboarding.soulProfileTitle": "Wasifu wa roho yako",
    "onboarding.discovered": "Hivi ndivyo tulivyogundua kuhusu wewe",
    "onboarding.yourStrengthsLabel": "Nguvu zako",
    "onboarding.growthOpportunities": "Fursa za kukua",
    "onboarding.deepFears": "Hofu za ndani",
    "onboarding.personalityLabel": "Utu",
    "onboarding.enterApp": "Ingia kwenye programu",
    "onboarding.analyzeProfile": "Chambua wasifu wangu",
    "onboarding.next": "Ifuatayo",
    "onboarding.chooseLanguage": "Chagua lugha yako",
    "onboarding.chooseLanguageDesc": "Chagua lugha unayopendelea kwa programu",
    "onboarding.tapReRecord": "Gusa kurekodi tena",
    "onboarding.tapRecord": "Gusa kurekodi jibu lako",
    "onboarding.orType": "Au andika jibu lako hapa...",
    "onboarding.answerCaptured": "Jibu limerekodiwa",
    "onboarding.transcribing": "Inakili...",
    "onboarding.question": "Swali",
    "onboarding.belief": "Imani",
    "onboarding.analyzing": "Kuchambua",
    "onboarding.profile": "Wasifu",
    "onboarding.language": "Lugha",
    "onboarding.worldviewIslam": "Uislamu",
    "onboarding.worldviewChristianity": "Ukristo",
    "onboarding.worldviewJudaism": "Uyahudi",
    "onboarding.worldviewBuddhism": "Ubudha",
    "onboarding.worldviewHinduism": "Uhindu",
    "onboarding.worldviewSpiritual": "Kiroho",
    "onboarding.worldviewNoPref": "Bila upendeleo",
    // Upgrade touchpoints
    "upgrade.badge": "Boresha",
    "upgrade.winStreak": "Ona mifumo ya ndani zaidi katika safari yako na Premium",
    "upgrade.winEntries": "Fungua maarifa ya AI na mwenendo wa hisia na Premium",
    "upgrade.lockedTitle": "Ramani yako ya kina ya roho",
    "upgrade.lockedDesc": "Fungua uchambuzi huu wa ndani zaidi wa utu wako, nguvu zako na mifumo iliyofichika",
    "upgrade.lockedLine1": "Hisia zako zinaonyesha nguvu ya utulivu",
    "upgrade.lockedLine2": "Mada iliyofichika: unafikiri vizuri zaidi baada ya kupumzika",
  },
  de: {
    "nav.home": "Startseite",
    "nav.calendar": "Kalender",
    "nav.add": "Hinzufügen",
    "nav.library": "Bibliothek",
    "nav.profile": "Profil",
    "home.morning": "Guten Morgen",
    "home.afternoon": "Guten Tag",
    "home.evening": "Guten Abend",
    "home.friend": "Freund",
    "home.quickCapture": "Schnellaufnahme",
    "home.recentEntries": "Letzte Einträge",
    "home.viewAll": "Alle anzeigen",
    "home.noEntries": "Noch keine Einträge",
    "home.createFirst": "Erstelle deinen ersten Eintrag",
    "record.title": "Neuer Eintrag",
    "record.tapToRecord": "Tippe, um deine Gedanken aufzunehmen",
    "record.write": "Schreiben",
    "record.howFeeling": "Wie fühlst du dich?",
    "record.selectMood": "Wähle deine Stimmung",
    "record.enhance": "Verbessern",
    "record.save": "Speichern",
    "record.saving": "Speichern...",
    "record.recording": "Aufnahme...",
    "record.processing": "Verarbeitung...",
    "record.limitReached": "Limit erreicht",
    "record.textLimit": "Texteinträge",
    "record.audioLimit": "Audioeinträge",
    "record.today": "heute",
    "record.thisWeek": "diese Woche",
    "record.upgradePremium": "Auf Premium upgraden",
    "record.newEntry": "NEUER EINTRAG",
    "record.howAreYou": "Wie geht es dir, ",
    "record.tapToRecordAssessment": "Tippe zum Aufnehmen",
    "record.recordingTime": "Aufnahme {time}... Tippe zum Stoppen",
    "record.audioLimitReached": "Audio-Limit erreicht",
    "record.writeLimit": "Schreiben",
    "record.mood": "Stimmung",
    "record.aiCoachReflection": "KI-COACH REFLEXION",
    "record.recentEntries": "LETZTE EINTRÄGE",
    "record.viewAll": "Alle anzeigen",
    "record.whatsOnMind": "Was beschäftigt dich heute?",
    "record.continue": "Weiter",
    "record.originalTranscription": "Originaltranskription",
    "record.enhanceWithAI": "Mit KI verbessern",
    "record.enhancing": "Verbessern...",
    "record.aiEnhanced": "KI-verbessert",
    "record.addTitle": "Titel hinzufügen (optional)",
    "record.voicePlaybackLanguage": "Sprachwiedergabe",
    "record.chooseLanguage": "Wähle die Sprache für deine Geschichte",
    "record.generatingVoice": "Stimme wird erzeugt...",
    "record.previewVoice": "Stimmvorschau (Optional)",
    "record.pause": "Pause",
    "record.playPreview": "Vorschau abspielen",
    "record.saveEntry": "Eintrag speichern",
    "record.entrySaved": "Eintrag gespeichert!",
    "record.entrySavedDesc": "Dein Tagebucheintrag wurde gespeichert.",
    "record.textEntriesCount": "Texteinträge: {count}/2 heute",
    "record.audioEntriesCount": "Audioeinträge: {count}/1 diese Woche",
    "record.upgradeUnlimited": "Auf unbegrenzt upgraden",
    "settings.title": "Einstellungen",
    "settings.account": "Konto",
    "settings.profile": "Profil",
    "settings.security": "Sicherheit & PIN",
    "settings.appearance": "Erscheinungsbild",
    "settings.themes": "Themen",
    "settings.fonts": "Schriftarten",
    "settings.darkMode": "Dunkelmodus",
    "settings.features": "Funktionen",
    "settings.voice": "Spracheinstellungen",
    "settings.goals": "Ziele & Interessen",
    "settings.reminders": "Erinnerungen",
    "settings.export": "Tagebuch exportieren",
    "settings.coaching": "KI-Coach",
    "settings.signOut": "Abmelden",
    "settings.admin": "Admin-Dashboard",
    "settings.manageSubscription": "Abo verwalten",
    "coaching.title": "KI-Coach",
    "coaching.subtitle": "Dein persönlicher Coach",
    "coaching.analyze": "Meine Woche analysieren",
    "coaching.analyzing": "Analyse läuft...",
    "coaching.usageCounter": "Coaching-Anrufe diesen Monat genutzt",
    "coaching.limitReached": "Monatliches Coaching-Limit erreicht",
    "calendar.title": "Tagebuch-Kalender",
    "calendar.noEntries": "Keine Einträge für dieses Datum",
    "insights.title": "Einblicke",
    "insights.moodTrend": "Stimmungstrend",
    "insights.weeklyActivity": "Wöchentliche Aktivität",
    "export.title": "Tagebuch exportieren",
    "export.download": "Alle Einträge herunterladen",
    "export.soulBook": "Seelenbuch-Builder (PDF)",
    "export.quickMarkdown": "Schnell JSON / Markdown",
    "export.quickPDF": "Schnell PDF",
    "common.back": "Zurück",
    "common.cancel": "Abbrechen",
    "common.save": "Speichern",
    "common.delete": "Löschen",
    "common.edit": "Bearbeiten",
    "common.loading": "Laden...",
    "common.error": "Etwas ist schiefgelaufen",
    "common.success": "Erfolg",
    "common.upgrade": "Upgraden",
    "common.premium": "Premium",
    "common.language": "Sprache",
    "auth.welcomeBack": "Willkommen zurück! Melde dich an, um fortzufahren",
    "auth.createAccount": "Erstelle dein Konto",
    "auth.signIn": "Anmelden",
    "auth.signUp": "Konto erstellen",
    "auth.yourName": "Dein Name",
    "auth.email": "E-Mail-Adresse",
    "auth.password": "Passwort",
    "auth.or": "oder",
    "auth.continueGoogle": "Weiter mit Google",
    "auth.noAccount": "Noch kein Konto?",
    "auth.hasAccount": "Bereits ein Konto?",
    "auth.signUpLink": "Registrieren",
    "auth.signInLink": "Anmelden",
    "pricing.title": "Wähle deinen Plan",
    "pricing.free": "Kostenlos",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/Monat",
    "pricing.subtitle": "Schalte das volle Echo Diary Erlebnis frei",
    "pricing.forever": "/für immer",
    "pricing.perYear": "/Jahr",
    "pricing.premiumActive": "Premium aktiv",
    "pricing.granted": "Gewährt",
    "pricing.yearly": "Jährlich",
    "pricing.monthly": "Monatlich",
    "pricing.renewsOn": "Verlängerung",
    "pricing.manageSubscription": "Abo verwalten",
    "pricing.currentPlan": "Aktueller Plan",
    "pricing.yourPlan": "Dein Plan",
    "pricing.premiumMonthly": "Premium monatlich",
    "pricing.premiumYearly": "Premium jährlich",
    "pricing.save30": "30% SPAREN",
    "pricing.justPerMonth": "Nur",
    "pricing.savePerYear": "spare",
    "pricing.subscribeMonthly": "Monatlich abonnieren",
    "pricing.subscribeYearly": "Jährlich abonnieren — Bester Wert",
    "pricing.refreshStatus": "Abonnementstatus aktualisieren",
    "pricing.loading": "Laden...",
    "calendar.visualHistory": "VISUELLE HISTORIE",
    "calendar.thisMonth": "Dieser Monat",
    "calendar.entries": "Einträge",
    "calendar.entry": "Eintrag",
    "calendar.allEntries": "Alle Einträge",
    "calendar.viewEntry": "Eintrag anzeigen",
    "calendar.noEntriesDay": "Keine Einträge für diesen Tag",
    "calendar.createEntry": "Eintrag erstellen",
    "calendar.happy": "GLÜCKLICH",
    "calendar.fine": "OK",
    "calendar.sad": "TRAURIG",
    "insights.yourPatterns": "Deine Tagebuchmuster",
    "insights.noEntries": "Noch keine Einträge",
    "insights.createFirst": "Erstelle deinen ersten Eintrag",
    "insights.totalEntries": "Gesamt Einträge",
    "insights.bestStreak": "Beste Serie",
    "insights.days": "Tage",
    "insights.mostFelt": "Am meisten gefühlt",
    "insights.avgLength": "Durchschn. Länge",
    "insights.min": "Min",
    "insights.thisWeek": "Diese Woche",
    "insights.languagesUsed": "Verwendete Sprachen",
    "insights.detailedInsights": "Detaillierte Einblicke",
    "export.exportYourEntries": "Deine Einträge exportieren",
    "export.exportDescription": "Lade alle Tagebucheinträge als Backup oder zum Teilen herunter.",
    "export.soulBookDesc": "Anpassbares Cover, Schriften und Layout",
    "export.markdownDesc": "Textbackup aller Einträge",
    "export.quickPDFDesc": "Einfacher Export ohne Anpassung",
    "export.exportInfo": "Deine Exportdatei enthält alle Einträge mit Datum, Stimmung und Inhalt.",
    "export.noEntries": "Keine Einträge zum Exportieren",
    "export.createFirst": "Erstelle zuerst einige Einträge!",
    "export.successMarkdown": "Export erfolgreich! 📝",
    "export.entriesExported": "Einträge als Markdown exportiert.",
    "export.successPDF": "PDF bereit! 📄",
    "export.pdfDescription": "Einträge vorbereitet. Nutze den Druckdialog zum Speichern als PDF.",
    "export.failed": "Export fehlgeschlagen",
    "export.failedDesc": "Etwas ist schiefgelaufen. Bitte versuche es erneut.",
    "export.journalExport": "Tagebuch exportieren",
    "export.journalExportDesc": "Exportiere dein Tagebuch als PDF oder Markdown. Upgrade auf Premium zum Freischalten.",
    "onboarding.welcome": "Willkommen bei",
    "onboarding.appName": "Voice Journal",
    "onboarding.welcomeDesc": "Dein privater Raum zur Selbstreflexion. Sprich deine Gedanken aus, KI verfeinert sie.",
    "onboarding.feature1": "Spracheinträge mühelos aufnehmen",
    "onboarding.feature2": "KI-gestützte Reflexionen & Coaching",
    "onboarding.feature3": "Exportiere deine Reise als Buch",
    "onboarding.yourGoals": "Deine Ziele",
    "onboarding.goalsDesc": "Woran arbeitest du? Wähle einige aus.",
    "onboarding.worldview": "Weltanschauung",
    "onboarding.worldviewDesc": "Personalisiert deine Soul Mirror Reflexionen.",
    "onboarding.yourStrengths": "Deine Stärken",
    "onboarding.strengthsDesc": "Was bringst du mit?",
    "onboarding.yourFears": "Deine Ängste",
    "onboarding.fearsDesc": "Ehrlichkeit vertieft deine Reflexionen.",
    "onboarding.cloneVoice": "Klone deine Stimme",
    "onboarding.cloneVoiceDesc": "Nimm 30 Sekunden auf und dein Soul Mirror liest dir mit deiner eigenen Stimme vor.",
    "onboarding.setupVoiceClone": "Stimmklon einrichten",
    "onboarding.doLater": "Du kannst das später in den Einstellungen tun.",
    "onboarding.allSet": "Alles bereit!",
    "onboarding.allSetDesc": "Beginne mit deinem ersten Tagebucheintrag. Sprich frei — die KI erledigt den Rest.",
    "onboarding.startJournaling": "Tagebuch starten",
    "onboarding.saving": "Speichern...",
    "onboarding.skipForNow": "Vorerst überspringen",
    "onboarding.getStarted": "Los geht's",
    "onboarding.continue": "Weiter",
    "onboarding.back": "Zurück",
    "onboarding.welcomeToast": "Willkommen! 🎉",
    "onboarding.profileReady": "Dein Profil ist bereit.",
    "onboarding.q1.title": "Erzähl mir von dir",
    "onboarding.q1.subtitle": "Was hat dich hierher gebracht? Teile ein wenig über dich.",
    "onboarding.q2.title": "Was versuchst du zu verbessern?",
    "onboarding.q2.subtitle": "Welche Veränderungen oder welches Wachstum suchst du?",
    "onboarding.q3.title": "Worauf bist du stolz?",
    "onboarding.q3.subtitle": "Erzähl mir etwas, das dich stolz auf dich macht.",
    "onboarding.q4.title": "Was hält dich zurück?",
    "onboarding.q4.subtitle": "Welche Muster oder Hindernisse stehen dir manchmal im Weg?",
    "onboarding.q5.title": "Wovor hast du Angst?",
    "onboarding.q5.subtitle": "Was fürchtest du zu verlieren, zu versagen oder zu werden?",
    "onboarding.q6.title": "Wann fühlst du dich am lebendigsten?",
    "onboarding.q6.subtitle": "Welche Momente oder Aktivitäten motivieren dich wirklich?",
    "onboarding.beliefSystem": "Dein Glaubenssystem",
    "onboarding.beliefDesc": "Dies hilft, deine Reflexionen kultursensibel zu personalisieren.",
    "onboarding.analyzingTitle": "Dein Seelenprofil wird analysiert...",
    "onboarding.analyzingDesc": "KI liest deine Antworten und erstellt dein personalisiertes psychologisches Profil.",
    "onboarding.soulProfileTitle": "Dein Seelenprofil",
    "onboarding.discovered": "Das haben wir über dich herausgefunden",
    "onboarding.yourStrengthsLabel": "Deine Stärken",
    "onboarding.growthOpportunities": "Wachstumschancen",
    "onboarding.deepFears": "Tiefe Ängste",
    "onboarding.personalityLabel": "Persönlichkeit",
    "onboarding.enterApp": "App betreten",
    "onboarding.analyzeProfile": "Mein Profil analysieren",
    "onboarding.next": "Weiter",
    "onboarding.chooseLanguage": "Wähle deine Sprache",
    "onboarding.chooseLanguageDesc": "Wähle deine bevorzugte Sprache für die App",
    "onboarding.tapReRecord": "Tippen zum erneut aufnehmen",
    "onboarding.tapRecord": "Tippen zum Aufnehmen deiner Antwort",
    "onboarding.orType": "Oder gib deine Antwort hier ein...",
    "onboarding.answerCaptured": "Antwort erfasst",
    "onboarding.transcribing": "Wird transkribiert...",
    "onboarding.question": "Frage",
    "onboarding.belief": "Glaube",
    "onboarding.analyzing": "Analyse",
    "onboarding.profile": "Profil",
    "onboarding.language": "Sprache",
    "onboarding.worldviewIslam": "Islam",
    "onboarding.worldviewChristianity": "Christentum",
    "onboarding.worldviewJudaism": "Judentum",
    "onboarding.worldviewBuddhism": "Buddhismus",
    "onboarding.worldviewHinduism": "Hinduismus",
    "onboarding.worldviewSpiritual": "Spirituell",
    "onboarding.worldviewNoPref": "Keine Präferenz",
    // Upgrade touchpoints
    "upgrade.badge": "Premium",
    "upgrade.winStreak": "Entdecke tiefere Muster in deiner Reise mit Premium",
    "upgrade.winEntries": "Schalte KI-Insights und Stimmungstrends mit Premium frei",
    "upgrade.lockedTitle": "Deine tiefere Seelenkarte",
    "upgrade.lockedDesc": "Schalte diese tiefere Analyse deiner Persönlichkeit, Stärken und verborgenen Muster frei",
    "upgrade.lockedLine1": "Deine Gefühlsmuster offenbaren eine stille Stärke",
    "upgrade.lockedLine2": "Verstecktes Thema: Nach Ruhe denkst du am klarsten",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    return (localStorage.getItem("app-language") as AppLanguage) || "en";
  });

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return (
      translations[language]?.[key] ||
      EXTRA_TRANSLATIONS[language]?.[key] ||
      UI_TRANSLATIONS[language]?.[key] ||
      translations.en[key] ||
      EXTRA_TRANSLATIONS.en[key] ||
      UI_TRANSLATIONS.en[key] ||
      key
    );
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};

// Helper to get full language name for AI prompts
export const getLanguageName = (code: AppLanguage): string => {
  return LANGUAGES.find((l) => l.code === code)?.name || "English";
};
