import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type AppLanguage = "en" | "fr" | "es" | "ar" | "zh" | "ja" | "sw" | "de";

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGES: { code: AppLanguage; name: string; flag: string; native: string }[] = [
  { code: "en", name: "English", flag: "🇺🇸", native: "English" },
  { code: "fr", name: "French", flag: "🇫🇷", native: "Français" },
  { code: "es", name: "Spanish", flag: "🇪🇸", native: "Español" },
  { code: "ar", name: "Arabic", flag: "🇸🇦", native: "العربية" },
  { code: "zh", name: "Chinese", flag: "🇨🇳", native: "中文" },
  { code: "ja", name: "Japanese", flag: "🇯🇵", native: "日本語" },
  { code: "sw", name: "Swahili", flag: "🇰🇪", native: "Kiswahili" },
  { code: "de", name: "German", flag: "🇩🇪", native: "Deutsch" },
];

// Translation dictionaries
const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    // Nav
    "nav.home": "Home",
    "nav.calendar": "Calendar",
    "nav.add": "Add",
    "nav.library": "Library",
    "nav.profile": "Profile",
    // Home
    "home.morning": "Morning",
    "home.afternoon": "Afternoon",
    "home.evening": "Evening",
    "home.quickCapture": "Quick Capture",
    "home.recentEntries": "Recent Entries",
    "home.viewAll": "View All",
    "home.noEntries": "No entries yet",
    "home.createFirst": "Create Your First Entry",
    // Record
    "record.title": "New Entry",
    "record.tapToRecord": "Tap to record your thoughts",
    "record.write": "Write",
    "record.howFeeling": "How are you feeling?",
    "record.selectMood": "Select your mood",
    "record.enhance": "Enhance",
    "record.save": "Save Entry",
    "record.saving": "Saving...",
    "record.recording": "Recording...",
    "record.processing": "Processing...",
    "record.limitReached": "Limit Reached",
    "record.textLimit": "Text entries",
    "record.audioLimit": "Audio entries",
    "record.today": "today",
    "record.thisWeek": "this week",
    "record.upgradePremium": "Upgrade to Premium",
    "record.newEntry": "NEW ENTRY",
    "record.howAreYou": "How are you, ",
    "record.tapToRecordAssessment": "Tap to Record Assessment",
    "record.recordingTime": "Recording {time}... Tap to stop",
    "record.audioLimitReached": "Audio limit reached",
    "record.writeLimit": "Write",
    "record.mood": "Mood",
    "record.aiCoachReflection": "AI COACH REFLECTION",
    "record.recentEntries": "RECENT ENTRIES",
    "record.viewAll": "View All",
    "record.whatsOnMind": "What's on your mind today?",
    "record.continue": "Continue",
    "record.originalTranscription": "Original Transcription",
    "record.enhanceWithAI": "Enhance with AI",
    "record.enhancing": "Enhancing...",
    "record.aiEnhanced": "AI Enhanced",
    "record.addTitle": "Add a title (optional)",
    "record.voicePlaybackLanguage": "Voice Playback Language",
    "record.chooseLanguage": "Choose which language to hear your story in",
    "record.generatingVoice": "Generating Voice...",
    "record.previewVoice": "Preview Voice (Optional)",
    "record.pause": "Pause",
    "record.playPreview": "Play Preview",
    "record.saveEntry": "Save Entry",
    "record.entrySaved": "Entry Saved!",
    "record.entrySavedDesc": "Your journal entry has been saved.",
    "record.textEntriesCount": "Text entries: {count}/2 today",
    "record.audioEntriesCount": "Audio entries: {count}/1 this week",
    "record.upgradeUnlimited": "Upgrade for unlimited",
    // Settings
    "settings.title": "Settings",
    "settings.account": "Account",
    "settings.profile": "Profile",
    "settings.security": "Security & PIN",
    "settings.appearance": "Appearance",
    "settings.themes": "Themes",
    "settings.fonts": "Fonts",
    "settings.darkMode": "Dark Mode",
    "settings.features": "Features",
    "settings.voice": "Voice Settings",
    "settings.goals": "Goals & Interests",
    "settings.reminders": "Reminders",
    "settings.export": "Export Journal",
    "settings.coaching": "AI Coaching",
    "settings.signOut": "Sign Out",
    "settings.admin": "Admin Dashboard",
    "settings.manageSubscription": "Manage Subscription",
    // Coaching
    "coaching.title": "AI Coach",
    "coaching.subtitle": "Your personal soul coach",
    "coaching.analyze": "Analyze My Week",
    "coaching.analyzing": "Analyzing...",
    "coaching.usageCounter": "coaching calls used this month",
    "coaching.limitReached": "Monthly coaching limit reached",
    // Calendar
    "calendar.title": "Journal Calendar",
    "calendar.noEntries": "No entries for this date",
    // Insights
    "insights.title": "Insights",
    "insights.moodTrend": "Mood Trend",
    "insights.weeklyActivity": "Weekly Activity",
    // Export
    "export.title": "Export Journal",
    "export.download": "Download all your entries",
    "export.soulBook": "Soul Book Builder (PDF)",
    "export.quickMarkdown": "Quick JSON / Markdown",
    "export.quickPDF": "Quick PDF",
    // Common
    "common.back": "Back",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.success": "Success",
    "common.upgrade": "Upgrade",
    "common.premium": "Premium",
    "common.language": "Language",
    // Pricing
    "pricing.title": "Choose Your Plan",
    "pricing.free": "Free",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/month",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.calendar": "Calendrier",
    "nav.add": "Ajouter",
    "nav.library": "Bibliothèque",
    "nav.profile": "Profil",
    "home.morning": "Bonjour",
    "home.afternoon": "Bon après-midi",
    "home.evening": "Bonsoir",
    "home.quickCapture": "Capture rapide",
    "home.recentEntries": "Entrées récentes",
    "home.viewAll": "Voir tout",
    "home.noEntries": "Aucune entrée",
    "home.createFirst": "Créer votre première entrée",
    "record.title": "Nouvelle entrée",
    "record.tapToRecord": "Appuyez pour enregistrer vos pensées",
    "record.write": "Écrire",
    "record.howFeeling": "Comment vous sentez-vous ?",
    "record.selectMood": "Sélectionnez votre humeur",
    "record.enhance": "Améliorer",
    "record.save": "Sauvegarder",
    "record.saving": "Sauvegarde...",
    "record.recording": "Enregistrement...",
    "record.processing": "Traitement...",
    "record.limitReached": "Limite atteinte",
    "record.textLimit": "Entrées texte",
    "record.audioLimit": "Entrées audio",
    "record.today": "aujourd'hui",
    "record.thisWeek": "cette semaine",
    "record.upgradePremium": "Passer à Premium",
    "record.newEntry": "NOUVELLE ENTRÉE",
    "record.howAreYou": "Comment allez-vous, ",
    "record.tapToRecordAssessment": "Appuyez pour enregistrer",
    "record.recordingTime": "Enregistrement {time}... Appuyez pour arrêter",
    "record.audioLimitReached": "Limite audio atteinte",
    "record.writeLimit": "Écrire",
    "record.mood": "Humeur",
    "record.aiCoachReflection": "RÉFLEXION DU COACH IA",
    "record.recentEntries": "ENTRÉES RÉCENTES",
    "record.viewAll": "Voir tout",
    "record.whatsOnMind": "Qu'avez-vous en tête aujourd'hui ?",
    "record.continue": "Continuer",
    "record.originalTranscription": "Transcription originale",
    "record.enhanceWithAI": "Améliorer avec l'IA",
    "record.enhancing": "Amélioration...",
    "record.aiEnhanced": "Amélioré par l'IA",
    "record.addTitle": "Ajouter un titre (optionnel)",
    "record.voicePlaybackLanguage": "Langue de lecture vocale",
    "record.chooseLanguage": "Choisissez la langue pour écouter votre histoire",
    "record.generatingVoice": "Génération de la voix...",
    "record.previewVoice": "Aperçu vocal (Optionnel)",
    "record.pause": "Pause",
    "record.playPreview": "Écouter l'aperçu",
    "record.saveEntry": "Sauvegarder l'entrée",
    "record.entrySaved": "Entrée sauvegardée !",
    "record.entrySavedDesc": "Votre entrée de journal a été sauvegardée.",
    "record.textEntriesCount": "Entrées texte : {count}/2 aujourd'hui",
    "record.audioEntriesCount": "Entrées audio : {count}/1 cette semaine",
    "record.upgradeUnlimited": "Passer en illimité",
    "settings.title": "Paramètres",
    "settings.account": "Compte",
    "settings.profile": "Profil",
    "settings.security": "Sécurité & PIN",
    "settings.appearance": "Apparence",
    "settings.themes": "Thèmes",
    "settings.fonts": "Polices",
    "settings.darkMode": "Mode sombre",
    "settings.features": "Fonctionnalités",
    "settings.voice": "Paramètres vocaux",
    "settings.goals": "Objectifs & Intérêts",
    "settings.reminders": "Rappels",
    "settings.export": "Exporter le journal",
    "settings.coaching": "Coach IA",
    "settings.signOut": "Déconnexion",
    "settings.admin": "Tableau de bord admin",
    "settings.manageSubscription": "Gérer l'abonnement",
    "coaching.title": "Coach IA",
    "coaching.subtitle": "Votre coach personnel",
    "coaching.analyze": "Analyser ma semaine",
    "coaching.analyzing": "Analyse en cours...",
    "coaching.usageCounter": "appels coaching utilisés ce mois",
    "coaching.limitReached": "Limite mensuelle de coaching atteinte",
    "calendar.title": "Calendrier du journal",
    "calendar.noEntries": "Aucune entrée pour cette date",
    "insights.title": "Aperçus",
    "insights.moodTrend": "Tendance d'humeur",
    "insights.weeklyActivity": "Activité hebdomadaire",
    "export.title": "Exporter le journal",
    "export.download": "Téléchargez toutes vos entrées",
    "export.soulBook": "Constructeur de livre d'âme (PDF)",
    "export.quickMarkdown": "JSON / Markdown rapide",
    "export.quickPDF": "PDF rapide",
    "common.back": "Retour",
    "common.cancel": "Annuler",
    "common.save": "Sauvegarder",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.loading": "Chargement...",
    "common.error": "Une erreur est survenue",
    "common.success": "Succès",
    "common.upgrade": "Passer en Premium",
    "common.premium": "Premium",
    "common.language": "Langue",
    "pricing.title": "Choisissez votre plan",
    "pricing.free": "Gratuit",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mois",
  },
  es: {
    "nav.home": "Inicio",
    "nav.calendar": "Calendario",
    "nav.add": "Añadir",
    "nav.library": "Biblioteca",
    "nav.profile": "Perfil",
    "home.morning": "Buenos días",
    "home.afternoon": "Buenas tardes",
    "home.evening": "Buenas noches",
    "home.quickCapture": "Captura rápida",
    "home.recentEntries": "Entradas recientes",
    "home.viewAll": "Ver todo",
    "home.noEntries": "Sin entradas aún",
    "home.createFirst": "Crea tu primera entrada",
    "record.title": "Nueva entrada",
    "record.tapToRecord": "Toca para grabar tus pensamientos",
    "record.write": "Escribir",
    "record.howFeeling": "¿Cómo te sientes?",
    "record.selectMood": "Selecciona tu estado de ánimo",
    "record.enhance": "Mejorar",
    "record.save": "Guardar",
    "record.saving": "Guardando...",
    "record.recording": "Grabando...",
    "record.processing": "Procesando...",
    "record.limitReached": "Límite alcanzado",
    "record.textLimit": "Entradas de texto",
    "record.audioLimit": "Entradas de audio",
    "record.today": "hoy",
    "record.thisWeek": "esta semana",
    "record.upgradePremium": "Actualizar a Premium",
    "record.newEntry": "NUEVA ENTRADA",
    "record.howAreYou": "¿Cómo estás, ",
    "record.tapToRecordAssessment": "Toca para grabar",
    "record.recordingTime": "Grabando {time}... Toca para detener",
    "record.audioLimitReached": "Límite de audio alcanzado",
    "record.writeLimit": "Escribir",
    "record.mood": "Ánimo",
    "record.aiCoachReflection": "REFLEXIÓN DEL COACH IA",
    "record.recentEntries": "ENTRADAS RECIENTES",
    "record.viewAll": "Ver todo",
    "record.whatsOnMind": "¿Qué tienes en mente hoy?",
    "record.continue": "Continuar",
    "record.originalTranscription": "Transcripción original",
    "record.enhanceWithAI": "Mejorar con IA",
    "record.enhancing": "Mejorando...",
    "record.aiEnhanced": "Mejorado por IA",
    "record.addTitle": "Añadir un título (opcional)",
    "record.voicePlaybackLanguage": "Idioma de reproducción de voz",
    "record.chooseLanguage": "Elige en qué idioma escuchar tu historia",
    "record.generatingVoice": "Generando voz...",
    "record.previewVoice": "Vista previa de voz (Opcional)",
    "record.pause": "Pausa",
    "record.playPreview": "Reproducir vista previa",
    "record.saveEntry": "Guardar entrada",
    "record.entrySaved": "¡Entrada guardada!",
    "record.entrySavedDesc": "Tu entrada de diario ha sido guardada.",
    "record.textEntriesCount": "Entradas de texto: {count}/2 hoy",
    "record.audioEntriesCount": "Entradas de audio: {count}/1 esta semana",
    "record.upgradeUnlimited": "Actualizar a ilimitado",
    "settings.title": "Configuración",
    "settings.account": "Cuenta",
    "settings.profile": "Perfil",
    "settings.security": "Seguridad y PIN",
    "settings.appearance": "Apariencia",
    "settings.themes": "Temas",
    "settings.fonts": "Fuentes",
    "settings.darkMode": "Modo oscuro",
    "settings.features": "Funciones",
    "settings.voice": "Configuración de voz",
    "settings.goals": "Objetivos e intereses",
    "settings.reminders": "Recordatorios",
    "settings.export": "Exportar diario",
    "settings.coaching": "Coach IA",
    "settings.signOut": "Cerrar sesión",
    "settings.admin": "Panel de administración",
    "settings.manageSubscription": "Gestionar suscripción",
    "coaching.title": "Coach IA",
    "coaching.subtitle": "Tu coach personal",
    "coaching.analyze": "Analizar mi semana",
    "coaching.analyzing": "Analizando...",
    "coaching.usageCounter": "llamadas de coaching usadas este mes",
    "coaching.limitReached": "Límite mensual de coaching alcanzado",
    "calendar.title": "Calendario del diario",
    "calendar.noEntries": "Sin entradas para esta fecha",
    "insights.title": "Perspectivas",
    "insights.moodTrend": "Tendencia de ánimo",
    "insights.weeklyActivity": "Actividad semanal",
    "export.title": "Exportar diario",
    "export.download": "Descarga todas tus entradas",
    "export.soulBook": "Constructor de libro del alma (PDF)",
    "export.quickMarkdown": "JSON / Markdown rápido",
    "export.quickPDF": "PDF rápido",
    "common.back": "Volver",
    "common.cancel": "Cancelar",
    "common.save": "Guardar",
    "common.delete": "Eliminar",
    "common.edit": "Editar",
    "common.loading": "Cargando...",
    "common.error": "Algo salió mal",
    "common.success": "Éxito",
    "common.upgrade": "Actualizar",
    "common.premium": "Premium",
    "common.language": "Idioma",
    "pricing.title": "Elige tu plan",
    "pricing.free": "Gratis",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mes",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.calendar": "التقويم",
    "nav.add": "إضافة",
    "nav.library": "المكتبة",
    "nav.profile": "الملف الشخصي",
    "home.morning": "صباح الخير",
    "home.afternoon": "مساء الخير",
    "home.evening": "مساء الخير",
    "home.quickCapture": "التقاط سريع",
    "home.recentEntries": "الإدخالات الأخيرة",
    "home.viewAll": "عرض الكل",
    "home.noEntries": "لا توجد إدخالات بعد",
    "home.createFirst": "أنشئ إدخالك الأول",
    "record.title": "إدخال جديد",
    "record.tapToRecord": "اضغط لتسجيل أفكارك",
    "record.write": "كتابة",
    "record.howFeeling": "كيف تشعر؟",
    "record.selectMood": "اختر مزاجك",
    "record.enhance": "تحسين",
    "record.save": "حفظ",
    "record.saving": "جارٍ الحفظ...",
    "record.recording": "جارٍ التسجيل...",
    "record.processing": "جارٍ المعالجة...",
    "record.limitReached": "تم الوصول للحد",
    "record.textLimit": "إدخالات نصية",
    "record.audioLimit": "إدخالات صوتية",
    "record.today": "اليوم",
    "record.thisWeek": "هذا الأسبوع",
    "record.upgradePremium": "ترقية إلى Premium",
    "record.newEntry": "إدخال جديد",
    "record.howAreYou": "كيف حالك، ",
    "record.tapToRecordAssessment": "اضغط للتسجيل",
    "record.recordingTime": "تسجيل {time}... اضغط للإيقاف",
    "record.audioLimitReached": "تم الوصول لحد الصوت",
    "record.writeLimit": "كتابة",
    "record.mood": "المزاج",
    "record.aiCoachReflection": "تأمل مدرب الذكاء الاصطناعي",
    "record.recentEntries": "الإدخالات الأخيرة",
    "record.viewAll": "عرض الكل",
    "record.whatsOnMind": "ما الذي يشغل بالك اليوم؟",
    "record.continue": "متابعة",
    "record.originalTranscription": "النص الأصلي",
    "record.enhanceWithAI": "تحسين بالذكاء الاصطناعي",
    "record.enhancing": "جارٍ التحسين...",
    "record.aiEnhanced": "محسّن بالذكاء الاصطناعي",
    "record.addTitle": "أضف عنوانًا (اختياري)",
    "record.voicePlaybackLanguage": "لغة تشغيل الصوت",
    "record.chooseLanguage": "اختر اللغة لسماع قصتك",
    "record.generatingVoice": "جارٍ إنشاء الصوت...",
    "record.previewVoice": "معاينة الصوت (اختياري)",
    "record.pause": "إيقاف مؤقت",
    "record.playPreview": "تشغيل المعاينة",
    "record.saveEntry": "حفظ الإدخال",
    "record.entrySaved": "تم حفظ الإدخال!",
    "record.entrySavedDesc": "تم حفظ إدخال يومياتك.",
    "record.textEntriesCount": "إدخالات نصية: {count}/2 اليوم",
    "record.audioEntriesCount": "إدخالات صوتية: {count}/1 هذا الأسبوع",
    "record.upgradeUnlimited": "ترقية للامحدود",
    "settings.title": "الإعدادات",
    "settings.account": "الحساب",
    "settings.profile": "الملف الشخصي",
    "settings.security": "الأمان و PIN",
    "settings.appearance": "المظهر",
    "settings.themes": "السمات",
    "settings.fonts": "الخطوط",
    "settings.darkMode": "الوضع الداكن",
    "settings.features": "الميزات",
    "settings.voice": "إعدادات الصوت",
    "settings.goals": "الأهداف والاهتمامات",
    "settings.reminders": "التذكيرات",
    "settings.export": "تصدير اليوميات",
    "settings.coaching": "مدرب الذكاء الاصطناعي",
    "settings.signOut": "تسجيل الخروج",
    "settings.admin": "لوحة الإدارة",
    "settings.manageSubscription": "إدارة الاشتراك",
    "coaching.title": "مدرب الذكاء الاصطناعي",
    "coaching.subtitle": "مدربك الشخصي",
    "coaching.analyze": "تحليل أسبوعي",
    "coaching.analyzing": "جارٍ التحليل...",
    "coaching.usageCounter": "مكالمات تدريب مستخدمة هذا الشهر",
    "coaching.limitReached": "تم الوصول لحد التدريب الشهري",
    "calendar.title": "تقويم اليوميات",
    "calendar.noEntries": "لا توجد إدخالات لهذا التاريخ",
    "insights.title": "رؤى",
    "insights.moodTrend": "اتجاه المزاج",
    "insights.weeklyActivity": "النشاط الأسبوعي",
    "export.title": "تصدير اليوميات",
    "export.download": "تنزيل جميع إدخالاتك",
    "export.soulBook": "منشئ كتاب الروح (PDF)",
    "export.quickMarkdown": "JSON / Markdown سريع",
    "export.quickPDF": "PDF سريع",
    "common.back": "رجوع",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.loading": "جارٍ التحميل...",
    "common.error": "حدث خطأ ما",
    "common.success": "نجاح",
    "common.upgrade": "ترقية",
    "common.premium": "Premium",
    "common.language": "اللغة",
    "pricing.title": "اختر خطتك",
    "pricing.free": "مجاني",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/شهر",
  },
  zh: {
    "nav.home": "首页",
    "nav.calendar": "日历",
    "nav.add": "添加",
    "nav.library": "图书馆",
    "nav.profile": "个人资料",
    "home.morning": "早上好",
    "home.afternoon": "下午好",
    "home.evening": "晚上好",
    "home.quickCapture": "快速记录",
    "home.recentEntries": "最近的条目",
    "home.viewAll": "查看全部",
    "home.noEntries": "还没有条目",
    "home.createFirst": "创建您的第一个条目",
    "record.title": "新条目",
    "record.tapToRecord": "点击录制您的想法",
    "record.write": "写作",
    "record.howFeeling": "您感觉如何？",
    "record.selectMood": "选择您的心情",
    "record.enhance": "优化",
    "record.save": "保存",
    "record.saving": "保存中...",
    "record.recording": "录制中...",
    "record.processing": "处理中...",
    "record.limitReached": "已达上限",
    "record.textLimit": "文字条目",
    "record.audioLimit": "音频条目",
    "record.today": "今天",
    "record.thisWeek": "本周",
    "record.upgradePremium": "升级至 Premium",
    "record.newEntry": "新条目",
    "record.howAreYou": "你好吗，",
    "record.tapToRecordAssessment": "点击录制",
    "record.recordingTime": "录制中 {time}... 点击停止",
    "record.audioLimitReached": "音频上限已达",
    "record.writeLimit": "写作",
    "record.mood": "心情",
    "record.aiCoachReflection": "AI 教练反思",
    "record.recentEntries": "最近条目",
    "record.viewAll": "查看全部",
    "record.whatsOnMind": "今天在想什么？",
    "record.continue": "继续",
    "record.originalTranscription": "原始转录",
    "record.enhanceWithAI": "AI 优化",
    "record.enhancing": "优化中...",
    "record.aiEnhanced": "AI 已优化",
    "record.addTitle": "添加标题（可选）",
    "record.voicePlaybackLanguage": "语音播放语言",
    "record.chooseLanguage": "选择收听故事的语言",
    "record.generatingVoice": "生成语音中...",
    "record.previewVoice": "预览语音（可选）",
    "record.pause": "暂停",
    "record.playPreview": "播放预览",
    "record.saveEntry": "保存条目",
    "record.entrySaved": "条目已保存！",
    "record.entrySavedDesc": "您的日记条目已保存。",
    "record.textEntriesCount": "文字条目：{count}/2 今天",
    "record.audioEntriesCount": "音频条目：{count}/1 本周",
    "record.upgradeUnlimited": "升级至无限",
    "settings.title": "设置",
    "settings.account": "账户",
    "settings.profile": "个人资料",
    "settings.security": "安全与 PIN",
    "settings.appearance": "外观",
    "settings.themes": "主题",
    "settings.fonts": "字体",
    "settings.darkMode": "深色模式",
    "settings.features": "功能",
    "settings.voice": "语音设置",
    "settings.goals": "目标与兴趣",
    "settings.reminders": "提醒",
    "settings.export": "导出日记",
    "settings.coaching": "AI 教练",
    "settings.signOut": "退出登录",
    "settings.admin": "管理后台",
    "settings.manageSubscription": "管理订阅",
    "coaching.title": "AI 教练",
    "coaching.subtitle": "您的个人教练",
    "coaching.analyze": "分析我的一周",
    "coaching.analyzing": "分析中...",
    "coaching.usageCounter": "本月已使用教练次数",
    "coaching.limitReached": "已达月度教练上限",
    "calendar.title": "日记日历",
    "calendar.noEntries": "此日期无条目",
    "insights.title": "洞察",
    "insights.moodTrend": "情绪趋势",
    "insights.weeklyActivity": "每周活动",
    "export.title": "导出日记",
    "export.download": "下载所有条目",
    "export.soulBook": "灵魂之书构建器 (PDF)",
    "export.quickMarkdown": "快速 JSON / Markdown",
    "export.quickPDF": "快速 PDF",
    "common.back": "返回",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.loading": "加载中...",
    "common.error": "出了点问题",
    "common.success": "成功",
    "common.upgrade": "升级",
    "common.premium": "Premium",
    "common.language": "语言",
    "pricing.title": "选择您的计划",
    "pricing.free": "免费",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/月",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.calendar": "カレンダー",
    "nav.add": "追加",
    "nav.library": "ライブラリ",
    "nav.profile": "プロフィール",
    "home.morning": "おはようございます",
    "home.afternoon": "こんにちは",
    "home.evening": "こんばんは",
    "home.quickCapture": "クイック記録",
    "home.recentEntries": "最近のエントリー",
    "home.viewAll": "すべて表示",
    "home.noEntries": "エントリーがありません",
    "home.createFirst": "最初のエントリーを作成",
    "record.title": "新しいエントリー",
    "record.tapToRecord": "タップして思考を記録",
    "record.write": "書く",
    "record.howFeeling": "気分はどうですか？",
    "record.selectMood": "気分を選択",
    "record.enhance": "改善",
    "record.save": "保存",
    "record.saving": "保存中...",
    "record.recording": "録音中...",
    "record.processing": "処理中...",
    "record.limitReached": "上限に達しました",
    "record.textLimit": "テキストエントリー",
    "record.audioLimit": "音声エントリー",
    "record.today": "今日",
    "record.thisWeek": "今週",
    "record.upgradePremium": "Premiumにアップグレード",
    "record.newEntry": "新しいエントリー",
    "record.howAreYou": "お元気ですか、",
    "record.tapToRecordAssessment": "タップして録音",
    "record.recordingTime": "録音中 {time}... タップで停止",
    "record.audioLimitReached": "音声上限に達しました",
    "record.writeLimit": "書く",
    "record.mood": "気分",
    "record.aiCoachReflection": "AIコーチの振り返り",
    "record.recentEntries": "最近のエントリー",
    "record.viewAll": "すべて表示",
    "record.whatsOnMind": "今日は何を考えていますか？",
    "record.continue": "続ける",
    "record.originalTranscription": "元の文字起こし",
    "record.enhanceWithAI": "AIで改善",
    "record.enhancing": "改善中...",
    "record.aiEnhanced": "AI改善済み",
    "record.addTitle": "タイトルを追加（任意）",
    "record.voicePlaybackLanguage": "音声再生言語",
    "record.chooseLanguage": "ストーリーを聞く言語を選択",
    "record.generatingVoice": "音声生成中...",
    "record.previewVoice": "音声プレビュー（任意）",
    "record.pause": "一時停止",
    "record.playPreview": "プレビュー再生",
    "record.saveEntry": "エントリーを保存",
    "record.entrySaved": "エントリーが保存されました！",
    "record.entrySavedDesc": "日記エントリーが保存されました。",
    "record.textEntriesCount": "テキスト：{count}/2 今日",
    "record.audioEntriesCount": "音声：{count}/1 今週",
    "record.upgradeUnlimited": "無制限にアップグレード",
    "settings.title": "設定",
    "settings.account": "アカウント",
    "settings.profile": "プロフィール",
    "settings.security": "セキュリティ & PIN",
    "settings.appearance": "外観",
    "settings.themes": "テーマ",
    "settings.fonts": "フォント",
    "settings.darkMode": "ダークモード",
    "settings.features": "機能",
    "settings.voice": "音声設定",
    "settings.goals": "目標と興味",
    "settings.reminders": "リマインダー",
    "settings.export": "日記をエクスポート",
    "settings.coaching": "AIコーチ",
    "settings.signOut": "サインアウト",
    "settings.admin": "管理ダッシュボード",
    "settings.manageSubscription": "サブスクリプション管理",
    "coaching.title": "AIコーチ",
    "coaching.subtitle": "あなたの個人コーチ",
    "coaching.analyze": "今週を分析",
    "coaching.analyzing": "分析中...",
    "coaching.usageCounter": "今月のコーチング利用回数",
    "coaching.limitReached": "月間コーチング上限に達しました",
    "calendar.title": "日記カレンダー",
    "calendar.noEntries": "この日付のエントリーはありません",
    "insights.title": "インサイト",
    "insights.moodTrend": "気分の傾向",
    "insights.weeklyActivity": "週間アクティビティ",
    "export.title": "日記をエクスポート",
    "export.download": "すべてのエントリーをダウンロード",
    "export.soulBook": "ソウルブックビルダー (PDF)",
    "export.quickMarkdown": "クイック JSON / Markdown",
    "export.quickPDF": "クイック PDF",
    "common.back": "戻る",
    "common.cancel": "キャンセル",
    "common.save": "保存",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.loading": "読み込み中...",
    "common.error": "エラーが発生しました",
    "common.success": "成功",
    "common.upgrade": "アップグレード",
    "common.premium": "Premium",
    "common.language": "言語",
    "pricing.title": "プランを選択",
    "pricing.free": "無料",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/月",
  },
  sw: {
    "nav.home": "Nyumbani",
    "nav.calendar": "Kalenda",
    "nav.add": "Ongeza",
    "nav.library": "Maktaba",
    "nav.profile": "Wasifu",
    "home.morning": "Habari za asubuhi",
    "home.afternoon": "Habari za mchana",
    "home.evening": "Habari za jioni",
    "home.quickCapture": "Chukua haraka",
    "home.recentEntries": "Maingizo ya hivi karibuni",
    "home.viewAll": "Tazama yote",
    "home.noEntries": "Hakuna maingizo bado",
    "home.createFirst": "Unda ingizo lako la kwanza",
    "record.title": "Ingizo jipya",
    "record.tapToRecord": "Gusa ili kurekodi mawazo yako",
    "record.write": "Andika",
    "record.howFeeling": "Unajisikiaje?",
    "record.selectMood": "Chagua hali yako",
    "record.enhance": "Boresha",
    "record.save": "Hifadhi",
    "record.saving": "Inahifadhi...",
    "record.recording": "Inarekodi...",
    "record.processing": "Inachakata...",
    "record.limitReached": "Kikomo kimefikiwa",
    "record.textLimit": "Maingizo ya maandishi",
    "record.audioLimit": "Maingizo ya sauti",
    "record.today": "leo",
    "record.thisWeek": "wiki hii",
    "record.upgradePremium": "Panda hadi Premium",
    "record.newEntry": "INGIZO JIPYA",
    "record.howAreYou": "Habari yako, ",
    "record.tapToRecordAssessment": "Gusa ili kurekodi",
    "record.recordingTime": "Inarekodi {time}... Gusa kusimamisha",
    "record.audioLimitReached": "Kikomo cha sauti kimefikiwa",
    "record.writeLimit": "Andika",
    "record.mood": "Hali",
    "record.aiCoachReflection": "TAFAKURI YA KOCHA WA AI",
    "record.recentEntries": "MAINGIZO YA HIVI KARIBUNI",
    "record.viewAll": "Tazama yote",
    "record.whatsOnMind": "Una nini akilini leo?",
    "record.continue": "Endelea",
    "record.originalTranscription": "Maandishi ya awali",
    "record.enhanceWithAI": "Boresha na AI",
    "record.enhancing": "Inaboresha...",
    "record.aiEnhanced": "Imeboreshwa na AI",
    "record.addTitle": "Ongeza kichwa (hiari)",
    "record.voicePlaybackLanguage": "Lugha ya kucheza sauti",
    "record.chooseLanguage": "Chagua lugha ya kusikiliza hadithi yako",
    "record.generatingVoice": "Inaunda sauti...",
    "record.previewVoice": "Hakiki sauti (Hiari)",
    "record.pause": "Simamisha",
    "record.playPreview": "Cheza hakiki",
    "record.saveEntry": "Hifadhi ingizo",
    "record.entrySaved": "Ingizo limehifadhiwa!",
    "record.entrySavedDesc": "Ingizo lako la jarida limehifadhiwa.",
    "record.textEntriesCount": "Maingizo ya maandishi: {count}/2 leo",
    "record.audioEntriesCount": "Maingizo ya sauti: {count}/1 wiki hii",
    "record.upgradeUnlimited": "Panda kwa bila kikomo",
    "settings.title": "Mipangilio",
    "settings.account": "Akaunti",
    "settings.profile": "Wasifu",
    "settings.security": "Usalama & PIN",
    "settings.appearance": "Muonekano",
    "settings.themes": "Mandhari",
    "settings.fonts": "Fonti",
    "settings.darkMode": "Hali ya giza",
    "settings.features": "Vipengele",
    "settings.voice": "Mipangilio ya sauti",
    "settings.goals": "Malengo na Maslahi",
    "settings.reminders": "Vikumbusho",
    "settings.export": "Hamisha jarida",
    "settings.coaching": "Kocha wa AI",
    "settings.signOut": "Ondoka",
    "settings.admin": "Dashibodi ya msimamizi",
    "settings.manageSubscription": "Dhibiti usajili",
    "coaching.title": "Kocha wa AI",
    "coaching.subtitle": "Kocha wako binafsi",
    "coaching.analyze": "Changanua wiki yangu",
    "coaching.analyzing": "Inachambua...",
    "coaching.usageCounter": "simu za kocha zilizotumika mwezi huu",
    "coaching.limitReached": "Kikomo cha kocha cha mwezi kimefikiwa",
    "calendar.title": "Kalenda ya jarida",
    "calendar.noEntries": "Hakuna maingizo kwa tarehe hii",
    "insights.title": "Maarifa",
    "insights.moodTrend": "Mwenendo wa hali",
    "insights.weeklyActivity": "Shughuli za wiki",
    "export.title": "Hamisha jarida",
    "export.download": "Pakua maingizo yako yote",
    "export.soulBook": "Mjenzi wa Kitabu cha Roho (PDF)",
    "export.quickMarkdown": "JSON / Markdown haraka",
    "export.quickPDF": "PDF haraka",
    "common.back": "Rudi",
    "common.cancel": "Ghairi",
    "common.save": "Hifadhi",
    "common.delete": "Futa",
    "common.edit": "Hariri",
    "common.loading": "Inapakia...",
    "common.error": "Kuna kosa limetokea",
    "common.success": "Imefanikiwa",
    "common.upgrade": "Panda daraja",
    "common.premium": "Premium",
    "common.language": "Lugha",
    "pricing.title": "Chagua mpango wako",
    "pricing.free": "Bure",
    "pricing.premium": "Premium",
    "pricing.perMonth": "/mwezi",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    return (localStorage.getItem("app-language") as AppLanguage) || "en";
  });

  const setLanguage = (lang: AppLanguage) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const dir = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, dir]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};

// Helper to get full language name for AI prompts
export const getLanguageName = (code: AppLanguage): string => {
  return LANGUAGES.find((l) => l.code === code)?.name || "English";
};
